### ISSUE TITLE
Java mode not found

### ISSUE THREAD

**Issue by Loadus** [processing/processing-android#106]
Build fails when Java mode is not found - any instructions on what to put and where (I'm most likely doing something seriously wrong)?

Complete output >> http://pastebin.com/YGjArhLa

**Comment by omerjerk** [comment]
Which version are you on ?

**Comment by Loadus** [comment]
This was the latest that was cloned just hours before. 

There were lots of other problems but they were solvable, this stumps me, because I don't know who needs to read who and where (I don't have much knowledge about the build mechanism).

**Comment by omerjerk** [comment]
The master branch of this repository is not buildable with the master branch of processing.
processing has moved ahead and we haven't updated this repository yet. 
Why are you really building the Android mode yourself ?
If you want to run your processing sketches on your phone, then just download processing 2.2.1 from the main website, open the IDE and from there, download the Android mode.
In case, if you really want to build Android mode from source, apply this pull request - https://github.com/processing/processing-android/pull/98 .

**Comment by Loadus** [comment]
Aaah, I didn't know that. I was trying to find a way to get createShape() working on Android. But I gave up and used a very very ugly hack. 

I haven't learned Git yet, if I do a pull request I'll most likely divide something with 0. 

Cheers for the tips! ^.^
