### ISSUE TITLE
Enable createShape()?

### ISSUE THREAD

**Issue by Loadus** [processing/processing-android#107]
createShape() seems to be in the source, but it's marked as unapproved and protected. Can it be enabled somehow? I tried subclassing it but ran out of coding skills really fast - same when I tried to build it from source. 

An app that I'm cooking up creates shapes from the user's input so this would be a key to a lot of things. : )

**Comment by codeanticode** [comment]
will look into this, createShape() should work the same way as it does on the desktop.

**Comment by Loadus** [comment]
createShape() works beautifully now in Processing 3.0. Thank you very much!
