### ISSUE TITLE
LowLevelGL Example crash immediatly

### ISSUE THREAD

**Issue by tlecoz** [processing/processing-android#112]
Hello !

I would like to do some performance test with Shaders on my android tablet but the LowLevelGL example crash with the error message : 

OpenGL error 1280 at bot beginDraw(): invalid enum FATAL EXCEPTION: GLThread 4879 Process: processing.test.lowlevelgl, PID: 13527 java.lang.RuntimeException: GL function glDrawBuffer() is not available on this hardware (or driver) Read http://wiki.processing.org/w/OpenGL_Issues for help. at processing.opengl.PGLES.drawBuffer(Unknown Source) at processing.opengl.PGraphicsOpenGL.restoreGL(Unknown Source) at processing.opengl.PGraphicsOpenGL.endPGL(Unknown Source) at processing.core.PApplet.endPGL(Unknown Source) at processing.test.lowlevelgl.LowLevelGL.draw(LowLevelGL.java:79) at processing.core.PApplet.handleDraw(Unknown Source) at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source) at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532) at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)

But it doesn"t make any sense because my tablet is a Samsung Galaxy Note 4 and I am 100% sure the GPU is enabled on it. 
Moreover the 'StaticParticleRetained' example works fine (32 000 particles at 60 FPS) then I suppose that there is a small bug in the LowLevelGL example.

Please fix it ! :)

Thanks for your work !

**Comment by tlecoz** [comment]
Hello !

I'm sorry to ask this but I would like to know if you're going to fix it soon ( < 2 months) or if I have to choose another tool to create my android app.

Thank you again for all your work

**Comment by codeanticode** [comment]
Hi, we are currently working on the android mode with @omerjerk, as part of Google Summer of Code. We should have a working version compatible with Processing 3 soon.

**Comment by omerjerk** [comment]
This is easily fixable. We should fix this by the end of next week.

**Comment by tlecoz** [comment]
Great news ! Thanks a lot !

**Comment by DEHiCKA** [comment]
Please fix it! All bare opengl stuff  is not working in Android mode becouse of this damn bug
Thanks!

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/ecbab95e3938683135de261cf506aebf7d219b76
