### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by Bazmundi** [processing/processing-android#115]
Happily coding for Samsung S2.

Decided to change version of Android SDK build tools, and changed from 19.1 to 22.0.1.

However, with no source file changes the build C:\Development\adt-bundle-windows-x86_64\sdk\tools\ant\build.xml started failing with message Cannot run program:
C:\Users\rr\AppData\Local\Temp\android7214396220583717459sketch\${aapt}

I thought this might have been the build tool change so I changed back to 19.1 and the broken build problem persists.

So, again, source file compiles, installs and runs on Samsung S2 up until Android SDK manager is used to change Android SDK build tools.

Any suggestions please.

I will delete and then re-install Processing in the meantime.

Cheers,
A

**Comment by Bazmundi** [comment]
Worse.  I downloaded new SDK tools and pointed the processing IDE to that and still same problem.

**Comment by Bazmundi** [comment]
Worse, it doesn't matter what source file I use.

I have tried running processing in administrator mode etc.

**Comment by RShankar** [comment]
I teach a course that uses Prof. Sauter's book. Several students in the class (and I)  have this problem. For some it is OK. I found this online: http://connortumbleson.com/2015/02/16/fixing-apktool-bug713/ . Any recommendations on the next step? I have tried  everything Bazmundi has tried. Same Problem.  Thank you.

**Comment by codeanticode** [comment]
hey guys, we just pushed a new release of the android mode

https://github.com/processing/processing-android/releases

It is meant to be used with Processing 3.0a11, which is not out yet, so you can test it by building Processing from source.

**Comment by codeanticode** [comment]
Could you test the latest release of the mode with Processing 3.0 alpha 11 and let me know if it works for you? Thanks!

**Comment by codeanticode** [comment]
@Bazmundi could you test the latest version of the mode with Processing 3.0 beta 1 or newer and let us know if you still have this problem.

**Comment by Bazmundi** [comment]
Nope. Happy enough with 2.whatzit.
