### ISSUE TITLE
Build broken with latest processing core

### ISSUE THREAD

**Issue by fiskurgit** [processing/processing-android#116]
Is the SurfaceInfo class in the main processing project new? AndroidPreprocessor seems to be expecting an int[], have put this quick fix together: https://gist.github.com/fiskurgit/faf756da90be76639604

Also, is there a forum where I could discuss the possibility of changing the structure of this project? Having a huge 'PApplet' class that extends Activity is unhelpful for Android development, the library would be far better off exposing a 'ProcessingView' that could be dropped into any layout. Happy to do the work but don't want to submit a large pull request if it's unlikely to be accepted.

**Comment by omerjerk** [comment]
Hi @fiskurgit,
We are working on both the issues you mentioned during this Google Summer of Code.
We're converting PApplet class from Activity to a Fragment so that it can be added anywhere the user wants.

**Comment by fiskurgit** [comment]
Great stuff, I won't duplicate the effort then! 

A View may be preferable to a Fragment though (or at least the API should make both available), as there'll be issues using a Fragment in a DreamService. Processing is perfect for creating Daydream screensavers on Android TV...

**Comment by codeanticode** [comment]
Port to Fragment already implemented, will be available  in next release of the mode.
