### ISSUE TITLE
Goodbye Gingerbread!

### ISSUE THREAD

**Issue by benfry** [processing/processing-android#119]
For 3.0, we'll be dropping Gingerbread support and moving to API 15. A few things for us to consider:

* What documentation or other wiki pages need to be updated? (Please file issues for these, in this repo)
* What code can we remove that was a workaround for supporting Gingerbread? (i.e. in the past we had to get a GL method via reflection, though I think that was to support Froyo/2.2)
* Is there anything we can clean up or remove from the manifest and properties files?
* Do we need anything else to notify users about the change?

This is a jumping off point for other issues. Once we're comfortable that we have things covered, let's close this one as soon as possible.

CC @codeanticode @omerjerk

**Comment by omerjerk** [comment]
I guess, first thing should be to remove support v4 jar from the code.

**Comment by codeanticode** [comment]
@omerjerk do we need to do anything else to close this issue?
