### ISSUE TITLE
no build

### ISSUE THREAD

**Issue by onlylemi** [processing/processing-android#124]
I user, but have some problems, please help me! why ?
CameraView extendx PApplet.
but "Type mismatch: cannot convert from CameraView to Fragment"

![12](https://cloud.githubusercontent.com/assets/7680698/8887475/edc09e8e-32b5-11e5-856a-062b7c5c7d90.png)

**Comment by omerjerk** [comment]
Are using the latest release ?
The latest release doesn't contain the changes in which PApplet is a child of Fragment. Those changes have already been merged to the master branch of this repository though.
We should be able to make another release this week. 
If you really want to get things running, you'll have to build android-core.zip yourself.

**Comment by onlylemi** [comment]
@omerjerk Thank you.
I don't use the latest release. In addition, I find that I don‘t use `size()` in `setup()`, but can use in `settings()` or not use `size()`. 
Now I can use it in **eclipse**, but not use the latest release in **processing**.

**Comment by codeanticode** [comment]
new release of the mode will be out shortly, and will incorporate the Fragment changes from @omerjerk
