### ISSUE TITLE
Processing IDE exits if you don't answer to Automatic/Manual Android SDK dialog

### ISSUE THREAD

**Issue by darkwave** [processing/processing-android#138]
I'm having a pretty subtle issue here: if you wait some seconds answering SDK Automatic/Manual dialog after installing Android Mode *Processing IDE exits silently*. It simply quits with no messages.

I tested it on a fresh installed latest version of both IDE and Android Mode.

**Comment by omerjerk** [comment]
I'm not having this issue.
Can you try again if you're actually having it or was it just by mistake ?

Thanks

**Comment by codeanticode** [comment]
Fixed in recent RCs
