### ISSUE TITLE
Unable to start Java mode

### ISSUE THREAD

**Issue by Dringo42** [processing/processing-android#139]
I've updated to the new version of processing 3.0b4 and attempted to install android mode where I received a error every time I try to swap over to android mode.
![picture1](https://cloud.githubusercontent.com/assets/11827306/9435879/8642a47c-4a8a-11e5-936b-b0122a95e32a.png)

**Comment by codeanticode** [comment]
Ok, thanks for letting us know. It seems you are on windows, what version?

**Comment by codeanticode** [comment]
actually, it is an issue in Processing core, not in the android mode, might be fixed with https://github.com/processing/processing/commit/0836dad678b3a71b83bca07da66b1cbee3ded06d

**Comment by benfry** [comment]
Fixed with 3.0 beta 5.

**Comment by Dringo42** [comment]
Thanks for the response. This is using the latest version of android mode
3.0-alpha3.

**Comment by benfry** [comment]
The latest version of Processing (3.0 beta 5, posted ~8 hours ago) has the fix, download that and you should be all set.

**Comment by Dringo42** [comment]
Thanks. I've updated and I can now open it. I do have a new bug though.
Every time I run a sketch I receive this error. The thread number seems to
change each time.

​
