### ISSUE TITLE
PApplet's Activity needed

### ISSUE THREAD

**Issue by emnullfuenf** [processing/processing-android#141]
I am currently implementing Vuforia AR for Processing. Until Processing 3.0b1 i could pass the PApplet (this) as Activity to the Vuforia initialization. This doesn't work anymore.

Is there a way to get the PApplet's Activity?

The activity itself is declared private.
private Activity activity;

this.getActivity() isn't available from within the sketch.
activity = getActivity();

**Comment by codeanticode** [comment]
This is a result of making PApplet a descendant of Fragment. @omerjerk what do you think about this?

**Comment by emnullfuenf** [comment]
It seems that this.getActivity() is actually working. Although Processing shows an error that "getActivity() is not available and marks it red.

**Comment by omerjerk** [comment]
Yeah. getActivity() returns the activity to which PApplet is attached. 
getActivity() is marked red because we're having problem with the PDE error checking.
