### ISSUE TITLE
onCreate() doesn't work anymore

### ISSUE THREAD

**Issue by emnullfuenf** [processing/processing-android#142]
Until Processing 3.0b1 i could override and call onCreate(). It doesn't work anymore with the current version.

Example:

```
import android.app.Activity;
import android.os.Bundle;

void setup()
{
  println("Setup"); // works
}

//@Override
public void onCreate(Bundle savedInstanceState)
{
  super.onCreate(savedInstanceState);
  println("onCreate"); // doesn't print
}
```

Furthermore i get errors regarding the imports:
"Only a type can be imported, android.app.Activity resolves a package"
"The class Activity does not exist"
"The class Bundle does not exist"

**Comment by DEHiCKA** [comment]
Same here.
Imports from android.os, android.view are not working anymore.

**Comment by DEHiCKA** [comment]
Also calls like getWindowManager(), getWindow() are not working for me anymore even though i've imported android.view.WindowManager;

ERROR in ... The method get...() is undefined

**Comment by codeanticode** [comment]
@omerjerk do you have any thoughts on this?

**Comment by omerjerk** [comment]
@DEHiCKA 
You can call those methods by preceding them with `getActivity()`.
For e.g. `getActivity().getWindowManager()`

**Comment by DEHiCKA** [comment]
Thanks. Missed that since R241 it's a Fragment instead of Activity.

**Comment by omerjerk** [comment]
Also, we've fixed all the import related errors in the latest release.
This commit https://github.com/processing/processing/commit/f397415ba04cfdd1aa01e0ffc84b45134e37aa88 fixes the bug.
