### ISSUE TITLE
installing Android Mode on a machine that's never run it throws SDK errors

### ISSUE THREAD

**Issue by benfry** [processing/processing-android#151]
Complains that the Android SDK is not available and that the Mode will be all but disabled, but doesn't prompt user to do SDK installation.

**Comment by omerjerk** [comment]
which OS ?

**Comment by benfry** [comment]
OS X and Windows.

**Comment by benfry** [comment]
Also puts up the error each time you start the PDE. 

The initial error immediately after installing in the Contribution Manager:

![pastedgraphic-3](https://cloud.githubusercontent.com/assets/1623101/10202944/4c0e526a-6781-11e5-9158-5c255cc55637.png)

**Comment by farzanajabin** [comment]
Hi, I am also having the same issue in OS X

**Comment by codeanticode** [comment]
I can reproduce this issue (on OS X). After closing the "bad day" warning, and then switching to the Android mode in the PDE, the SDK selection window does show up, where one can choose between "Locate SDK path manually" and "Download SDK automatically". However, clicking on "Download SDK automatically" does not trigger the SDK download. This functionality used to work in a recent beta (probably 6). @omerjerk do you have time to look into this?

**Comment by farzanajabin** [comment]
I manage to direct my processing towards the Android SDK File, by selecting the "Locate SDK path manually", as initially I could not view the Library directory to show. It does not prompt me the above erros as "bad day".  Yes! the "Download SDK automatically" does not trigger, although it shows that it completes the download. However, after all is complete, now processing shows an error of that "could not create a virtual device for the emulator".

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/a80791702cc59951222b8d9fef4102fbed807e0e
