### ISSUE TITLE
Hide navigation bar?

### ISSUE THREAD

**Issue by imartini** [processing/processing-android#155]
Hi!!

When I run the aplication, in the screen of the smartphone appears the navigation bar (return, home, settings buttons and black background). I modified the manifest.xml, use the sketch permissions, and other code with onCreate() functions, but nothing works.
there any way to hide the navigation bar?

Thanks!!

**Comment by codeanticode** [comment]
Hi, this is a coding question that should be posted on the forum. The android developer site has [a page](https://developer.android.com/training/system-ui/navigation.html) on hiding the navigation bar.
