### ISSUE TITLE
Provide download for SDK in Android mode

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#156]
Moved from https://github.com/processing/processing/issues/3986:

If the user attempts to use Android mode and does not have the SDK, the popup should offer instructions on how to obtain and install the developer tools.

**Comment by codeanticode** [comment]
@gingerdeadshot It this the popup you refer to:

![image](https://cloud.githubusercontent.com/assets/62246/10430325/8d08d0d4-70cc-11e5-919b-bf4c7574263f.png)

? It points users to the http://developer.android.com/sdk

**Comment by gingerdeadshot** [comment]
Yes, except this popup does not appear for me. The popup that appears on my computer simply says "Android SDK could not be loaded - Android mode will be all but disabled."

**Comment by codeanticode** [comment]
what version of the mode are you using?

**Comment by gingerdeadshot** [comment]
The latest version available.

**Comment by codeanticode** [comment]
@omerjerk I noticed that often the "It's gonna to be a bad day" popup shows up several times when the SDK is not available:

![image](https://cloud.githubusercontent.com/assets/62246/10459812/549a277e-719f-11e5-9658-75d11d3e61ec.png)

and the SDK installation dialog does not consistently appear instead of it. Do you have some time to look at the startup logic of the mode, so we make sure that the right dialog is displayed?

**Comment by gingerdeadshot** [comment]
Yeah, that's the popup that comes up, the "it's gonna be a bad day" one.

**Comment by codeanticode** [comment]
ok, if you try to switch to the android mode from the PDE, after closing the "bad day" popup, you should get the SDK installation dialog. It does not work very consistently, but it should show up at some point. Anyways, we will try to fix the startup logic so it is not confusing.

**Comment by gingerdeadshot** [comment]
Perfect. Thanks.

**Comment by kasperkamperman** [comment]
Same problem here. "It's gonna be a bad day". Switching to Android Mode worked to locate the SDK. However it might be smart to pop-up this SDK directly (or remove the "bad day" warning if you are not in Android mode).

**Comment by Loadus** [comment]
There is also a chance that the user gets stuck with a pop up saying "This version of Android Mode is not compatible with this version of Processing etc" and Processing won't start up - maybe fall back to Java mode if that error happens? [this might fall into a totally different issue category]

**Comment by omerjerk** [comment]
I'll fix this asap.

**Comment by codeanticode** [comment]
@omerjerk Thanks! I think we need to revise the logic of when the different popups are shown to the user.

For instance, right after installing the mode, it is very likely that the SDK is not available yet. Should we show the "bad day" popup right away, or ask for the SDK installation? I'd prefer the latter.

What @Loadus mentions is also a related issue, which I have experienced myself. If an incompatible version of the mode is installed, you cannot even start Processing, unless you delete the mode files manually.

**Comment by kasperkamperman** [comment]
@codeanticode I prefer the SDK installation warning or no message at all. It won't be nice if whole Processing (including all the other modes) will be blocked if just the Android mode doesn't work.

**Comment by omerjerk** [comment]
I was looking at the logic and as far as I think, the "Locate SDK" dialogue should always come up instead of the "bad day" one. https://github.com/processing/processing-android/blob/master/src/processing/mode/android/AndroidMode.java#L140
The possible reason could be that `parent` in the above mentioned code is null.

Unfortunately, I'm not able to build Processing from eclipse and unable to see the console output.
Let me fix my eclipse build first.

**Comment by codeanticode** [comment]
fixed after merging Umair's PR. Tested on Mac OS X 10.10 and Processing 3.0

**Comment by codeanticode** [comment]
@omerjerk actually, there are some instances where the "bad day" message still show up after the fix. For example, quit the PDE when using the Android mode, delete the SDK inside the mode folder, and run the PDE. Then the install SDK dialog shows up, but on top of it the "bad day" popup, which you need to dismiss twice to get to install the SDK again. 

I also noticed that if you close the install dialog SDK using the close button, without selecting any option, then it still downloads the SDK.

So, we need to tweak the UI logic a bit more.

**Comment by codeanticode** [comment]
This is fixed in [RC3](https://github.com/processing/processing-android/releases/tag/latest).

**Comment by codeanticode** [comment]
no confirmation from original posters, and the download logic is fixed in PR3. There are still some issues, but addressed [here](https://github.com/processing/processing-android/issues/202) and [here](https://github.com/processing/processing-android/issues/209).
