### ISSUE TITLE
sketch does not run, gives INSTALL_PARSE_FAILED_MANIFEST_MALFORMED error

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#157]
Ported from https://github.com/processing/processing/issues/3995

**Comment by toniholzer** [comment]
Think this issue can be closed now. It's working fine with processing v3.0.1.  (Android 3.0 beta 4)
There are no more error messages and permissions are set as expected.
Thank you...
ps. 'Android.xml' file would be much more readable if you add some linefeeds for separate text lines!!!
