### ISSUE TITLE
API clarification.

### ISSUE THREAD

**Issue by hudsonm4000** [processing/processing-android#159]
Wiki states that min API for 3.0 is 11and on the forum, some users are saying it's 17, but benfry has stated here on github that it is now 15. Which is correct?

**Comment by hudsonm4000** [comment]
... and is it a new 'must be installed' requirement as was the case for API 10 with 2.x?

**Comment by omerjerk** [comment]
With the latest Android mode, the minimum API level required is API 15.
Please point me to the forums where people mentioned API 17 being minimum.
There could have been some other problem with the Android mode.

**Comment by hudsonm4000** [comment]
Here:
#http://forum.processing.org/two/discussion/12665/android-sdk-could-not-be-loaded#latest

and here(more by implication though)
http://forum.processing.org/two/discussion/13009/could-not-create-a-virtual-device-for-the-emulator#latest

I think we all just need someone who knows to tell us what is right!. My guess is "15" as that is from benfry here on github... and that is what I am using.. although the wiki saying "11" seems odd?

**Comment by hudsonm4000** [comment]
@omerjerk ... just re-read your post... it is 15.

Perhaps this info could be added to the warning pop up that appears when the sdk is missing/not found, and/or  installing the android mode from within the Processing CM?

**Comment by codeanticode** [comment]
The SDK installation dialog now indicates to install API 15 or higher: https://github.com/processing/processing-android/commit/11f068566c88a0680b2c231dd43ab9f9a7b86f92
