### ISSUE TITLE
How can I add Application class ?

### ISSUE THREAD

**Issue by amirc2013** [processing/processing-android#169]
I want to make an Application (extend android's application) and add this to my project.
the question is how can i add an "outsider" java file ?
and how can i import this outsider ?
thank you

**Comment by omerjerk** [comment]
I'm afraid you cannot do this right from PDE.
You'll need to use Android Studio and use core.jar form Processing.
Useful link - https://github.com/processing/processing-android/wiki/Using-Eclipse-or-Android-Studio-for-Development

**Comment by shlomihod** [comment]
I think you can create *code* folder in your sketch folder and then add your external jar files.
