### ISSUE TITLE
separate "PApplet" into separate View and Activity classes on Android

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#17]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Sunday May 12, 2013 at 22:09 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/18_

----

Earlier report: http://code.google.com/p/processing/issues/detail?id=212

**Comment by codeanticode** [comment]
No longer valid with transition to Fragments API.
