### ISSUE TITLE
Error checker says that getActivity() function does not exist

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#171]
@omerjerk @Manindra29 this is still happening with the latest revision of Processing and the mode. Do you guys think there is a simple solution?

**Comment by Manindra29** [comment]
The sdk was not being initialised when getSearchPath() is called. So maybe that was causing the bug? When you start up Android Mode for the first time, a NPE occurs in getSearchPath() (stack trace visible in std.err). 

I can test the fix further if you can share a piece of sample code to reproduce this error. 

Please take a look at my PR too.

**Comment by codeanticode** [comment]
Hi Manindra, thanks for the PR. I will check if it fixes the issue.

**Comment by codeanticode** [comment]
No, the getActivity() method is still marked as not recognized after applying your PR:

![image](https://cloud.githubusercontent.com/assets/62246/10866855/adf188ce-801a-11e5-8af2-f4a2d6631f78.png)

**Comment by Manindra29** [comment]
I looked at this again, and it reveals a much bigger issue. So ErrorCheckerService (ECS) was designed originally for just JavaMode. Java sketches are wrapped with:
class <name> extend PApplet {
... user code...

..main method..
}

For Android Mode, this is done completely differently. The parent class needs to extend Activity class to have getActivity() available. I saw some of this template code in [AndroidBuild.java](https://github.com/processing/processing-android/blob/master/src/processing/mode/android/AndroidBuild.java#L881).

Right now, ECS is only designed to handle JavaMode. Moreover, ECS is designed to only handle single .java source files. Afaik, Android apps usually require multiple class files, not sure if it's the same for AndroidMode. Making ECS fully compatible with Android Mode will probably require some major modifications (non-trivial). So this will probably require a larger effort than a single PR.

**Comment by omerjerk** [comment]
@Manindra29 
`getActivity()` method is available in `Fragment` class which is what our sketch class extends.

**Comment by Manindra29** [comment]
I see. Can you share what the generated source files look like for a basic android sketch after they've been converted to .java files for an android sketch so that I can get the complete picture?

**Comment by codeanticode** [comment]
This is what I get when I export the sketch above as Android project:

* MainActivity.java
```java
package processing.test.getactivity_171;
import android.app.Activity;
import android.os.Bundle;
import android.view.Window;
import android.view.WindowManager;
import android.widget.FrameLayout;
import android.view.ViewGroup.LayoutParams;
import  android.app.FragmentTransaction;
import processing.core.PApplet;
public class MainActivity extends Activity {
    PApplet fragment;
    private static final String MAIN_FRAGMENT_TAG = "main_fragment";
    int viewId = 0x1000;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Window window = getWindow();
        requestWindowFeature(Window.FEATURE_NO_TITLE);
window.setFlags(WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
window.setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
        FrameLayout frame = new FrameLayout(this);
        frame.setId(viewId);
        setContentView(frame, new LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT));
        if (savedInstanceState == null) {
            fragment = new getactivity_171();
            FragmentTransaction ft = getFragmentManager().beginTransaction();
            ft.add(frame.getId(), fragment, MAIN_FRAGMENT_TAG).commit();
        } else {
            fragment = (PApplet) getFragmentManager().findFragmentByTag(MAIN_FRAGMENT_TAG);
        }
    }
    @Override
    public void onBackPressed() {
        fragment.onBackPressed();
        super.onBackPressed();
    }
}
```

* getactivity_171.java
```java
package processing.test.getactivity_171;

import processing.core.*; 
import processing.data.*; 
import processing.event.*; 
import processing.opengl.*; 

import android.app.Activity; 

import java.util.HashMap; 
import java.util.ArrayList; 
import java.io.File; 
import java.io.BufferedReader; 
import java.io.PrintWriter; 
import java.io.InputStream; 
import java.io.OutputStream; 
import java.io.IOException; 

public class getactivity_171 extends PApplet {

public void setup() {  
  Activity a = getActivity();  
}

public void draw() {

}
  public void settings() {  size(100, 100); }
  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "getactivity_171" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
```

**Comment by omerjerk** [comment]
@Manindra29 
In the above code, `PApplet` extends `Fragment`.

**Comment by omerjerk** [comment]
I'm wondering, even back when our sketch class used to extend `Activity` class, we never got warnings related to the `Activity` specific methods. Did we ?
If not, why is this happening only now ?

**Comment by codeanticode** [comment]
I cannot recall, as many changes happened in the syntax checker between we switched from Activity over to Fragment. I'm not even sure if the syntax checker was actually working at all before the Fragment switch.

In any case, the issue is happening, so we need to fix it :-)

**Comment by omerjerk** [comment]
Going to fix this issue once and for all now.
Working on it.

**Comment by omerjerk** [comment]
@Manindra29 
Whenever I type the following code, I don't get the `getActivity()` related error.
```
Fragment d = new Fragment();
d.getActivity();
```
But when `getActivity()` is put inside the setup method, the error appears. Note that `PApplet` itself extends `Fragment` class.
```
void setup() {
    getActivity();
}
```

**Comment by omerjerk** [comment]
Wait, I think I've figured out the issue. :P

**Comment by omerjerk** [comment]
@benfry
The error, as far as I think, is that the PDE loads the java one core.jar and not the android one. That's why only methods specific to Android mode's PApplet get underlined.
So, I looked into ErrorCheckerService.java and did extensive debugging but couldn't find a place where the core.jar is explicitly being added to the compiler classpath.
Probably, it is inheriting core.jar from Java mode's classpath (not sure though).
At this point, one way is that we remove Java mode's dependency on the core.jar, but this will require a bulk of changes and testing. Other than this, I'm out of ideas.

**Comment by Manindra29** [comment]
Both P5 core's PApplet and android core's PApplet have the same class names: processing.core.PApplet.
Since P5's PApplet is present in P5's classpath, that's the class detected by the ErrorChecker compiler (since it appears first in the classpath). But we want it to find the second PApplet class (android core.jar's PApplet) in the classpath. Not sure how we can accomplish that..

**Comment by omerjerk** [comment]
So, as suggested, I wrote a custom class loader and printed the classes which JDT compiler loads using the class loader. Here's the output :
```
loading class = java.class
couldn't find the class
loading class = java/lang.class
couldn't find the class
loading class = processing.class
couldn't find the class
loading class = processing/core.class
couldn't find the class
loading class = processing/data.class
couldn't find the class
loading class = processing/event.class
couldn't find the class
loading class = processing/opengl.class
couldn't find the class
loading class = PApplet.class
couldn't find the class
loading class = android.class
couldn't find the class
loading class = android/app.class
couldn't find the class
loading class = android/app/Fragment.class
CLASS LOADED
```
Another problem is that even if I don't load the `processing.core` classes inside my class loader, PDE still works perfectly fine with PApplet functions.

**Comment by codeanticode** [comment]
Where is the code of your custom class loader?

Did you try using overriding the default parent loader with this [other constructor](https://docs.oracle.com/javase/7/docs/api/java/net/URLClassLoader.html#URLClassLoader(java.net.URL[],%20java.lang.ClassLoader)) of URLClassLoader?

**Comment by omerjerk** [comment]
This is the ClassLoader which I used :
```
  public static class CustomLoader extends ClassLoader{
	  
	public CustomLoader() {
	  super(CustomLoader.class.getClassLoader()); //calls the parent class loader's constructor
	}
	
	@Override
	public Class<?> loadClass(String className) throws ClassNotFoundException {
      return findClass(className);
    }
	
	public Class<?> findClass(String className) {
        byte classByte[];
        Class<?> result = null;

        try {
            JarFile coreJar = new JarFile("/home/omerjerk/sketchbook/modes/AndroidMode/android-core.zip");
            JarFile androidJar = new JarFile("/home/omerjerk/sdk/platforms/android-22/android.jar");
            className = className.replace('.', File.separatorChar) + ".class";
            JarEntry entry = coreJar.getJarEntry(className);
            System.out.println("loading class = " + className);
            InputStream is;
            if (entry == null) {
            	entry = androidJar.getJarEntry(className);
            	if (entry == null) {
            		System.out.println("couldn't find the class");
            		return null;
            	}
            	is = androidJar.getInputStream(entry);
            }
            System.out.println("CLASS LOADED");
            is = coreJar.getInputStream(entry);
            ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
            int nextValue = is.read();
            while (-1 != nextValue) {
                byteStream.write(nextValue);
                nextValue = is.read();
            }

            classByte = byteStream.toByteArray();
            result = defineClass(className, classByte, 0, classByte.length, null);
            return result;
        } catch (Exception e) {
            return null;
        }
    }
  }
```
The code looks hacky but it is supposed to work.
