### ISSUE TITLE
Can't find android SDK message after installation

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#172]
Ported from https://github.com/processing/processing/issues/4063

**Comment by codeanticode** [comment]
@kinjo27

Do you see this message dialog after installing the android mode:

https://github.com/processing/processing-android/issues/156#issuecomment-147414413

If you do, all you have to do is to choose the "Locate SDK path manually" option and look for the folder containing your copy of the SDK.

If you don't see it, don't worry. The installation logic in the latest version of the mode is somewhat broken, so you might need to quit Processing, re-open it and switch to the android mode, then you should get the SDK selection dialog. 

Next release of the mode will address this issue, so I'm marking it as a duplicate of #156.

**Comment by kingjo47** [comment]
Thanks! it works.

**Comment by codeanticode** [comment]
cool!
