### ISSUE TITLE
Mode out of Date issue after downloading latest version

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#173]
Ported from https://github.com/processing/processing/issues/4075

**Comment by codeanticode** [comment]
@HeroLabsAndroid please note that the last version of the mode that works with Processing 2.2.1 is not compatible with Processing 3.x. You should use the latest release, which you can install through the Contribution Manager.

**Comment by HeroLabsAndroid** [comment]
No the problem is i don't even use android mode
Am 28.10.2015 13:31 schrieb "codeanticode" <notifications@github.com>:

**Comment by codeanticode** [comment]
you should be able to remove it also using the Contribution Manager in 3.x. Or manually in 2.x (go to your sketchbook folder, and then delete modes/AndroidMode).
