### ISSUE TITLE
Sensor examples are broken

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#175]
Accelerometer and Compass were not updated to reflect the Fragment changes in the API

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/fdf4955e3349f8967ecd6da87efe9fa22745168d

**Comment by darkwave** [comment]
Accelerometer example broken again (missing `getSurface()` method to access _activity_):

``` processing
 public AccelerometerManager(PApplet parent) {
    this.parent = parent;
    this.context = parent.getActivity();

...
```

**Comment by gunkiratk** [comment]
Hey,
Want to work on this issue
