### ISSUE TITLE
Please eliminate unnecessary Android mode import warnings!

### ISSUE THREAD

**Issue by toniholzer** [processing/processing-android#178]
Warnings and errors are displayed with red lighted text color.
If there are not only warnings, error messages must be picked out cumbersome. 
So is it possible to eliminate unnecessary 11 warning that came every time when testing an android app?  Pleeeease ;-)

**Comment by codeanticode** [comment]
Thanks for the report. I filed this issue with further details [here](https://github.com/processing/processing-android/issues/185). Closing this one as a duplicate.
