### ISSUE TITLE
Can't find connected device, can't run in emulator

### ISSUE THREAD

**Issue by dorinclisu** [processing/processing-android#179]
When loading Android mode I get this:

<pre>
Exception in thread "Thread-45" java.lang.NullPointerException
    at processing.mode.android.AndroidBuild.setSdkTarget(AndroidBuild.java:76)
    at processing.mode.android.AndroidEditor.updateSdkMenu(AndroidEditor.java:347)
    at processing.mode.android.AndroidEditor.access$300(AndroidEditor.java:50)
    at processing.mode.android.AndroidEditor$7.run(AndroidEditor.java:249)
</pre>

No android functionality is available.
Using processing 3.0.1 with Android Mode 3.0-beta4.

**Comment by omerjerk** [comment]
I was looking at the code and could not figure out when this exception should occur at all.
Are you doing something special to reproduce this ?
Can you please tell which Android SDKs are available on your machine right now ?

**Comment by dorinclisu** [comment]
How do I figure that out exactly? I just downloaded the SDK manager and then installed the packages that are supposed to be installed.

**Comment by codeanticode** [comment]
@omerjerk Just merged you PR https://github.com/processing/processing-android/pull/180 that should fix this, will push a new release soon.

**Comment by omerjerk** [comment]
@dorinclisu 
As far as the normal behavior of Processing is concerned, it should pop up a dialog box asking you to automatically download the Android SDK. I'm assuming that that somehow didn't happen with you and probably that's why you were facing this crash (still pretty strange). 
I think in your PC, Android sdk is present but corrupted or something else the pop up would have showed up.

I'd suggest you to open the Android SDK manager and manually install any Android SDK newer than Gingerbread ( KitKat probably).

**Comment by dorinclisu** [comment]
It did pop up a dialog box in the beginning and I gave it the path to the Android SDK that I previously downloaded. I manually installed the packages with the SDK manager.
But I find this pretty confusing and I think the root of many problems is that there is more than one way to install all this stuff.  For example I have no such file as AndroidEditor.java on my computer.

**Comment by omerjerk** [comment]
The last error you mentioned comes when there is not SDK installed. We keep 15 as the default value, so it's trying to look for api 15.
So, are you sure you correctly downloaded the SDK ? Can you send a screenshot of your sdk manager focusing the sdk you downloaded ?

From where did this AndroidEditor.java come in to play ? :o

**Comment by dorinclisu** [comment]
Well, I only had API 10 installed because that is what the instructions say  <url>https://github.com/processing/processing-android/wiki#Instructions</url>. I installed API 15 and the errors are gone, however it still says "No connected devices" and when trying to run in emulator it gives:
<pre>debug:
Emulator process exited with status 1.
EmulatorController: Emulator never booted. NOT_RUNNING
Error while starting the emulator. (NOT_RUNNING)
Shutting down any existing adb server...
</pre>

**Comment by sgsh123** [comment]
Is this issue related to Processing in any way or is it merely a single developer's specific problem?

**Comment by codeanticode** [comment]
Haven't heard any other user reporting this issue, and devices are detected in latest versions of the mode.
