### ISSUE TITLE
implement selector to choose the default device for debugging

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#18]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Sunday May 12, 2013 at 22:11 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/19_

----

currently, if multiple devices are plugged in, the first one found is used.

http://code.google.com/p/processing/issues/detail?id=207
http://processing.org/bugs/bugzilla/1389.html

**Comment by codeanticode** [comment]
Implemented by @imilka in GSOC 14
