### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by dodola** [processing/processing-android#182]
some code render ,frame count too low

**Comment by codeanticode** [comment]
What is the code that gives you low framecount? Lots of factors could be affecting the performance of your sketch.

**Comment by dodola** [comment]
@codeanticode example code /Demos/Performance/CubicGridImmediate 。 The Java Version run on mac the fps is 11,on Android  Device(MI 3) the fps is 5

**Comment by ajavamind** [comment]
FYI, My Window 7 pro Intel i7 runs the CubicGridImmediate java code averaging 19 fps, Sony Z1s .66 fps, and Samsung S6,  range from 19 to 29 fps - slowing down the longer it runs.

**Comment by codeanticode** [comment]
Hi there, the CubicGridImmediate example is inherently slow, even on desktop, and its main purpose is to demonstrate the advantages of using retained mode (i.e.: PShape) when rendering large geometries. How many fps do you get with /Demos/Performance/CubicGridRetained?

**Comment by ajavamind** [comment]
You piqued my interest. For CubicGridRetained
Windows 7 pro Intel i7 3.5 GHz: 35 fps average
Sony Z1S          59 fps average
Samsung S6     60 fps solid no variance
60 fps is the frame per second setting for the test, so I changed it to 120 with frameRate(120),
but the debug output still shows a solid 60 fps, implying frameRate() has no effect?

**Comment by ajavamind** [comment]
Forgot to mention I am using Processing-Android mode 3.0-beta4 for the CubicGridRetained test

**Comment by dodola** [comment]
@codeanticode  CubicGridRetained on my phone  fps: 60.0 ,I think I know the reason ,thanks

**Comment by dodola** [comment]
@ajavamind we call the frameRate method only control the draw sleep time, the real framerate is calculate by draw method

```java
  public void frameRate(float newRateTarget) {
        frameRateTarget = newRateTarget;
        frameRatePeriod = (long) (1000000000.0 / frameRateTarget);
        g.setFrameRate(newRateTarget);
    }

//...
   public void run() { 
//...
 long afterTime = System.nanoTime();
            long timeDiff = afterTime - beforeTime;
            long sleepTime = (frameRatePeriod - timeDiff) - overSleepTime;

            if (sleepTime > 0) { // some time left in this cycle
                try {
                    Thread.sleep(sleepTime / 1000000L, (int) (sleepTime % 1000000L));
                    noDelays = 0; // Got some sleep, not delaying anymore
                } catch (InterruptedException ex) {
                }
//...
}
//...
    public void handleDraw() {
//...
       double rate = 1000000.0 / ((now - frameRateLastNanos) / 1000000.0);
                float instantaneousRate = (float) rate / 1000.0f;
                frameRate = (frameRate * 0.9f) + (instantaneousRate * 0.1f);
//...
            frameRateLastNanos = now;
}

```

**Comment by codeanticode** [comment]
Does performance continue to be a problem? Is it ok to close this issue?

**Comment by dodola** [comment]
@codeanticode ok
