### ISSUE TITLE
Cannot load txt file with the library's Jar file

### ISSUE THREAD

**Issue by CyrusSUEN** [processing/processing-android#188]
I've created a simple [Processing library example](https://github.com/CyrusSUEN/processing-library-template/blob/master/src/template/library/HelloLibrary.java#L60-L61) that can load and display the content of a text file.

This is the structure of the Jar file:
![capture1](https://cloud.githubusercontent.com/assets/2461812/12817673/3ee8fbf0-cb8e-11e5-9e30-32a1f1c04d5b.PNG)

Result on Windows:
![capture2](https://cloud.githubusercontent.com/assets/2461812/12817674/41780c4e-cb8e-11e5-9111-861c7e5e8e01.PNG)

But on Android Processing I got the following error:
![screenshot_2016-02-04-22-11-40](https://cloud.githubusercontent.com/assets/2461812/12817693/5aeb57c6-cb8e-11e5-887f-9de7bfa5e2fc.png)

Is there something special on Android platform that I should be aware of? Thanks for your help!

**Comment by omerjerk** [comment]
Why are you using that app ? We don't maintain that app.
You should rather use the Android mode of processing.

Also, don't forget to add the read permissions to your app.

**Comment by CyrusSUEN** [comment]
> use the Android mode of processing.

Thanks! That works.
