### ISSUE TITLE
implement means for selecting the AVD

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#19]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Sunday May 12, 2013 at 22:12 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/20_

----

Earlier report: http://code.google.com/p/processing/issues/detail?id=208

**Comment by codeanticode** [comment]
AVD automatically selected based on the SDK https://github.com/processing/processing-android/pull/127
