### ISSUE TITLE
textFont() wipes out alpha

### ISSUE THREAD

**Issue by ZachSundberg** [processing/processing-android#196]
Processing 3.01
Any call to textFont() causes all curent and future objects to lose their alpha.

**Comment by erkosone** [comment]
I have the same problem.
In Android mode can´t use text() with PFont correctly, the alpha channel of any image are corrupted.

**Comment by codeanticode** [comment]
@ZachSundberg what renderer are you using?

**Comment by ZachSundberg** [comment]
P2D & P3D produces the error.  JAVA2D does not.

**Comment by codeanticode** [comment]
this code generates the same (correct) output with JAVA2D and P2D/P3D:

```java
int x = 30;
void setup() {
  size(200, 200, P2D);
  background(102); 
  fontA = createFont("Arial", 32);
  textFont(fontA, 32);
}

void draw() {
  fill(0, 100);
  text("ichi", x, 60);
  fill(51, 120);
  text("ni", x, 95);
  fill(204, 90);
  text("san", x, 130);
  fill(255, 0);
  text("shi", x, 165);
  
  fill(255, 0, 0, 40);
  noStroke();
  rect(0, 0, width, height);
}
```

Does it work for you? Can you post some code that highlights the issue?

**Comment by ZachSundberg** [comment]
Your code works fine.  The problem seems to arise when after using loadFont with a font created using the create font tool.  This code demonstrates how the error occurs only after a call to textFont.

`int delay = 5000;
PFont fontA;

void setup()
{
  orientation(PORTRAIT);
  size(displayWidth, displayHeight, P2D);
  fontA = loadFont("ArialMT-48.vlw"); //replace with any font created using create font tool
  fill(color(0,0,0,255));
  textSize(48);
}

void draw()
{
  background(255,255,255);
  if(millis()>delay)
  {
    textFont(fontA, 48);
  }
  text("Watch the circles",80,80,displayWidth,100);
  pushStyle();
  fill(color(255,0,0,50));
  ellipse(displayWidth*0.48,displayHeight*0.5,displayWidth*0.2,displayWidth*0.2);
  fill(color(0,0,255,50));
  ellipse(displayWidth*0.53,displayHeight*0.5,displayWidth*0.2,displayWidth*0.2);
  popStyle();
}`

**Comment by codeanticode** [comment]
I can reproduce it now using your code. Looking into it, thanks!

**Comment by erkosone** [comment]
any way to download version with this correction?
Thanks in advance.

**Comment by codeanticode** [comment]
Try the [latest release](https://github.com/processing/processing-android/releases/tag/latest), RC1, and let me know if you still see this problem, or any other issues (please report separately). Thanks!

**Comment by erkosone** [comment]
This release works perfectly!!!! I LOVE YOU!!

**Comment by ZachSundberg** [comment]
RC1 Fix confirmed on my end. 
Thanks for all your hard work.

**Comment by codeanticode** [comment]
Glad to know that the problem is solved. Thanks for testing!
