### ISSUE TITLE
Not compatible with Android 23

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#205]
Tested automatically downloading Android SDK 23, but sketched give an error when running the build script that comes with the platform (android-23 not found).

**Comment by omerjerk** [comment]
Hey @codeanticode,
Are you working on this ?
I can look into it.

**Comment by codeanticode** [comment]
That would be great. Use the latest revision, and change [PLATFORM_API_LEVEL](https://github.com/processing/processing-android/blob/master/src/processing/mode/android/SDKDownloader.java#L35), and install the SDK automatically from the PDE. Once installed, try running a sketch on the device.

**Comment by codeanticode** [comment]
@omerjerk were you able to test it?

**Comment by omerjerk** [comment]
I'm sorry. I missed your last reply.
I'll test it right away.

**Comment by omerjerk** [comment]
@codeanticode 
I tested it and it worked totally fine.
Although one thing I noticed was that dialog doesn't come even when the platforms folder is empty. I can send a pull request to take care of this case.

**Comment by codeanticode** [comment]
I'm still getting the error. What platform are you on? Linux? I'm on OS X, so I wonder if that has something to do with it.

The SDK that gets installed is N (23), which shows up like this in the SDK selection menu:

![image](https://cloud.githubusercontent.com/assets/62246/14683365/5d17232c-06f8-11e6-94e9-84f6417de4fc.png)

Any sketch that I try to run on the device fails with this error in the console:

```
-build-setup:
Using latest Build Tools: 24.0.0 rc3
     [echo] Resolving Build Target for MoveEye...

BUILD FAILED
/Users/andres/code/processing/git/processing-android/sdk/tools/ant/build.xml:538: Unable to resolve project target 'android-23'

Total time: 2 seconds
```

**Comment by omerjerk** [comment]
I'm on Ubuntu, but I don't think this issue is specific to OS.
I'll check again why it happens.

**Comment by codeanticode** [comment]
Don't know why you didn't see this happening on Linux, but I found the problem: platform preview N has the same API level, 23, las the latest "stable" platform, 6.0, as you can see in the [repository xml](https://dl-ssl.google.com/android/repository/repository-11.xml). So selecting platform only by level was downloading N, but Processing tried to use 23 (6.0), and this lead to the problem. [This commit](https://github.com/processing/processing-android/commit/18688719daafde8a98b4d4ccf30d5204dcaf2b91) (where platform is selected by matching api level and version) fixes the issue:
