### ISSUE TITLE
NullPointerException when calling PImage.resize()

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#21]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Tuesday May 14, 2013 at 00:14 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/22_

---

Original report: http://code.google.com/p/processing/issues/detail?id=1499

**Comment by barefists** [comment]
Leaving a note here, hoping this issue will be fixed soon. :)

**Comment by PandaBalls** [comment]
same issue for me.. can't resize() for non-fileloaded PImage.

**Comment by codeanticode** [comment]
I cannot reproduce the crash, but the resized image is black.

**Comment by codeanticode** [comment]
Duplicate of #251
