### ISSUE TITLE
blank white screen on android 6.0

### ISSUE THREAD

**Issue by jango-fx** [processing/processing-android#211]
i'm trying to get a simple test sketch to run on Marshmallow. But all i get is a blank white screen. The same goes for any other example sketch.

i'm on
- OS X 10.11.4
- javac 1.8.0_92
- Android 6.0
- Motorola XT1068
- Processing 3.0.2
- Android SDK: API 6.0 (23)

i don't get any errors. except for those warnings. and i don't seem to get any feedback from `println();` either.

> The import processing.data is never used
> The import processing.event is never used
> The import processing.opengl is never used
> The import java.util.HashMap is never used
> The import java.util.ArrayList is never used
> The import java.io.File is never used
> The import java.io.BufferedReader is never used
> The import java.io.PrintWriter is never used
> The import java.io.InputStream is never used
> The import java.io.OutputStream is never used
> The import java.io.IOException is never used

my code is really just a super basic test sketch:

```
void setup()
{
  background(0, 0, 255);
  rectMode(CENTER);
}

void draw()
{
  background(0, 255, 0);
  fill(255, 0, 0);
  rect(width/2, height/2, 50, 50, 50);
  println("i'm alive");
}
```

i'm out of ideas...

**Comment by ZachSundberg** [comment]
Having the same issue since the latest update.  Looks like draw() is not being called.

**Comment by codeanticode** [comment]
Thanks for the info, will look into it.

**Comment by sesmusician** [comment]
Yes, same problem using API 21, 22 ,and i also used API 15 just in case.

**Comment by joshgiesbrecht** [comment]
I just had this problem, and it's """fixed""" by calling size() in your setup function. (Discovered this by accident while trying example code)

**Comment by joshgiesbrecht** [comment]
("""fixed"""" because this results in a non-fullscreen sketch window centered on the device; obviously not optimal but at least you can do stuff with it)

**Comment by jango-fx** [comment]
well, good enough for me at the moment. if it's called in settings(), it works fullscreen, too.
```
void settings()
{
    size(displayWidth, displayHeight);
}
```

**Comment by codeanticode** [comment]
Thanks for bringing this up. There was an actual bug: on the desktop, Processing sets a default width/height of 100x100, however this was not being done in the android mode. Now it is.
