### ISSUE TITLE
Processing IDE freezes, when switching to Android Mode

### ISSUE THREAD

**Issue by jango-fx** [processing/processing-android#212]
arr! trying to update android mode somehow just messed everything up for me...
when i try to switch to android mode, the GUI seems to restart, then just freezes.

i tried downgrading from "Processing/modes/old", now i can successfully start android mode but i get weird warnings like "PApplet does not exist" or "background(int) does not exist" and the app crashes on start on the device...

deleting androidmode-folder and reinstalling it from the library manager doesn't help...

**Comment by jango-fx** [comment]
ok, seems uninstalling and reinstalling sdk helped.
but now i got this problem again: #211

**Comment by jango-fx** [comment]
downgrading **that** one i could fix by downgrading to a previous version from "Processing/modes/old"..

**Comment by codeanticode** [comment]
This is probably a duplicate of https://github.com/processing/processing-android/issues/209

**Comment by codeanticode** [comment]
@jango-fx A temporary workaround for this issue is to disable the "Suggest import statements" option in the Preferences.

**Comment by codeanticode** [comment]
Using Processing 3.1 solves this issue.
