### ISSUE TITLE
Debug console in "Processing Sketch", doesn't receive response of app

### ISSUE THREAD

**Issue by imartini** [processing/processing-android#216]
Hi!!

Some time ago, I was worked in a VR/AR aplication. This works perfectly in Android 5.1.1, Processing 3.0.1 and the processing-android mode. The problem begins when I upgrade to Processing 3.1, the last processing-android mode and Android 6.0.1 on my smartphone. I can install the app, but de debug console doesn't recieve any response from the errors or code (println() or similars) from the smartphone. The last text I see in the console is "debug:" and nothing else down of this line.
I tried to install the latest usb drivers, searching new options in the 6.0.1 Android for debugging, change permisions int the AndroidManifest.xml  but nothing works...

Thanks and sorry for my bad english!

**Comment by sesmusician** [comment]
Does the app run in your device?

**Comment by imartini** [comment]
Yes, the app run perfectly. Doesn't return any error.

**Comment by codeanticode** [comment]
@JakubValtar any chance this could this be due to a recent change in the JavaMode?

**Comment by JakubValtar** [comment]
@codeanticode Probably not. There was some change in out and err stream encoding though, try to look there.

**Comment by imartini** [comment]
I tried with a Processing 3.0.2 and old versión of android-mode, and the problem persist. I think that the problem is in the android 6.0.1 and processing-mode can't interpret the response of the smartphone. Another possibility is the incorrect installation of the android in my smartphone, but it's a clear installation.

**Comment by codeanticode** [comment]
Ok, it is likely then that something changed in Android 6.0.1 that broke the debug output. Will look into it.

**Comment by rich-gg** [comment]
Hi imartini
Might be out of context but I am interested in making AR app for Android using Processing.
is ke:tai the trick ?

Would you be so kind as to exchange on the topic with me ?

cheers

**Comment by codeanticode** [comment]
@imartini What was the last version of Processing, Android mode, and SDK where you were able to get the debug output in the console?

I tried Processing 3.0.2 with the RC4 release of the mode and SDK 4.0.4 (15), and don't get any output, so this might have been going on for a while, I just didn't notice until now.

**Comment by imartini** [comment]
Android SO 5.1.1 SDK 22, Processing 3.0.1 and Android Mode 3.0-beta4. 
The other possibility that was broken the debug output, it's the Windows 10 actualizations? Capping the usb or something.

**Comment by CaffeineOverdrive** [comment]
I'm running Processing for Android on a couple if rigs under various configurations and have only found the debug console problem using phones on Android 6.01.
Windows version, Android Mode version, Processing version don't consistently seem to affect the issue.
It looks like Android 6.01 has changed something in the debug output and Processing's console can't echo them.
As a workaround I can still view the debug messages in Android Studio's logcat using filters for TAG: system.out or Application: Processing.test.*. I suppose the same would be possible in a ADB terminal window?

**Comment by codeanticode** [comment]
Yes, you should be able to run adb logcat and see the debug messages. I will look into it soon, I filed the issue under the 3.0.1 bugfix release, which will happen shortly after I push the 3.0 final.
