### ISSUE TITLE
PApplet fragments remain in memory even after parent activity has been destroyed

### ISSUE THREAD

**Issue by jsalerno** [processing/processing-android#217]
A fix in https://github.com/processing/processing-android/issues/213 solved the issue of Activity refs being retained by PApplet fragments. That solves a major part of memory loss/leakage. Those activity's PApplet fragments, however, are themselves retained in memory even after the Activity instances are gone from the Heap.

Here is a sample reference tree of such a fragment ref still on the heap:

<pre>
mypkg.MyTroublesomeProcessingFragment@317856864 (0x12f21c60)
    java.lang.Thread@318656032 (0x12fe4e20)
    processing.opengl.PGraphics3D@343302144 (0x14766000)
    processing.core.PApplet$SketchSurfaceViewGL@316919808 (0x12e3d000)
    processing.core.PApplet$InternalEventQueue@345443392 (0x14970c40)
    mypkg.MyTroublesomeProcessingFragment$CurrentTrace@314993488 (0x12c66b50)
    processing.opengl.PGLES@314815264 (0x12c3b320)
    processing.opengl.PShader@315869120 (0x12d3c7c0)
    processing.opengl.PShader@315868880 (0x12d3c6d0)
    processing.opengl.PShader@315867920 (0x12d3c310)
    processing.core.PImage@314746992 (0x12c2a870)
    java.lang.Object[12]@346065984 (0x14a08c40)
</pre>

mypkg.MyTroublesomeProcessingFragment extends PApplet.

It looks like the PImage is still in memory and through the object tree the reference is retained.

**Comment by codeanticode** [comment]
All fragments should be automatically disposed when the activity that created them is destroyed, and this won't happen if the app was only [paused or stopped](https://developer.android.com/reference/android/app/Activity.html#ActivityLifecycle). I made some minor changes (https://github.com/processing/processing-android/commit/668bb06ace228c7dd7731624f4288d5d6395d198) to make sure that not references to the main activity are left inside the renderer, this might help.

**Comment by codeanticode** [comment]
Also, [this thread](http://stackoverflow.com/questions/6330200/how-to-quit-android-application-programmatically) mentions the use of Activity.finish() and Activity.finishAffinity(), which sounds like the right way to terminate the app and all associated components. I'm use finishAffinity() in exit2(), and see what happens.

**Comment by codeanticode** [comment]
@jsalerno Bugfix release 3.0.1 is available in the CM, do you still see this problem?

**Comment by codeanticode** [comment]
I replaced the System.exit() call with activity.finish() in https://github.com/processing/processing-android/commit/8eaccf15961745a0111b861528122c9417458d97, and didn't see any memory issues so far. Closing this issue, feel free to reopen it if you still find memory leakage.
