### ISSUE TITLE
Move cardboard packages to Cardboard library

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#223]
The cardboard_core.zip, cardboard_common.zip, and cardboard_audio.zip packages should be bundled with the Cardboard library, and copied when building the sketch in Cardboard mode.

**Comment by thijsvb** [comment]
Maybe this is creating an error when trying to export a sketch using eclipse? 

I exported a cardboard sketch as android project and opened it in eclipse to sign and export, but it gave me this error:

```
The type com.google.vrtoolkit.cardboard.CardboardActivity cannot be resolved. It is indirectly referenced from required .class files	
```

Seems to me it can have something to do with this, but I might be wrong.

**Comment by codeanticode** [comment]
You need to import the cardboard packages manually into your Eclipse project (Processing does it automatically when you run the sketch). Otherwise it won't be able to resolve the dependencies on CardboardActivity and other required classes. 

Note that you can export your sketch as a signed package directly from the PDE, last time I tried from using Eclipse to develop Carboard apps I run into trouble as the Android plugins for Eclipse are no longer maintained. The export Android project in the PDE should export a gradle project for Android Studio instead, but haven't had the time to work on that yet :-)

**Comment by codeanticode** [comment]
fixed with https://github.com/processing/processing-android/commit/7bac0a276c19116511f92ce088f23eafa82955df
