### ISSUE TITLE
Wiki links to `http://android.processing.org/`, which links directly back to wiki.

### ISSUE THREAD

**Issue by mitchmindtree** [processing/processing-android#230]
The wiki recommends to use [the official site](http://android.processing.org/)

> For detailed information (installation guide, tutorials, etc.), on how to use the Android mode to write your own sketches, please refer to [the official site](http://android.processing.org/).

 which itself seems to be an empty page that links back to the wiki.

**Comment by REAS** [comment]
This might be a temporary error while we're in transition. We're launching a new Android site very soon. For now, you can see it here: http://android.processing.org/test/
