### ISSUE TITLE
Connecting Smartwatch

### ISSUE THREAD

**Issue by Twaan07** [processing/processing-android#232]
Hey, i am struggeling getting processing android to work with my moto360. I get to the step where host and destination are connecting, but if I am opening processing, the host disconnects. I think its this problem but don`t know how to solve with processing, http://visualgdb.com/adbfix/ . Hope you can help me.﻿

**Comment by codeanticode** [comment]
@Twaan07 still having this problem?

**Comment by codeanticode** [comment]
If the problem is caused by an old version of the adb, the next release of the mode (beta2) will install the latest version of the tools, so that should solve it. You can also update the tools after the SDK was downloaded by opening the SDK Manager and applying all the available updates.
