### ISSUE TITLE
Cardboard app doesn't need extra permissions

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#239]
Right now READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE, NFC, and VIBRATE are automatically added to the manifest file. Are they needed?

**Comment by jwill** [comment]
According to this looks like minimum is READ_EXTERNAL_STORAGE, NFC. VIBRATE is a nice to have.

https://developers.google.com/vr/android/samples/treasure-hunt

**Comment by codeanticode** [comment]
@jwill thanks for the observation. Now the manifest only has READ_EXTERNAL_STORAGE, NFC, and VIBRATE: https://github.com/processing/processing-android/blob/c958737253f86dcef41ecf18037e1c72b826d983/templates/CardboardManifest.xml.tmpl
