### ISSUE TITLE
keyTyped() not implemented on Android

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#24]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Tuesday May 14, 2013 at 00:20 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/25_

---

keyTyped() does not exist in the Android API, so a decision needs to be made on whether to post a fake event for parity with the desktop, or just leave things as they are.

Original report: http://code.google.com/p/processing/issues/detail?id=1489

**Comment by codeanticode** [comment]
It is implemented [now](https://github.com/processing/processing-android/blob/master/core/src/processing/core/PApplet.java#L2520).
