### ISSUE TITLE
Create gradle project when exporting sketch

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#244]
The Export Android Project creates an ant project, we should switch to gradle which is the default adopted by Android Studio.

**Comment by jwill** [comment]
+1. I think it might also bundle a gradle wrapper so that the resulting package can be run even if the person doesn't have Android Studio installed.

**Comment by codeanticode** [comment]
Implemented with https://github.com/processing/processing-android/commit/cb99af6da38edf13cbac2cac5ed4a71f13ade525, https://github.com/processing/processing-android/commit/87f42d075103a80cc9dbc5e303a3120bbe293c98, https://github.com/processing/processing-android/commit/7941f0719bf90df0b8758e05d27a064dad1ab66e, https://github.com/processing/processing-android/commit/9425bff8c9156398d34a7a6a38f55b0ea85c345d, https://github.com/processing/processing-android/commit/6308d788bcf7b62c04de39947416f7ec4186436f, 
https://github.com/processing/processing-android/commit/730de216996728f266566b7c3badd94c1d849fc3, https://github.com/processing/processing-android/commit/b7b9b3c40d57f9e3f79a45bb15f17a6c5f324ebf, https://github.com/processing/processing-android/commit/855f6b922cc70fba102d6bf5f726998a9c43977a, and https://github.com/processing/processing-android/commit/e992ff092029f8349f7c0db88b6ee245029b59d8.

Outputting ant project is still possible by setting android.export.build_system to ant in Processing's preferences file. Gradle is the default now.
