### ISSUE TITLE
Possible bug in createFont()

### ISSUE THREAD

**Issue by raft75** [processing/processing-android#248]
The following code works correctly in Java mode, but not in Android.
In Java mode the text appears smaller or bigger when I change the size parameter of createFont().
In Android mode the text is always very small. As a workaround to have a consistent behaviour between Java mode and Android mode, I use textSize() with the desired size after createFont().
Tested with Processing 3.2.1 on Galaxy S3 (Android 4.4.2) 

```
PFont f;
void setup() {
  f = createFont("arial.ttf", 32, true);
  textFont(f);
}
void draw() {
  text("Hello", 20, 50);
}
```

**Comment by codeanticode** [comment]
I get text with the correct size depending on the parameter I pass to createFont().

What version of the mode are you using, the latest stable release available through the Contributions Manager?

**Comment by raft75** [comment]
Yes, the Android mode I'm using is the latest stable release available through the Contributions Manager.

**Comment by jburns20** [comment]
I am also seeing this issue (only when loading TTF fonts).

**Comment by codeanticode** [comment]
I can confirm it happens with the Android2D renderer, not OpenGL (P2D/P3D)

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/2e7a4c8de3af95543f40778eef3881da9bc21147
