### ISSUE TITLE
obj PShape textures are not loaded

### ISSUE THREAD

**Issue by nakednous** [processing/processing-android#249]
as the titles says, PShapes textures get not loaded. For an example see [this](https://github.com/remixlab/proscene/tree/master/examples/Droid/FrameInteraction) (that works as expected in the desktop).

**Comment by codeanticode** [comment]
what version of the mode are you using?

**Comment by nakednous** [comment]
3.0.1

**Comment by codeanticode** [comment]
It is fixed with https://github.com/processing/processing-android/commit/041915867e76aafc93b10128d90de81a23840a76.

See [this discussion](https://forum.processing.org/two/discussion/comment/85705/#Comment_85705) in the forum for a temporary workaround in 3.0.2 until the next release is available.

**Comment by darkwave** [comment]
Broken again?

![screenshot_2017-03-24-18-48-15](https://cloud.githubusercontent.com/assets/246174/24307223/936e3868-10c3-11e7-8007-9273c5042eb9.png)

**Comment by codeanticode** [comment]
what version?

**Comment by darkwave** [comment]
@codeanticode 4.0-beta5 version

**Comment by codeanticode** [comment]
Ok, thank you. I look into it as soon as possible.

**Comment by codeanticode** [comment]
[Fixes in PShapeOBJ](https://github.com/processing/processing-android/compare/android-0257-v4.0-beta4...android-0258-v4.0-beta5#diff-e679f67dbd4fa58e55180abf952e9e4c) introduced in beta4 did not make it to beta5 somehow

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/842cbf3a4003f3ca3a620b9ffe36dbf2fbb17e2e
