### ISSUE TITLE
Android emulator doesn't always start on the first attempt

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#25]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Tuesday May 14, 2013 at 00:24 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/26_

----

Original report: http://code.google.com/p/processing/issues/detail?id=1210

**Comment by codeanticode** [comment]
The emulator starts. Because it typically takes a long time, the sketch might fail to run in the first attempt. The solution is to run the sketch again once the emulator is ready.
