### ISSUE TITLE
implement layout() function to embed sketch into larger app

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#252]
This could be used as follows:

```
void setup() {
  layout(R.layout.parent_layout, P2D);
}
```

The sketch will be created in full screen mode inside the parent layout.

**Comment by codeanticode** [comment]
Implemented with https://github.com/processing/processing-android/commit/615ec0e1603700d20736e945266d5fcbff41a2ad

**Comment by codeanticode** [comment]
@benfry Implemented this, and works really well. But also realized that one could pass the layout ID when initializing the sketch object in the activity's onCreate(), doing something like this:

```
public class MainActivity extends AppCompatActivity {
  Sketch sketch;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    sketch = new Sketch();
    PFragment fragment = new PFragment();
    fragment.setSketch(sketch);
    fragment.init(R.id.content_main, getSupportFragmentManager());
    ...
```

In this case, there would no need to pass the layout ID again in the sketch with the layout() function, and so fullScreen() and size() could simply refer to the bounds of the parent view.

**Comment by benfry** [comment]
What percentage of the time is this likely to be used? Remind me again how this needs to work? It seems like the default case doesn't require a layout, but I thought maybe there was an instance where users would *always* need to specify a layout (i.e. wallpapers or something) and so this was looking like a necessity.

**Comment by codeanticode** [comment]
From my experience with Android Studio, it seems to me that the standard way to define UI elements in a normal app is through layouts (either by writing the xml files manually or with the [layout editor](https://developer.android.com/studio/write/layout-editor.html), which then get inflated during runtime. So this would be used most of the time, but I would not call it a necessity. One could still embed the sketch object into an existing view using API calls. It is just that being able to pass the layout ID and get the sketch embedded automatically simplifies things quite a bit, and also make it more compatible with what I believe is the standard UI development methodology in Android Studio.

**Comment by benfry** [comment]
But "most of the time" meaning "most of the time" in Android Studio, right?

**Comment by codeanticode** [comment]
Yes, that's correct. 

What I realized though, is that we don't need any additional API in PApplet for this integration to work. We can just have a init() function in PFragment which would set the layout ID in the sketch instance, and that would take care of everything. So there is no cost (in terms of API complexity) associated to this.

**Comment by benfry** [comment]
Ok, sounds good.

**Comment by codeanticode** [comment]
Resolved with https://github.com/processing/processing-android/commit/037559d2023f6ce0c6f44fea02d95f45c64e5295
