### ISSUE TITLE
Touching the screen with more than one finger messes up mousePressed

### ISSUE THREAD

**Issue by brew4321** [processing/processing-android#256]
Try writing a simple app with something to keep track of the `mousePressed` variable.
Something like this:

```
 void draw(){
        background(255, 255, 255);
        fill(0, 0, 0);
        text("mousePressed = " + mousePressed, width / 2, height / 2);
    }
```

or a println.. or system log if you're in android studio:

```
import android.util.Log;
...
    Log.d("@ print ","mousePressed = " + mousePressed);
```

Then test it on a physical device.
Putting a finger on the screen changes it to true, lifting it changes it to false... But there is a problem when you put more than one finger down at a time. It can lock the variable into true even after all fingers are removed from the screen.

**Comment by brew4321** [comment]
This workaround seems to work:
`import android.view.MotionEvent;`
...
```
    public boolean surfaceTouchEvent(MotionEvent event) {
        if(event.getActionMasked() == MotionEvent.ACTION_UP){
            mousePressed=false;
        }
        return super.surfaceTouchEvent(event);
    }
```

**Comment by codeanticode** [comment]
The touch API is finalized, so you will be able to handle multiple touch points: http://android.processing.org/reference/multitouch/touches.html

**Comment by PatrickMurphy** [comment]
This example no longer works. `touches` will not resolve to a variable for me

**Comment by codeanticode** [comment]
Hi, touches is available in the [recent betas](https://github.com/processing/processing-android/releases) of the mode (not the stable package available from the Contributions Manager)

**Comment by butaniravi** [comment]
This example not works... touches will not resolve to a variable for me... using processing 3.3.2
Is there any work around...??

**Comment by butaniravi** [comment]
https://stackoverflow.com/questions/17166522/can-processing-handle-multi-touch
from this thread I am able to use multitouch... but when event index 0 close before other child event... it stop working...
