### ISSUE TITLE
Cannot import mesh

### ISSUE THREAD

**Issue by omaribraz** [processing/processing-android#258]
I had tried importing a mesh as pShape, WEMesh, and even HeMesh. None of these seem to work, the app just crashes. Is it possible to import meshes into the sketch? It is quite a small mesh. The code works well in the Java mode.

```
import toxi.geom.*;
import toxi.geom.mesh.*;
import toxi.processing.ToxiclibsSupport;

ToxiclibsSupport gfx;
TriangleMesh cave;

void setup() {
  fullScreen();
  gfx = new ToxiclibsSupport(this);
  cave = (TriangleMesh) new STLReader().loadBinary(sketchPath("cave2.stl"), STLReader.TRIANGLEMESH);
}

void draw() {
  background(0);
  pushMatrix();
  fill(40, 120);
  noStroke();
  lights();
  gfx.mesh(cave, false, 0);
  popMatrix();
}
```
```
PShape cave;

void setup() {
  fullScreen();
  cave = loadShape("cave.obj");
}

void draw() {
  background(0);
  cave.setFill(color(255, 255, 255));
  shape(cave);
}
```

**Comment by codeanticode** [comment]
You need to use the P3D renderer:

```
fullScreen(P3D);
```

in order to render 3D objects. This should solve the crash with the second sketch using PShape, but not sure if the toxiclibs and HeMesh are compatible with Android.

**Comment by omaribraz** [comment]
Yep that fixed it thanks. It needed a smaller mesh, I found around 500 polygons was adequate. Also, I found that it will not run with transparency, ie. color(120,40) where 40 is alpha. Not really a big deal.

**Comment by codeanticode** [comment]
Cool, thanks for the update! Both HeMesh and toxiclibs work in the Android mode?

**Comment by omaribraz** [comment]
I have checked toxiclibs, it works well as long as I build the mesh inside the code, ie, I do not import a mesh. I can import an obj as PShape though. toxiclibs also works in cardboard.

**Comment by codeanticode** [comment]
Great to know toxiclibs works, and also in cardboard. Thanks!
