### ISSUE TITLE
mouseX and mouseY are not correctly reported in Android mode 3.0.1

### ISSUE THREAD

**Issue by nakednous** [processing/processing-android#260]
mouseX and mouseY are not correctly reported in Android mode 3.0.1. 0 values are always returned instead.

**Comment by codeanticode** [comment]
I have not observed this issue. Could you double check with the latest version?

**Comment by codeanticode** [comment]
Can you confirm if this still happens with the latest [release candidate](https://github.com/processing/processing-android/releases/tag/android-264)? Thanks!

**Comment by codeanticode** [comment]
Did not receive confirmation and haven't observed in version 4 of the mode, closing.
