### ISSUE TITLE
0255 - The method onCreate(Bundle) is undefined for the type PApplet

### ISSUE THREAD

**Issue by CupOfTea** [processing/processing-android#262]
problem with android mode 0255 4.0b2

  the following code compiles without problem in 0252
```
import android.os.Bundle;
import android.view.WindowManager;
void onCreate(Bundle bundle) {
  super.onCreate(bundle);
  getActivity().getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
}
void setup(){}
void draw(){}

```
  in 0255 I get
  
```
  ----------
1. ERROR in C:\Users\anyone\AppData\Local\Temp\android1478702949045067316sketch\src\processing\test\sketch_161206a\sketch_161206a.java (at line 27)
	super.onCreate(bundle);
	      ^^^^^^^^
The method onCreate(Bundle) is undefined for the type PApplet
----------
2. ERROR in C:\Users\anyone\AppData\Local\Temp\android1478702949045067316sketch\src\processing\test\sketch_161206a\sketch_161206a.java (at line 28)
	getActivity().getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
	^^^^^^^^^^^
The method getActivity() is undefined for the type sketch_161206a
----------
2 problems (2 errors)
```

using surface.getActivity()....   got rid of that error.

  
 while trying to ensure I hadn't messed up I also noticed
 
 manually installing 0255 to a fresh processing install resulted in a partial unusable SDK install.
 I had to first install 0252 using the contributions manager and install the SDK before manually installing 0255.
 then android mode did not appear in the contributions manager until typing an "a" in the filter box.

**Comment by codeanticode** [comment]
Hi, PApplet is not a subclass of Activity in version 0255 of the mode, that's why onCreate() is not accessible any longer from the sketch instance. But, as you found out already, you can get it through the the surface field.

The problem with the manual install is a separate issue, but haven't experienced it myself. I will open a separate issue for it and will take a look.
