### ISSUE TITLE
Font size argument currently represents pixels

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#264]
It should be points, and internally converted to pixels according to the screen DPI.

Some useful links:

http://stackoverflow.com/a/2025541
https://developer.android.com/guide/practices/screens_support.html
https://www.captechconsulting.com/blogs/understanding-density-independence-in-android

**Comment by benfry** [comment]
Not a good idea—this would be a major break from the rest of the Processing API, which deals entirely in pixels.

**Comment by codeanticode** [comment]
Ok. Users should scale the font with the display density, right? Something like this:

float density = surface.density;
font = createFont("Roboto", 32);

(note that surface.density not yet exists, #263)

**Comment by benfry** [comment]
Yep.

**Comment by codeanticode** [comment]
ok, will close the issue then.
