### ISSUE TITLE
onRequestPermissionsResult() handler is available only in SDK level 23

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#268]
But it is added to the main activity even when the selected SDK level is lower than than.

**Comment by codeanticode** [comment]
This handler is added irrespectively of the SDK level with the new template mechanism, so it is very likely an issue again. Need to check with older device.

**Comment by mangal1995** [comment]
It wont be an issue as for API level < 23 , permissions are given at installation time only.No need to check for the permissions at run-time .

**Comment by codeanticode** [comment]
Good point, thank you!
