### ISSUE TITLE
PApplet.resume() and Activity.onResume() called before PApplet.setup()

### ISSUE THREAD

**Issue by adri326** [processing/processing-android#274]
I saw this issue while implementing the android.hardware.SensorManager class. This is a code that will show the error:
```
void setup() {
  println("Setup");
}
void onResume() {
  super.onResume();
  println("Android's resume");
}
void resume() {
  println("Processing's resume");
}
```
And the output log:
```
Processing's resume
Android's resume
Setup
```

Any new programmer would put the code to initialise the program in the setup() function and the on-resume code in the resume(), but wouldn't think that the resume() function is called before the setup() function. I personally think that the resume() function shouldn't be triggered at the beginning, for the user can trigger it manually.

**Comment by codeanticode** [comment]
Thanks for the observation. I agree that resume() should not be triggered before setup(), although onResume() is ok (part of Android's application lifecycle). Should be taken care with https://github.com/processing/processing-android/commit/173c65133583f23f30dafe4b99463b2b74390777
