### ISSUE TITLE
should be fullScreen() be the default?

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#276]
Right now the default screen size when the user does not provide a size() call is 100x100, but using the entire display makes more sense on Android.

**Comment by victordiaz** [comment]
Maybe it would be better to set the size to the Drawing area? 
- In this case it could be easily embedable in a fragment anywhere and any size in the screen when using Android Studio. 
- In normal Processing mode, I would give 2 options 
  * Immersive - with all android controls hidden
  * Normal - Showing the status and system bar (top and bottom bars)

**Comment by codeanticode** [comment]
Thanks for your suggestions! Commit https://github.com/processing/processing-android/commit/615ec0e1603700d20736e945266d5fcbff41a2ad implements the following:

* running a sketch without size or fullscreen will run it in full screen, but without hiding the status and system bar. This is equivalent to use size(displayWidth, displayHeight). The rationale is that if the user does not explicitly request full-screen, we should not hide the controls, and the most reasonable size setting when lacking ant other information is that of the entire display.

* embedding the sketch in a parent layout results in the sketch using the entire parent area, see #252
