### ISSUE TITLE
Update Android with fragments example in web

### ISSUE THREAD

**Issue by victordiaz** [processing/processing-android#279]
I couldn't find a place to send a pull request to update the web, so I just create this issue

The Android example in http://android.processing.org/tutorials/android_studio/index.html doesn't reflect the current API that uses PFragment. 

The content inside onCreate in step 7 should be
```
super.onCreate(savedInstanceState);
setContentView(R.layout.activity_main);
FragmentManager fragmentManager = getSupportFragmentManager();
Sketch sketch = new Sketch();
PFragment fragment = new PFragment();
fragment.setSketch(sketch);
fragmentManager.beginTransaction()
  .replace(R.id.container, fragment)
  .commit();
```

Maybe is a good idea to add in step 6 displayWidth and displayHeight in size, so the sketch will adapt to the fragment size
`
size(displayWidth, displayHeight, P3D) // or any other renderer
`

**Comment by rich-gg** [comment]
thank you for that tip !

**Comment by omerjerk** [comment]
@rich-gg I do not have access to edit that page. I guess @codeanticode will need to do it.

**Comment by codeanticode** [comment]
@rich-gg The website repository is currently at https://github.com/codeanticode/processing-android-website. Please re-open the and submit the PR there. Thank you!
