### ISSUE TITLE
No result shown when using PCardboard.STEREO (it works when MONO)

### ISSUE THREAD

**Issue by darkwave** [processing/processing-android#286]
I'm testing the super cool cardboard feature on Android 4.4.2 but when PCardboard.STEREO is used it produces no result at all.

`setup()` method seems to be not executed: for example, following code does not change the background color and a black screen (with no lens correction, only _UI_ elements) appears.

No errors, no freeze (the _UI_ is responsive). Nothing.

```processing
import processing.cardboard.*;

void setup() {
  fullScreen(PCardboard.STEREO);
  background(255, 0, 0);
}

void draw() {
  background(255, 128, 0);
}
```

I'm using Android mode 4.0-beta4

![screenshot_2017-02-03-12-14-19](https://cloud.githubusercontent.com/assets/246174/22589486/d71cbb8c-ea0a-11e6-9ad0-3809525157cc.png)

**Comment by codeanticode** [comment]
Could be related to the Android version? I running your sketch on a N5X with Android 7.1.1 and works as expected.

**Comment by darkwave** [comment]
Tested on Android 4.3 (no gyro) and 5.1.1 and _renderer_ seems to work fine.

According to Google cardboard documentation it should work fine on 4.4.1 too but, at least on my Samsung Galaxy Note 2, it does not. :face_with_head_bandage:

**Comment by codeanticode** [comment]
Interesting, maybe some setting in the library makes it incompatible with your device. Doesn't Cardboard require a gyro to work correctly?

**Comment by darkwave** [comment]
> On a related note, looks like it is possible to emulate the gyroscope by combining data from other sensors, so one can use Cardboard on devices without a gyro.

I was going to open another issue suggesting the same improvement :blush: 

Before Cardboard came out I experimented a lot with **accelerometer** and worked pretty well on many smartphones and tablets so I wonder if it's possible to use just the stereo view provided by cardboard sdk and move the scene transforming it according to accelerometer... :thinking: 

I think accelerometer data only permits to obtain yaw, pitch and roll for **_not moving object_** so may be a solution for VR experience.

**Comment by codeanticode** [comment]
According to the [Cardboard docs](https://developers.google.com/vr/cardboard/overview), any android phone would be work (this is not he case for [Daydream](https://developers.google.com/vr/daydream/overview), although both Cardboard and Daydream use the same underlying [VR SDK](https://developers.google.com/vr/android/reference_overview)). 

On the other hand, the Processing library simply wraps [GvrView](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView), but I don't see any option to control the stereo view using accelerometer data only. If you find some relevant information about this, please let me know.

**Comment by darkwave** [comment]
@codeanticode Latest release of Android Mode is now working correctly!!! :smile_cat: 

What changed from beta4? Maybe some issue with the bundled libraries?

**Comment by codeanticode** [comment]
not sure, I will close this issue, but re-open in the problem re-appears.
