### ISSUE TITLE
Add support for actual mouse events (not touch events mapped to mouse) in Android

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#29]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Tuesday May 14, 2013 at 00:35 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/30_

---

Original request: http://code.google.com/p/processing/issues/detail?id=1544

**Comment by codeanticode** [comment]
Taken care with the touch API
