### ISSUE TITLE
ant scripts and android tool are no longer available

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#307]
Version 25.3.1 of the SDK tools remove the ant scripts and the android tool:

https://code.google.com/p/android/issues/detail?id=235455
https://code.google.com/p/android/issues/detail?id=235410

See release notes:
https://developer.android.com/studio/releases/sdk-tools.html

Right now, using up to version 25.2.5 of the SDK tools ensures that the mode works, but need a longer-term solution. The mode already exports Gradle projects, but may need to switch to gradle for the internal build process as well.

**Comment by rijuldhir** [comment]
@codeanticode Can you suggest me some discussion or issues on ant scripts so that I can have a look at them. I have submitted the  GSoC proposal Draft on the website for reviews.

**Comment by codeanticode** [comment]
Another important consideration: before one could just drop an android library built as a jar file, but nowadays they are often provided in source form or as an aar package hosted in maven or jcenter, so once the gradle is the internal build system, one could add these dependencies directly into the sketch.

**Comment by MasterYushi** [comment]
When will this be fixed? It has been 5 months now

**Comment by codeanticode** [comment]
Work is in progress in this branch: https://github.com/processing/processing-android/tree/rc1

Gradle build and SDK download/update are implemented, finishing the emulator support, which was also broken after the android tool was removed.

**Comment by codeanticode** [comment]
Fixed with:

* Gradle build: https://github.com/processing/processing-android/commit/3eba9ff7bcbd9cde9539e91a724321ebec3736db through https://github.com/processing/processing-android/commit/cab721cd66fc9b7009bd71bc07ff1a9c365ef164
* SDK download/update: https://github.com/processing/processing-android/commit/9dfff6e645718b69d879d81b4b4052365c6389cd through https://github.com/processing/processing-android/commit/46161cdc4d7c5faa594c045985aeaef1c7a71ec5
* Create AVDs with avdmanager: https://github.com/processing/processing-android/commit/9b78586d3cbfa639adb4a93789b529496e816f87 through https://github.com/processing/processing-android/commit/f082c0f7f594880e1b57c2572b9d79f30001ea0a

**Comment by codeanticode** [comment]
@danieltorrer, @mnasell, @trippedout, @MasterYushi, @TheWlr9, @0xFireball, @mschillo The RC1 release including the new Gradle-based build system and many other improvements is available under [releases](https://github.com/processing/processing-android/releases/tag/android-264) if you want to give it a try. The next stable release should be in the CM in a couple of weeks, after completing some rounds of testing with the RC1. Please feel free to submit any issues you may find in it. Thank you!

**Comment by danieltorrer** [comment]
@codeanticode Thanks for the amazing effort, i already downloaded it and i'm testing to export the project and building it in Android studio. Will post if I came across anything.

**Comment by MasterYushi** [comment]
@codeanticode How do I work with the zip?

**Comment by codeanticode** [comment]
@MasterYushi In order to test the RCs, download the zip package, unpack, and then move the uncompressed AndroidMode folder into <sketchbook folder>/modes

**Comment by MasterYushi** [comment]
@codeanticode I figured it out and everything is working fine till now. I can finally get back to working on my app, thanks for the efforts!
