### ISSUE TITLE
Creating AVD on Linux fails

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#308]
The image is installed without problem, but when Processing tries to create an AVD, the following error comes up:

```
Android 7.1.1 is a basic Android platform.
Do you wish to create a custom hardware profile [no]
    stderr:
Error: Failed to create the SD card.
Error: Failed to create sdcard in the AVD folder.
Error: AVD not created.
```

**Comment by cjdg** [comment]
are you running on an AMD processor?

**Comment by codeanticode** [comment]
No, an Intel.

**Comment by rupak0577** [comment]
It seems there are some 32bit dependencies for creating the sdcard

http://stackoverflow.com/questions/3878445/ubuntu-error-failed-to-create-the-sd-card

**Comment by codeanticode** [comment]
Confirmed that installing the lib32stdc++6 package on Ubuntu 16.0.4 64bit, as suggested in the discussion that @rupak0577 pointed to, solves the problem. I will add a message dialog after installing the system image on Linux that provides this info.

**Comment by codeanticode** [comment]
https://github.com/processing/processing-android/commit/f3522a43646c5bdf9872791a85ef2c63045bbd2b
