### ISSUE TITLE
patches to implement the Android version of Processing using the Fragment API

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#31]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Tuesday May 14, 2013 at 00:38 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/32_

----

Original report with patches: http://code.google.com/p/processing/issues/detail?id=1335

**Comment by omerjerk** [comment]
@codeanticode @benfry 
I'd like to implement this enhancement. Can you just tell me some point to keep in mind while implementing this ?
The above link is not working.

**Comment by codeanticode** [comment]
Implemented with https://github.com/processing/processing-android/pull/118
