### ISSUE TITLE
Implement API to access wallpaper and watch face properties

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#313]
Need to give access to:

* wallpaper [preview state](https://developer.android.com/reference/android/service/wallpaper/WallpaperService.Engine.html#isPreview())
* wallpaper [offsets](https://developer.android.com/reference/android/service/wallpaper/WallpaperService.Engine.html#onOffsetsChanged(float,%20float,%20float,%20float,%20int,%20int))
* watch face [ambient mode state](https://developer.android.com/reference/android/support/wearable/watchface/WatchFaceService.Engine.html#isInAmbientMode())
* watch face [screen shape and insets](https://developer.android.com/reference/android/service/wallpaper/WallpaperService.Engine.html#onApplyWindowInsets(android.view.WindowInsets))
* watch face [special properties](https://developer.android.com/reference/android/support/wearable/watchface/WatchFaceService.Engine.html#onPropertiesChanged(android.os.Bundle))

**Comment by rijuldhir** [comment]
@codeanticode I am interested in contributing to this repo.
I am also a GSoC,17 aspirant. Can you assign me a quick-win issue and help me contribute

**Comment by codeanticode** [comment]
@rijuldhir Many thanks for your interest and enthusiasm. Here you have some lighter issues you could look at: #21, #303, #253.

Just as a quick comment to better frame your future contributions. We are not really after scoring "winning points" quickly, but rather to engage with people with diverse backgrounds and interests in a project that benefits a large community of users around the world ;-)

**Comment by codeanticode** [comment]
implemented in https://github.com/processing/processing-android/commit/d66d4e671cdf164d974d5ba42fa515b120a34194
