### ISSUE TITLE
Cannot run sketches on Android device

### ISSUE THREAD

**Issue by mschillo** [processing/processing-android#320]
Hi,

an example sketch gets compiled and transferred to my android device. The next thing that happens is that a window appears saying "\<sketch name\> stopped" with an "ok" button.

How can I find out what is going wrong?

Cheerio,

Michael.

PS: Processing 3.3 on macOS 10.12.4, Android Mode 0260  for Samsung Galaxy Tab A, Android 6.0.1

This is the code I ran:
`void setup() {`
`noStroke(); `
 `fill(0);` 
 `}`

`void draw() {`
`  background(204);`
`  if (mousePressed) {`
`    if (mouseX < width/2) {`
 `     rect(0, 0, width/2, height); // Left`
`    } else {`
`      rect(width/2, 0, width/2, height); // Right`
`    }`
`  }`
`}`

EDIT: I may have had the wrong Android API before, changed it to Android 6.0 (API 23). This is the error I get from the Processing console:

> FATAL EXCEP TION: main
> Process: processing.test.androidsimpleexample, PID: 14720
> java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{processing.test.androidsimpleexample/processing.test.androidsimpleexample.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "processing.test.androidsimpleexample.MainActivity" on path: DexPathList[[zip file "/data/app/processing.test.androidsimpleexample-2/base.apk"],nativeLibraryDirectories=[/data/app/processing.test.androidsimpleexample-2/lib/arm, /vendor/lib, /system/lib]]
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3132)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
> 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:7325)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
> Caused by: java.lang.ClassNotFoundException: Didn't find class "processing.test.androidsimpleexample.MainActivity" on path: DexPathList[[zip file "/data/app/processing.test.androidsimpleexample-2/base.apk"],nativeLibraryDirectories=[/data/app/processing.test.androidsimpleexample-2/lib/arm, /vendor/lib, /system/lib]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
> 	at android.app.Instrumentation.newActivity(Instrumentation.java:1096)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3122)
> 	... 9 more
> 	Suppressed: java.io.IOException: Failed to open dex files from /data/app/processing.test.androidsimpleexample-2/base.apk
> 		at dalvik.system.DexFile.openDexFileNative(Native Method)
> 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
> 		at dalvik.system.DexFile.<init>(DexFile.java:80)
> 		at dalvik.system.DexFile.<init>(DexFile.java:59)
> 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
> 		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
> 		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
> 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
> 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
> 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:86)
> 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:47)
> 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:438)
> 		at android.app.LoadedApk.makeApplication(LoadedApk.java:663)
> 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6395)
> 		at android.app.ActivityThread.access$1800(ActivityThread.java:229)
> 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
> 		... 6 more
> 	Suppressed: java.lang.ClassNotFoundException: processing.test.androidsimpleexample.MainActivity
> 		at java.lang.Class.classForName(Native Method)
> 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
> 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
> 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
> 		... 12 more
> 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by codeanticode** [comment]
Hi, are you using the SDK that the mode downloads automatically after installing it for the first time?

**Comment by mschillo** [comment]
I tried many things and at the moment I don't remember where the current SDK came from. But feel free to direct me: should I try the automatic download with the current Android Mode 0260 built?

Thanks,

Michael.

**Comment by xuv** [comment]
Running in the same issue.
Processing 3.3, Mac 10.12.4, Android Mode 3.0.2, Galaxy S5 running Android 6.0.1
Fresh installation of Processing, Android Mode and SDK that loads by default (7.1.1)

1. With an empty Processing script. 
2. Compilation is happening, sketch transferred on device.
3. _sketch_170413a has stopped_ is displayed on the phone
No error message in the Processing IDE console.

Tried installing Android SDK 6.0 to see if it would correct the error.
No error

**Comment by remy-luisant** [comment]
Same issue, no error message.
Processing 0257. Arch Linux. Android 6. Using the Android SDK installed with Android Studio. Android mode 3.0.2.

I don't have a good idea of what I'm doing, so it might be a novice mistake on my part. Building and running things with Android Studio without Processing works.

**Comment by remy-luisant** [comment]
Forgot to add: I have adb access, and am willing to provide all logs, if you just tell me where they are. I don't see a handy /var/log/, so... yeah.

**Comment by mschillo** [comment]
Question has been answered here:
https://forum.processing.org/two/discussion/21588/running-sketches-on-my-smartphone-does-not-work-anymore#latest

**Comment by xuv** [comment]
Hello @mschillo Thanks for pointing to this thread on the forum. But this thread is impossibly long with so many different answers.
Could you please point to the working solution to this problem? 
I believe you are pointing to [your answer](https://forum.processing.org/two/discussion/comment/95347/#Comment_95347). Though you are mentioning other versions of the Android-mode, and the steps are not that clear to me. Does it involve removing the Android SDK downloaded automatically from Processing? Does it involve using the SDK installed by Android Studio? Etc...

**Comment by mschillo** [comment]
@xuv 

> I believe you are pointing to [your answer](https://forum.processing.org/two/discussion/comment/95347/#Comment_95347).

exactly. sorry, did not know you can refer to a message in a thread. Thanks for teaching me!

> Does it involve removing the Android SDK downloaded automatically from Processing? 

yes.

> Does it involve using the SDK installed by Android Studio?

yes.

> Etc...

What exactly do you mean by etc.? 

Cheerio,

Michael.

**Comment by xuv** [comment]
@mschillo Thanks for the reply.
My "etc." could have been more explicit. I realize from your post on the forum that in the steps you are describing, it seems to me, your are assuming we read the whole thread. And I feel there is some things not explicitly said in the steps to get this working. So I was wondering if you could simplify maybe rewrite this here into a couple easy steps and summarize the process. It would be really helpful, I think.

**Comment by benfry** [comment]
Folks, please use the forum for discussion. We're trying to fix issues here, and it takes more of our time to sort through these when it's not actually a bug report.

**Comment by phanirithvij** [comment]
@benfry I believe you can create a new label `coding-question` or something similar. That helps sorting issues. I assume that's already being followed as it's been around 2 years already.
