### ISSUE TITLE
Instructions on how to set SDK path?

### ISSUE THREAD

**Issue by mschillo** [processing/processing-android#321]
Hi,

my android device runs Android 6.0.1. I downloaded the current Android Mode 0260. Now I am trying to set the proper SDK path.

I tried downloading manually from the link provided by the window "Is the Android SDK installed?" which sends me to [android.com](https://developer.android.com/studio/index.html#downloads). But it also advises me to download the SDK platform for API 25. Judging from what the Android SDK Manager tells me I thought I should install API 23 for my device. Which one is correct?

Many thanks in advance,

Michael.

PS: Processing 3.3 on macOS 10.12.4, Android Mode 0260  for Samsung Galaxy Tab A, Android 6.0.1

**Comment by codeanticode** [comment]
Ok, I see. I think some fixes/updates are needed in the mode itself, a problem being that Google removed the ant scripts from the SDK: #307. The mode is still using ant for building the sketches as android packages, and we will try to update to gradle as soon as possible (Processing exports the sketch as a gradle project through)

The following are the tool versions that should work with the mode currently:

![image](https://cloud.githubusercontent.com/assets/62246/25018523/75977bd2-2055-11e7-814f-ae8fc73876e0.png)

**Comment by mschillo** [comment]
you mean I should use the 7.1.1 Android SDK even though my Android device runs 6.0.1?

Thanks for your help!

Michael.

**Comment by mschillo** [comment]
Question has been answered here:
https://forum.processing.org/two/discussion/21588/running-sketches-on-my-smartphone-does-not-work-anymore#latest
