### ISSUE TITLE
When the screen rotates, the live paper does not resize itself . Version 260 Beta7(and 259)

### ISSUE THREAD

**Issue by TrW236** [processing/processing-android#324]
https://forum.processing.org/two/discussion/21998/surface-setsize-and-setresizable-do-not-exist-in-android-mode-how-to-resize-the-sketch-dynamic#latest

The Problem is in the Forum

**Comment by codeanticode** [comment]
I can reproduce it on a Galaxy Tab 3 with KitKat, thanks for reporting.
