### ISSUE TITLE
Keyboard doesn't open using MENU button on Nexus (and perhaps other devices)

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#33]
<a href="https://github.com/jeffThompson"><img src="https://avatars.githubusercontent.com/u/509469?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeffThompson](https://github.com/jeffThompson)**
_Friday May 17, 2013 at 21:33 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/34_

---

Having a Nexus tablet and no other Android devices, I can only say that the keyboard does not open when holding the MENU button (the suggested method on the Wiki).

To fix this, I've used the following code:

``` java
// use menu button to toggle keyboard
if (key == CODED && keyCode == MENU) {
    // turn on keyboard - via: http://stackoverflow.com/a/2348030
    InputMethodManager inputMgr = (InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);
      inputMgr.toggleSoftInput(0, 0);
}
```

**Comment by pvtmert** [comment]
i think you need to hold menu button

or try android.view.Keyevent.KEYCODE_MENU

**Comment by codeanticode** [comment]
Added openKeyboard() and closeKeyboard() in the multitouch branch: 

https://github.com/processing/processing-android/commit/2c705e807affa1b922b75d7f37cb5dd73acdaf7f

but this API is not yet finalized.

**Comment by codeanticode** [comment]
the open/closeKeyboard functions were included in master
