### ISSUE TITLE
No debug info available on console when running

### ISSUE THREAD

**Issue by kfrajer** [processing/processing-android#331]
Hi 
Below is a portion of my console output when I run an android app. It ends with "**AndroidDevice: cannot find process id, console output will be disabled**". this happen with any app that I try to run on my phone. This wasn't happening before. Since I get this error, I do not get any information related to errors in case my application crashes. I believe this started happening when I started using Android mode version 4.0-beta7.

I am using Processing 3.3.2, Windows 10 x64 on a Samsung Galaxy S4
Android SDK tools 25.2.5   Android SDK bukd tools 25.0.2

I am not sure what is my API target as I cannot see it anymore in the Processing IDE (I guess it is a recent change as well?) How can you tell?

Kfrajer

>   [crunch] Processing image to cache: C:\Users\C\AppData\Local\Temp\android7601982729575122958sketch\res\drawable\icon.png => C:\Users\C\AppData\Local\Temp\android7601982729575122958sketch\bin\res\drawable\icon.png
>    [crunch]   (processed image to cache entry C:\Users\C\AppData\Local\Temp\android7601982729575122958sketch\bin\res\drawable\icon.png: 84% size of source)
>    [crunch] Crunched 6 PNG files to update cache
> 
> -package-resources:
> Creating full resource package...
>      [aapt] Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.
> 
> -package:
> Current build type is different than previous build: forced apkbuilder run.
> Creating sketch_170428d-debug-unaligned.apk and signing it with a debug key...
> 
> -post-package:
> 
> -do-debug:
> Running zip align on final apk...
>      [echo] Debug Package: C:\Users\C\AppData\Local\Temp\android7601982729575122958sketch\bin\sketch_170428d-debug.apk
> [propertyfile] Creating new property file: C:\Users\C\AppData\Local\Temp\android7601982729575122958sketch\bin\build.prop
> [propertyfile] Updating property file: C:\Users\C\AppData\Local\Temp\android7601982729575122958sketch\bin\build.prop
> [propertyfile] Updating property file: C:\Users\C\AppData\Local\Temp\android7601982729575122958sketch\bin\build.prop
> [propertyfile] Updating property file: C:\Users\C\AppData\Local\Temp\android7601982729575122958sketch\bin\build.prop
> 
> -post-build:
> 
> debug:
> AndroidDevice: cannot find process id, console output will be disabled.

**Comment by ewelinka** [comment]
Same problem on Processing 3.3.3, OS X Yosemite + Tablet Haier-Pad723U
Android SDK tools 25.2.5 Android SDK build tools 25.0.3

**Comment by codeanticode** [comment]
@kfrajer @ewelinka Could you check if this issue is still present in [RC2](https://github.com/processing/processing-android/releases/tag/android-265)? Thanks a lot!

**Comment by kfrajer** [comment]
This is what I get now:

> ... (Other output)
> ... (Other output)
> ... (Other output)
> BUILD SUCCESSFUL in 1m 9s
> 35 actionable tasks: 35 executed
> AndroidDevice: cannot find process id, console output will be disabled.

My application runs on my device though. I am using 
AS 2.3.3 
Android SDK tools 26.0.2
I will say that I am running Android API 21... I cannot see it in the current Processing IDE but it is what my phone has (Android v 5.0.1 Lollipop)

I don't think this is really helpful as I just started running some samples using the new mode. Notice I tested this with RC1 and RC2... I used the mode you provided in the forum and I just noticed that in this post you were using RC2.

Kfrajer

**Comment by codeanticode** [comment]
Could you paste the output logcat when you are running a Processing sketch with some println() calls?

As for the RCs, I may post a few more in rapid succession as I test last minute changes before the pushing the stable release through the CM. Just use the last one.

**Comment by codeanticode** [comment]
@kfrajer the reason for the lack of messages in the console may be some formatting issue with  logcat, so it would be very informative if you can past a sample of the output from `adb logcat` , especially when you are running your Processing sketches. Thanks.

**Comment by kfrajer** [comment]
@codeanticode Sorry for my late reply, just been busy. I should be able to upload the sample output this weekend.

Kf

**Comment by codeanticode** [comment]
@kfrajer That would be wonderful, thanks a lot!

**Comment by raft75** [comment]
[log.zip](https://github.com/processing/processing-android/files/1235311/log.zip)
Please find attached the output I get with adb logcat when I run the following code:

void draw() {
background(204);
println("test");
}

With release 0265 the sketch runs on my tablet (it didn't with 4.0-beta5) however I still don't get console output, but this error:
AndroidDevice: cannot find process id, console output will be disabled.

**Comment by codeanticode** [comment]
@raft75 This is very useful, thank you. I will go through the log and let you know how it goes.

**Comment by codeanticode** [comment]
@raft75 @kfrajer I uploaded a [new RC](https://github.com/processing/processing-android/releases/tag/android-266), hopefully the last one, where I did some tweaks to support logcat format that appeared in the log posted by raft75. It would be great if you can test it and let me know if this issue is resolved. Thank you!

**Comment by raft75** [comment]
I works on my tablet Lenovo TAB 2 A10-70F that I used to provide you the log, but unfortunately it does not work on my Samsung SIII Neo, I don't see any output or error messages.
Please find attached log.
[log.zip](https://github.com/processing/processing-android/files/1241318/log.zip)

The version of support tools I use is the one included with sdk downloaded automatically from Processing:
Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android

**Comment by raft75** [comment]
I works = It works

**Comment by codeanticode** [comment]
Glad to know the latest fix solves the issue at least for some devices. I confirm that I'm using the same version of adb. It could be that some manufacturers make custom changes to the Android system so the logcat output is slightly different from the standard.

In this case, they key element is to find the output line where the process corresponding to the Processing sketch is launched. This line contains the process ID (pid), which later identifies the output lines that correspond only to that process... The standard process launch line is something like:
```
I/ActivityManager( 1451): Start proc 8770:processing.test.sketch_170818a for activity processing.test.sketch_170818a/.MainActivity
```
and the pid is right after "Start proc". In the log from your Lenovo, the line is slightly different:

I/ActivityManager(  648): Start proc processing.test.sketch_170818a for activity processing.test.sketch_170818a/.MainActivity: pid=4256 uid=10175 gids={50175}

where you can see the pid is right after "pid="

In the latest log, I cannot find any line that resembles the process launching output, so don't know how to retrieve the pid.

**Comment by codeanticode** [comment]
@kfrajer @raft75 do you have any updates on this?

**Comment by raft75** [comment]
I don't have any updates since I have already tested this issue on my two devices, please let me know how I can help.

**Comment by codeanticode** [comment]
Ok, no problem. I don't think I can do anything else with regards to this issue. As I mentioned in the post above about the output of logcat, I was unable to find the line that contains the process id. I haven't seen any other comparable report, so it seems it only affects this specific device for some reason, and that the recent fixes in the logcat parsing cover the majority of the cases.

I will go ahead and close the issue. If you have any insight, just post a comment here and I will re-open it.
