### ISSUE TITLE
Access to FrameLayout: frame.setId(viewId); changed to  frame.setId(View.generateViewId());

### ISSUE THREAD

**Issue by kfrajer** [processing/processing-android#333]
Hi
I was checking the revision history and I couldn't find anything about the following change. In previous versions, I was able to retrieve the FrameLayout like this to add to the current view::

```
FrameLayout fl;
fl = (FrameLayout)act.findViewById(0x1000);
fl.addView(editUsr);   // editUsr is an instance of EditText Widget
```
This is what I would get when compiling the project:
```
public class MainActivity extends Activity {
    PApplet fragment;
    private static final String MAIN_FRAGMENT_TAG = "main_fragment";
    int viewId = 0x1000;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Window window = getWindow();
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        FrameLayout frame = new FrameLayout(this);
        frame.setId(viewId);

       ..... OTHER CODE

}
```

However, now I get the following code related to setting the Id to the frame: 

```
public class MainActivity extends AppCompatActivity {
  private PApplet sketch;
  
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    FrameLayout frame = new FrameLayout(this);
    frame.setId(View.generateViewId());    //  <---------????????????????????????? ### ??

       ..... OTHER CODE
```

How do I get access to the ID? Is the dynamic binding  already implemented in Android Mode? This is discussed in this article: [https://medium.com/google-developers/no-more-findviewbyid-457457644885](https://medium.com/google-developers/no-more-findviewbyid-457457644885). Is there any other way to get access to the current FrameLayout?

kfrajer

**Comment by kfrajer** [comment]
Never mind. I was spoiled with the initial design. The proper way to access the ViewGroup of interest is described here: http://stackoverflow.com/questions/4486034/get-root-view-from-current-activity

kfrajer

**Comment by codeanticode** [comment]
No problem, that got changed again the latest revisions of the mode (https://github.com/processing/processing-android/commit/a43374ce73e18a8a209b6a7ab885166b985d1541), because View.generateViewId() is not available in SDK level 16
