### ISSUE TITLE
How to use？

### ISSUE THREAD

**Issue by issca** [processing/processing-android#335]
Sorry to trouble you，this is my first time to used processing-android，I don't know how to use as a Moudle into Android Studio. please help and give some advice.

**Comment by codeanticode** [comment]
Hi, please refer to the [forum](https://forum.processing.org/two/categories/android) with questions on how to use the android mode. Also, I have made some Android Studio sample projects available [here](https://github.com/codeanticode/processing-android-tutorials/tree/master/android_studio).
