### ISSUE TITLE
Maven coordinates?

### ISSUE THREAD

**Issue by noncom** [processing/processing-android#336]
Hello, I am interested in developing with Processing on Android.. in order to do so, whether I use Android Studio or AIDE, I need Maven coordinates to pull the library in.. but I can't find any?

The official Processing page on MavenRepository https://mvnrepository.com/artifact/org.processing does not list anything Android.

**Comment by codeanticode** [comment]
Hi, we don't have a Maven repository for the Android processing-core library at the moment, this was discussed in another issue #278, but I haven't heard any updates.
