### ISSUE TITLE
Cardboard VR crash

### ISSUE THREAD

**Issue by grauwald** [processing/processing-android#341]
Just got an error compiling a VR app using 4.x version of Android Mode.

`processing.android.PFragment cannot be cast to com.google.vr.sdk.base.GvrActivity`

Basic examples work.  This one uses a PShape made of random vertices.

**Comment by codeanticode** [comment]
Did you switch the mode to VR in the Android menu?

![image](https://cloud.githubusercontent.com/assets/62246/26487492/b65596de-423a-11e7-9e6d-196f3bb8fe08.png)

**Comment by grauwald** [comment]
Oh, um, yeah.  That fixed it ;)  Thanks.

Now I'm trying to implement a shader with this and getting another error.  I might be diving in too deep too quickly but here's the error:

java.lang.IllegalArgumentException: File data/fogColor.glsl contains a path separator 

Where the Fog Color shader is the one found at the end of this thread:

https://forum.processing.org/one/topic/different-shaders-for-geometry-lines-and-text.html 

Guessing there's probably some fundamental differences between desktop and android shaders.

**Comment by grauwald** [comment]
Nevermind on that last one.  Had to do with putting "data/fogColor.glsl" instead of just "fogColor.glsl"  

Launching on the device now but throwing another error with the shaders added:

`OpenGL error 1281 at bot beginDraw(): invalid value`

**Comment by relddir123** [comment]
When you have the beginDraw() function called, print out the value at which the object is drawn there. If you can (a value prints), I can't help you. If you can't (you get "null" or "NaN" or something like that or an error there), you should hard code in a default value.

**Comment by codeanticode** [comment]
@grauwald GLES shaders need the following additional pre-processor directive to work properly:

```
#ifdef GL_ES
precision mediump float;
precision mediump int;
#endif
```

**Comment by grauwald** [comment]
Thanks for the help all!

@codeanticode I'll try that out with the pre-processor directive.  So the shader should look like?:

```
#define PROCESSING_COLOR_SHADER

#ifdef GL_ES
precision mediump float;
precision mediump int;
#endif

varying vec4 vertColor;

uniform float fogNear;
uniform float fogFar;

void main(){
    gl_FragColor = vertColor;
    
    vec3 fogColor = vec3(0.0, 0.0, 0.0);
    float depth = gl_FragCoord.z / gl_FragCoord.w;
    float fogFactor = smoothstep(fogNear, fogFar, depth);
    gl_FragColor = mix(gl_FragColor, vec4(fogColor, gl_FragColor.w), fogFactor);
}
```

**Comment by codeanticode** [comment]
@grauwald This looks more a programming question, which you can post in the current Processing forum, either on the GLSL or the Android sections? 

The main purpose of the issues page on GitHub is to report bugs, which does not seem to be the case.
