### ISSUE TITLE
PFont isn't recognized as a class

### ISSUE THREAD

**Issue by relddir123** [processing/processing-android#343]
Whenever I try to use PFont in Android mode, I get the error saying "The class 'PFont' does not exist." I don't understand what's happening here. I could be missing something, but every tutorial I have seen uses PFont like I do (code below) without any errors whatsoever.

```
PFont font;

void setup() {
  font = createFont("Arial Bold", 32);
}
```

There is of course more to the code, but I feel like you don't need to know about stuff not related to the text. If you need the full code, please tell me!

**Comment by codeanticode** [comment]
Sounds like there is a problem with the mode installation, or even with Processing's. PFont should be recognized in both the Java and Android modes, as it is core class.

**Comment by relddir123** [comment]
It's recognized in Java, just not Android. I tested, and the same error comes up for PImage, even though both turn orange upon typing. Do you have any suggestions on how to fix the error?

**Comment by codeanticode** [comment]
What version of the android mode are you using? The one available through the Contributions Manager?

**Comment by relddir123** [comment]
I'm using whatever version was available to download on May 24, 2017 from the download page for Android Mode. I think that's the latest one.

**Comment by codeanticode** [comment]
You mean from this page https://github.com/processing/processing-android/releases ?

**Comment by relddir123** [comment]
As it turns out, I just needed to reconvert from Android to Java and back to Android. And it was from android.processing.org/download.
