### ISSUE TITLE
orientation() isn't recognized

### ISSUE THREAD

**Issue by relddir123** [processing/processing-android#344]
Whenever I use the orientation() function, I get an issue. Whatever I put inside the parentheses (PORTRAIT or LANDSCAPE) isn't recognized as a valid input. Rather, they are recognized as variables that haven't been declared. Please explain to me if there is something else I need to put in my code apart from just the orientation() function. Thank you!

**Comment by codeanticode** [comment]
The PORTRAIT and LANDSCAPE constants are defined both in the Android and Java mode, so don't know why you are getting the error. Maybe you are in a different mode by mistake?

**Comment by relddir123** [comment]
I only have those two modes downloaded. I have no idea what is happening. I've redownloaded Processing entirely thrice (for separate reasons) and no dice.

**Comment by relddir123** [comment]
This got solved along with the PFont issue.
