### ISSUE TITLE
add support for icon-96 for xhdpi icons

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#35]
<a href="https://github.com/nneonneo"><img src="https://avatars.githubusercontent.com/u/75449?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nneonneo](https://github.com/nneonneo)**
_Friday May 24, 2013 at 02:52 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/37_

----

xhdpi resolution is used by default on some devices, e.g. Samsung Galaxy S3. Processing should understand icon-96.png in the data folder, and generate an xhdpi icon from it. Otherwise, we get the generic Processing icon, which is not desirable.

**Comment by codeanticode** [comment]
Added up to xxxhdpi icons (192px) in 3.0.
