### ISSUE TITLE
Crashes if opening a non library file.

### ISSUE THREAD

**Issue by DjTj1539** [processing/processing-android#353]
If you open a file that is not a library  it might not detect that it isn't one.
This happened to me a few times, I accidentely opent a XML file, it couldnt detect it wasnt a non zip file so it crashed. I tried it again with a mp4 file and it did detect.

**Comment by codeanticode** [comment]
This is not an issue related to the android mode. I don't even sure if you can classify it as a bug in the PDE, since you are trying to open a file that is not supported by Processing.
