### ISSUE TITLE
Export Signed Package fails with "The sketch does not include any app icons."

### ISSUE THREAD

**Issue by linux-man** [processing/processing-android#355]
But they exist, and are used on "Run on device". 7 png on sketch folder (icon-32.png to icon-192.png).
Processing 3.3.5, Android 4.0-beta9 on Linux64.

**Comment by codeanticode** [comment]
@linux-man actually, the instructions in the "distributing app" tutorials are wrong, icon-36.png should be listed instead of icon-32.png. Sorry about that!
