### ISSUE TITLE
Processing can't create emulator.

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#37]
<a href="https://github.com/vormplus"><img src="https://avatars.githubusercontent.com/u/805141?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vormplus](https://github.com/vormplus)**
_Friday Jun 07, 2013 at 14:24 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/41_

----

There is a problem when you start a sketch for the first time and have multiple Android APIs installed on your machine. I tried creating the virtual device with the command I found in the Processing console. If there is more than one ABI installed on the machine, you need to specify which one to use. Adding `--abi x86` at the end of this command does create the right virtual device. Sketches can run without a problem now.

This is the output of the terminal:

Cloudswimmers-MBP:tools janvantomme$ ./android create avd -n Processing-0217 -t android-10 -c 64M -s WVGA800
Valid ABIs: armeabi, x86
Error: This platform has more than one ABI. Please specify one using --abi.
Cloudswimmers-MBP:tools janvantomme$ ./android create avd -n Processing-0217 -t android-10 -c 64M -s WVGA800 --abi x86
Android 2.3.3 is a basic Android platform.
Do you wish to create a custom hardware profile [no]n
Created AVD 'Processing-0217' based on Android 2.3.3, Intel Atom (x86) processor,
with the following hardware config:
hw.lcd.density=240
vm.heapSize=24
hw.ramSize=256
Cloudswimmers-MBP:tools janvantomme$

**Comment by codeanticode** [comment]
Solved with https://github.com/processing/processing-android/commit/c9aee98d2267e28586ea7e66284a7a035f91ab8f and others.
