### ISSUE TITLE
Problem with android studio

### ISSUE THREAD

**Issue by MasterYushi** [processing/processing-android#385]
Following [this](http://android.processing.org/tutorials/android_studio/index.html) tutorial to work with processing on android studio I get an error on the line `Fragment fragment = new Sketch();` even though I followed all the steps exactly as mentioned.

![image](https://user-images.githubusercontent.com/24858182/29262338-b38b1b86-80f1-11e7-9aa4-5b25bdb71b11.png)

Here is the sketch class:

```
package masteryushi.fractaltree;

import processing.core.PApplet;

/**
 * Created by Master Yushi on 14-08-2017.
 */

public class Sketch extends PApplet {
	public void settings() {
		size(600, 600);
	}

	public void setup() { }

	public void draw() {
		if (mousePressed) {
			ellipse(mouseX, mouseY, 50, 50);
		}
	}
}
```

**Comment by codeanticode** [comment]
Keep in mind that the first set of instructions apply only when using the processing-core library from version 3.x of the mode. If you are using the core library from a recent beta or the RCs of version 4, use the next set of instructions, in particular:

```
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    FrameLayout frame = new FrameLayout(this);
    frame.setId(ViewIdGenerator.getUniqueId());
    setContentView(frame, 
      new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                                 ViewGroup.LayoutParams.MATCH_PARENT));

    sketch = new Sketch();
    PFragment fragment = new PFragment(sketch);
    fragment.setView(frame, this);
  }
```

The site will be updated to reflect only version 4 once the it is released on the Contributions Manager.
