### ISSUE TITLE
touchStarted() , mouseX and mouseY

### ISSUE THREAD

**Issue by rich-gg** [processing/processing-android#405]
hi there

Running Processing Android with the latest processing-core.jar from within Android Studio
I get strange behavior when I'm trying to catch mouseX and mouseY on touchStarted()

In draw(), I wrote :
`println("TOUCH draw " + mouseX + " - " + mouseY);`
inside a "doOnce" if

In touchStarted(), i wrote 
`println("TOUCH touch " + mouseX + " - " + mouseY);`

And when I touch the screen in my app I get
09-27 16:59:33.863 24895-24911/gg.rich.me.fuzo I/System.out: TOUCH touch 0 - 0
09-27 17:03:01.967 25182-25211/gg.rich.me.fuzo I/System.out: TOUCH draw 1191 - 344
 
09-27 17:03:03.047 25182-25211/gg.rich.me.fuzo I/System.out: TOUCH touch 1191 - 344
09-27 17:03:03.051 25182-25211/gg.rich.me.fuzo I/System.out: TOUCH draw 849 - 511
 
09-27 17:03:04.081 25182-25211/gg.rich.me.fuzo I/System.out: TOUCH touch 849 - 511
09-27 17:03:04.086 25182-25211/gg.rich.me.fuzo I/System.out: TOUCH draw 1206 - 830
...
Each Time I get THE PREVIOUS mouseX and mouseY in touchStarted()

Trying with mousePressed(), I get 
09-27 16:51:38.008 23058-23075/gg.rich.me.fuzo I/System.out: TOUCH mouse 1168 - 349
09-27 16:51:38.016 23058-23075/gg.rich.me.fuzo I/System.out: TOUCH draw 1168 - 349
which is fine

**Comment by codeanticode** [comment]
Thanks, will look into it.

**Comment by hudsonm4000** [comment]
This happens to me too ... so I use touches[0].x etc instead of mouseX

**Comment by codeanticode** [comment]
fixed with https://github.com/processing/processing-android/commit/5dc5a2aafa72c108ab11484c30612084a8839fe1
