### ISSUE TITLE
touches problem?

### ISSUE THREAD

**Issue by hudsonm4000** [processing/processing-android#409]
Not sure whether a bug, but having updated to mode4 I am having some problems with ketai gestures. Some seem to still be fine ... onFlick() and onPinch() for example, but onTap() seems to be broken ... it's as if it is being called twice. Just wondering if the new touchStarted() might be having a conflict if both mode4 and ketai are both calling surfaceTouchEvent(MotionEvent event) ??

Any ideas?

**Comment by codeanticode** [comment]
Ok, need to look into this. Might be related to #405

@danielsauter did you see any of this?

**Comment by hudsonm4000** [comment]
I have created my own tap detector for now but thanks for looking. Re #405 I think that mouseX etc is updated after each draw() cycle so if touches is operating in a separate thread, and mouseX will always be the previous value.

**Comment by hudsonm4000** [comment]
When/how did you try to contact me?
No worries though, if it's a Ketai issue then they should deal with it ... although I also contacted them and had no reply. My workaround is doing the job so it's not a big deal😁

**Comment by codeanticode** [comment]
@hudsonm4000 I guess is that it is a Ketai issue, but may be wrong. Feel free to reopen if still happens with the upcoming 4.0.1 release of the mode and you have reason to think it is due to some bug in processing-core itself.
