### ISSUE TITLE
processing Android problem

### ISSUE THREAD

**Issue by Ermina6** [processing/processing-android#411]
i am a new one in this programming..please help me!!!

I 've got this error:
FATAL EXCEPTION: Animation Thread
Process: processing.test.sketch_dataread_groceries, PID: 3361
java.lang.ArrayIndexOutOfBoundsException: Column 1 does not exist.
	at processing.data.Table.checkColumn(Unknown Source)
	at processing.data.Table.checkBounds(Unknown Source)
	at processing.data.Table.getString(Unknown Source)
	at processing.test.sketch_dataread_groceries.sketch_DataRead_Groceries.setup(sketch_DataRead_Groceries.java:36)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PSurfaceNone.callDraw(Unknown Source)
	at processing.core.PSurfaceNone$AnimationThread.run(Unknown Source)

**Comment by Ermina6** [comment]
please suggest me something..

My code is very simple:

Table groceries;

void setup()
{
  loadTable("groceries.tsv");
  groceries = loadTable("groceries.tsv");                 // 1
  textSize(72);
  rectMode(CENTER);                                       // 2
  textAlign(CENTER, CENTER);                              // 3
  noStroke();
  noLoop();                                               // 4
  background(0);
  int count = groceries.getRowCount();                    // 5

  for (int row = 1; row < count; row++) {
    float rowHeight = height/(count-1);                   // 6
    String amount = groceries.getString(row, 0);          // 7
    String unit = groceries.getString(row, 1);            // 8
    String item = groceries.getString(row, 2);            // 9

    if (groceries.getString(row, 3).equals("store")) {    // 10
      fill(color(255, 110, 50));                          // 11
    } 
    else if (groceries.getString(row, 3).equals("market")) {
      fill(color(50, 220, 255));
    } 
    else {
      fill(127);
    }

    rect(width/2, rowHeight/2, width, rowHeight);         // 12
    fill(255);
    text(amount + " " + unit + " " + item, width/2, rowHeight/2);  // 13
    translate(0, rowHeight);                              // 14
  }
}

**Comment by codeanticode** [comment]
@Ermina6 it sounds like the error is due to a bug in your code... did you check that the tsv file is formatted correctly and has more than 1 column? I would recommend asking this question in the [forum](https://forum.processing.org/two/categories/android) instead, since this GitHub page is primarily meant to discuss the development of the Android mode and the bugs in it.
