### ISSUE TITLE
added NoTitleBar theme by default

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#42]
<a href="https://github.com/redraw"><img src="https://avatars.githubusercontent.com/u/4641572?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [redraw](https://github.com/redraw)**
_Wednesday Nov 20, 2013 at 04:25 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/pull/56_

---

I think that NoTitleBar theme should be set by default, but it's up to you guys

---

_**[redraw](https://github.com/redraw)** included the following code: https://github.com/processing/processing-android-archive/pull/56/commits_

**Comment by codeanticode** [comment]
The default theme is noww Theme.AppCompat.Light.NoActionBar.FullScreen, so this issue has been addressed.
