### ISSUE TITLE
Pausing/restoring sketch erases view's contents

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#424]
This affects both Android2D and OpenGL renderers.

**Comment by rich-gg** [comment]
anything to do with loss of Context ?

**Comment by codeanticode** [comment]
No, I think it has more to do with the Android system clearing the surface view automatically after sending the activity to the background. I got a fix already, but need to do some more testing before pushing it, since the fix is slightly different between the JAVA2d and P2D/P3D renderers. I got into this issue from looking at #413, and I'm realizing that some aspects of the activity lifecycle need to be better handled in Processing more generally. So working on it :-)

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/85062a55d9bf51f0056abeff45aedb5d3f1011ba
