### ISSUE TITLE
AndroidManifest "android:debuggable=true" in the exported one.

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#43]
<a href="https://github.com/redraw"><img src="https://avatars.githubusercontent.com/u/4641572?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [redraw](https://github.com/redraw)**
_Thursday Nov 21, 2013 at 17:09 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/57_

---

When exporting the Android Application AndroidManifest.xml doesn't set debug to false, and fails when uploading it to Google Play after signing the apk.

I think it should be modified or commented in the Wiki. I wish I could do that, but I don't even know if the Manifest.java applies to the default or the exported file.

**Comment by ZachSundberg** [comment]
Ran into this today.  The only way around it for now is to edit the AndroidManifest.xml in the \android folder that gets created when you export, before your run ant release.

**Comment by codeanticode** [comment]
Thanks for the heads up, this will be solved during the transition to gradle #307

**Comment by codeanticode** [comment]
The android:debuggable=true property is no longer added to the manifest file.
