### ISSUE TITLE
Suggestion for Table and TableRow

### ISSUE THREAD

**Issue by EdvinAkerstrom** [processing/processing-android#439]
At the moment the only implementation of `Table.insertRow` is as follows:
`void Table.insertRow(int, Object[])`

I suggest the implementation of the following methods for continuity:
**TableRow**:
- `Object[] TableRow.getValues()`

**Table**:
- `void Table.insertRow(int, TableRow)`
- `void Table.insertRows(int, Table)`

This is due to the following already implemented methods:
**Table**:
- `Table.addRow(TableRow)`
- `Table.addRows(Table)`

**Comment by codeanticode** [comment]
@ShadowNinja44 Thanks for your suggestion to extend the data API. Since we try to keep the APIs in Processing and Processing Android in synch, you should bring this up in the Processing repo.
