### ISSUE TITLE
is it possible to access to the fingerprint scanner?

### ISSUE THREAD

**Issue by erwrow** [processing/processing-android#444]
i think that the title is very specific

**Comment by codeanticode** [comment]
Looks like it is possible, see [here](https://www.androidauthority.com/how-to-add-fingerprint-authentication-to-your-android-app-747304/). However, this is not really an issue reporting a bug or enhancement request, so I will close it. You can continue the discussion on how to use the fingerprint scanner on the [Forum](https://forum.processing.org/two/categories/android).
