### ISSUE TITLE
onActivityResult is never called after startActivityForResult

### ISSUE THREAD

**Issue by tms-martins** [processing/processing-android#452]
For activities like turning on Bluetooth or picking a contact, developers must call `startActivityForResult`, and handle the result in `onActivityResult`.

In the following snippet, tapping the screen starts an activity to pick a contact. The system's contact picker appears, a contact can be selected (or the process cancelled), returning to the app. However, the overridden method `onActivityResult` never seems to be called.

(it also seems that `mousePressed()` isn't called if there is no `draw()` function)

Processing 3.3.6
Android Mode 4.0.1
Tested on: 
* Motorola Moto G2, Android 6.0.0 (original rom)
* Motorola Moto G2, Android 7.1.2 (custom rom) 
* Huawei P Smart, Android 8.0.0 (original rom)

``` java
public static final int PICK_CONTACT = 57291;

void mousePressed() {
  println("mousePressed()");
  pickContact();
}

void pickContact() {
  println("pickContact()");
  Intent intent = new Intent(Intent.ACTION_PICK, ContactsContract.Contacts.CONTENT_URI);
  intent.setType(Phone.CONTENT_TYPE);  //should filter only contacts with phone numbers
  super.getActivity().startActivityForResult(intent, PICK_CONTACT);
}

@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
  println("onActivityResult() for code <" + requestCode + ">"); 
  super.onActivityResult(requestCode, resultCode, data);
}
```

**Comment by kfrajer** [comment]
> (it also seems that mousePressed() isn't called if there is no draw() function)

You need to provide an empty draw (at a minimum) for Processing events to be handled at all. Try with `draw(){ }` and see if it fixes your current problem.   I suggest you check the implementation of B2 in the Ketai library. There is an example there, or check Ketai.org

Kf

**Comment by tms-martins** [comment]
Thanks! I didn't post the complete sketch, but it does have an empty-bodied `draw()` as you suggested.
So, to clarify, `mousePressed()` **does** get called, and **so does** `pickContact()`.
The main issue persists, i.e., `onActivityResult()` doesn't seem to be called afterwards.

**Comment by codeanticode** [comment]
I can reproduce this issue, thanks. I think the solution is to add the implementation of onActivityResult(int requestCode, int resultCode, Intent data) to the template main activity, so it calls the corresponding method in PApplet (remember that PApplet itself is not an activity).

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/f452ad6895a2fee2be044de3461ca6974d2ed506
