### ISSUE TITLE
Chash when installing libraries in APDE

### ISSUE THREAD

**Issue by TheUltimateKrtek** [processing/processing-android#456]
Processing for Android crashes when importing a compressed library.
Message after opening processing again: Error occurred restoring state, likely caused by a crash in an activity further down the hierarchy

**Comment by kfrajer** [comment]
Shouldn't this be posted in APDE instead: https://github.com/Calsign/APDE/issues

Kf

**Comment by TheUltimateKrtek** [comment]
I guess. I am going to repost it. How do I delete the post?

**Comment by TheUltimateKrtek** [comment]
I though, this is the place, I did't find APDE in the list

**Comment by codeanticode** [comment]
@TheUltimateKrtek I see you opened the issue in the APDE repo https://github.com/Calsign/APDE/issues/38, so I will close it here.
