### ISSUE TITLE
updatePixels() makes image completely transparent in android mode.

### ISSUE THREAD

**Issue by Electric-Coke** [processing/processing-android#463]
Calling updatePixels() on an image after calling loadImage() makes the image completely transparent.
I just found this when i tried to copy mo project from java mode to android mode.

Image is shown:
`sky = loadImage("sky.jpg");`
`image(sky, 0, 0);`

Image is not shown:
`sky = loadImage("sky.jpg");`
`sky.updatePixels();`
`image(sky, 0, 0);`

In java mode the image would show either way.

**Comment by dzaima** [comment]
Quote from https://processing.org/reference/updatePixels_.html:

> Certain renderers may or may not seem to require loadPixels() or updatePixels(). However, the rule is that any time you want to manipulate the pixels[] array, you must first call loadPixels(), and after changes have been made, call updatePixels(). Even if the renderer may not seem to use this function in the current Processing release, this will always be subject to change.

**Comment by Electric-Coke** [comment]
Ahh. I understood it as that you had to call `loadPixels` for safety after `loadImage`, and thought it was a bug in this case, but I understand what it is for now.
Thanks.
