### ISSUE TITLE
Problems with the emulator across platforms?

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#467]
Testing the emulator with the latest release (4.0.2) and also the previous one, it seems that the emulator hangs during startup on Linux, Windows, and Mac. Need to do further testing.

**Comment by q2dg** [comment]
If it helps, I offer myself as a tester.

_I use Processing Android 4.0.2 in Fedora 28 x86-64 with Android SDK installed by default options  (that is, I haven't touched anything by hand; everything has installed through popups offered by Processing). My problem is "Lost connection with emulator while launching. Try again". I'm using x86 emulator instead of ARM's one._

**Comment by codeanticode** [comment]
@q2dg Thanks a lot! Yes, need to look into that "Lost connection" error, I have seen it popping up from time to time.

**Comment by codeanticode** [comment]
The situation might not be as hopeless as I originally thought. Tested the emulator on Mac, Windows, and Linux using the most recent versions of Processing and the Android mode (3.5.3 and 4.0.4, respectively) and I was able to install and the sketch in the emulator on the first two. Installation fails on Linux with the following error:

```
Emulator process exited with status 1.
EmulatorController: Emulator never booted. NOT_RUNNING
Error while starting the emulator. (NOT_RUNNING)
```

**Comment by codeanticode** [comment]
Tested emulator with latest version of the mode, 4.2.1. It works on Linux (Ubuntu 20.04) and macOS Catalina (although HAXM authorization fails in the latter). It doesn't work on Windows 10 (with the error EmulatorController: Emulator never booted. NOT_RUNNING, Error while starting the emulator. (NOT_RUNNING))

**Comment by BUZDOLAPCI** [comment]
> Tested emulator with latest version of the mode, 4.2.1. It works on Linux (Ubuntu 20.04) and macOS Catalina (although HAXM authorization fails in the latter). It doesn't work on Windows 10 (with the error EmulatorController: Emulator never booted. NOT_RUNNING, Error while starting the emulator. (NOT_RUNNING))

Running Processing with Admin rights seems to fix this issue for me, not sure if it's the same case with you.

**Comment by codeanticode** [comment]
Ok, thanks for the info. I'd say that running as admin could be useful as a workaround, but the emulator should run without requiring it :-)

**Comment by codeanticode** [comment]
Using the ```--skin``` argument (https://github.com/processing/processing-android/commit/806def28a1dfe4bdba9d1714f4bab04dc493450b) and with recent device art pulled from Android Studio (https://github.com/processing/processing-android/commit/e254f20063265ca6646692a887bb1d2b8e51cbcd, https://github.com/processing/processing-android/commit/2ad6507e2e81179fb4c7ddf23f2caae2e5d30bce) seems to solve most of the issues with the emulator
