### ISSUE TITLE
Processing 2.1.1  error 542: Unable to resolve project target

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#47]
<a href="https://github.com/KBEAST"><img src="https://avatars.githubusercontent.com/u/6701175?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KBEAST](https://github.com/KBEAST)**
_Monday Feb 17, 2014 at 04:33 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/61_

---

Hi,

I am running the sample, and I am getting below error.
All my tools are latest and eclipse is working with Android SDK with the latest on my window 7 64bit. But I still can't get Processing to work on Android mode with this latest version. 

Thanks for the help :)

-set-mode-check:

-set-debug-files:

-check-env:
Android SDK Tools Revision 22.3.0
Installed at C:\Program Files (x86)\Android\android-sdk\adt-bundle-windows-x86_64-20131030\sdk

-setup:
     [echo] Project Name: Planets
Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
Using latest Build Tools: 19.0.1
     [echo] Resolving Build Target for Planets...

BUILD FAILED
C:\Program Files (x86)\Android\android-sdk\adt-bundle-windows-x86_64-20131030\sdk\tools\ant\build.xml:542: Unable to resolve project target 'android-10'

Total time: 0 seconds

**Comment by Stoyz** [comment]
Is there another way to make it usable? Like changing to an earlier version (API 20 for example)?
