### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by namanpreetsingh** [processing/processing-android#472]
I went through Building Processing for Android document and followed up the steps which lead to this error - 

* Where:
Build file '/home/naman/processing-android/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'processing-android'.
> Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

On Using ./gradlew dist command, the error was- 
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':core:compileClasspath'.
> Could not find :android:.
  Searched in the following locations:
      file:/home/naman/Android/Sdk/platforms/android-26/android-.jar
      file:/home/naman/Android/Sdk/platforms/android-26/android.jar
      file:/home/naman/Android/Sdk/tools/lib/android-.jar
      file:/home/naman/Android/Sdk/tools/lib/android.jar
      file:/home/naman/processing-android/core/dist/android-.jar
      file:/home/naman/processing-android/core/dist/android.jar
  Required by:
      project :core

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by codeanticode** [comment]
@namanpreetsingh What version of the Android SDK you have installed? You need Android 26 in order to build Processing for Android (that should be noted in the wiki), alternatively you can edit the root build.gradle and set the global variable ext.targetSdkVersion to the version you want to use. Let me know if this solves the problem

**Comment by namanpreetsingh** [comment]
After setting up Android SDK 26 and running gradle dist command, the error was-
FAILURE: Build failed with an exception.

* Where:
Build file '/home/naman/processing-android/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'processing-android'.
> Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.578 secs

and on importing the project into IntelliJ IDE,  and following **Go to File > Project Structure > Modules > Add > Import Module > Select Processing-Android folder > Import module from external model (Eclipse) > Select all projects** to import the project, the error was - 

Unknown modules detected
processing-core
processing-app
processing-java

After adding path variables, setting up VM, and running the project, the error was -

Error: Could not find or load main class Base (processing.app)

Process finished with exit code 1

**Comment by codeanticode** [comment]
Are you using a version of Gradle lower than 4.1? google() is Google's Maven repository, but according to the official docs:

https://developer.android.com/studio/build/dependencies

```gradle
allprojects {
    repositories {
        google()

        // If you're using a version of Gradle lower than 4.1, you must instead use:
        // maven {
        //     url 'https://maven.google.com'
        // }
        // An alternative URL is 'https://dl.google.com/dl/android/maven2/'
    }
}
```

With regards to IntelliJ, remember to clone the [processing repo](https://github.com/processing/processing) to get access to the processing-app, java, and core projects.

**Comment by namanpreetsingh** [comment]
@codeanticode  After updating gradle, setting up processing repo, importing everything in IntelliJ IDE, only error I get is when I run the project, i.e,
Error: Could not find or load main class Base (processing.app)
Any suggestions on how it can be resolved and what is the cause?

**Comment by codeanticode** [comment]
Did you apply step 3 in the wiki?

> 3. Goto Run > Edit Configurations and create a new Application configuration.
> i. Set “Main class” to “Base (processing.app)”
> ii. And “Use classpath of module” to “processing-app”

Make sure that you run the processing-app project (which contains the PDE), not processing-core or processing-java.

**Comment by namanpreetsingh** [comment]
@codeanticode  Yes, I've applied Step 3 but I have a doubt that whether the Main Class is to be set just by writing "Base (processing.app)", or a file needs to be selected from the project? If so, then can you please tell me where to find that file? 
I am running processing-app project.

**Comment by codeanticode** [comment]
Actually, I'm not 100% sure as I'm not using IntelliJ. @rupak0577 should be able to answer this question, he wrote the original tutorial including the steps for IntelliJ.

**Comment by codeanticode** [comment]
Great, thanks for the update. I'm glad it finally worked for you! (and added the requirement for Gradle 4.1 to the wiki's installation guide)
