### ISSUE TITLE
PGraphics.clear() doesn't seem to be working on android

### ISSUE THREAD

**Issue by Talma18** [processing/processing-android#484]
I was playing around with some sketches when i noticed the method wasn't working. I made this test sketch, but it didn't clear here either. I get _no_ error messages.

```
PGraphics pg;
void setup() {
  size(300,300);
  pg = createGraphics(100,100);
}
void draw() {
  background(20);
  pg.beginDraw();
  pg.clear();
  pg.rect(random(80),random(80),20,20);
  pg.endDraw();
  image(pg,100,100);
}
```

**Result:**
![screenshot_20180810-121527](https://user-images.githubusercontent.com/11366635/43952800-4647a220-9c97-11e8-8b66-cbfb8dc95631.jpg)

**Ps.:** I'm pretty new to programming so i might just be missing something really silly, but i haven't been able to find it.

**Comment by dzaima** [comment]
`clear` [seems to call](https://github.com/processing/processing-android/blob/03c2efe45a06f7e32f9e89ba63479f28935e0f8f/core/src/processing/core/PGraphics.java#L4977) `background(0, 0, 0, 0);` - setting the background to black with alpha 0 (aka transparent).

Despite [this comment](https://github.com/processing/processing-android/blob/03c2efe45a06f7e32f9e89ba63479f28935e0f8f/core/src/processing/core/PGraphics.java#L4965-L4968) just above, it does seem to partially clear the graphic (or in this case, not at all, resulting in 0 difference from before).

A simple workaround would be to instead do `pg.background(0);`, or use the P2D renderer (adding a `P2D` as another argument in both `size` and `createGraphics`)

**Comment by Talma18** [comment]
But i need to graphic to be transparent, so `pg.background(0);` won't work here ( nor does `pg.background(0,0);`, tested ) and switching to OpenGL didn't seem to change anyting, apart from giving an error message (_OpenGL error 1280 at bot beginDraw(): invalid enum_);

**Comment by dzaima** [comment]
The error message seems to be there always when using an OpenGL renderer, but I never have had any problems with that except it being annoying.

```java
PGraphics pg;
void setup() {
  size(300,300,P2D);
  pg = createGraphics(100,100, P2D);
}
void draw() {
  background(256,0,0);
  pg.beginDraw();
  pg.clear();
  pg.rect(random(80),random(80),20,20);
  pg.endDraw();
  image(pg,100,100);
}
```

I get only one rectangle per frame, and the background always stays red, indicating that transparency is working.

**Comment by Talma18** [comment]
I haven't put P2D inside createGraphics, but it's working perfectly now. 
Thank you.

**Comment by codeanticode** [comment]
@Talma18 the clear() function sets the opacity to zero, as @dzaima pointed out. The last code snippet works as expected, so I'm closing this issue. Feel free to post updates if you find any other problems with this function. Thank you!
