### ISSUE TITLE
Getting Base64Encoder deprecated API

### ISSUE THREAD

**Issue by ghhann** [processing/processing-android#496]
<img width="683" alt="capture" src="https://user-images.githubusercontent.com/40902381/46232884-b8c35d80-c33e-11e8-8580-23b70e46e92d.PNG">

Getting the above error in both the Master Branch and AR branch
Using windows 10, using gradle all the latest versions

**Comment by codeanticode** [comment]
Ok, thanks for the heads up. Before it would give a warning, but if this API was finally removed from Java, then is time to find an alternative...

**Comment by codeanticode** [comment]
Upon closer examination, I found that there is a public Base64 Encoder/Decoder in java 8:

https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html

However, the PKCS7 encoding classes appear to be available [only for internal use](https://security.stackexchange.com/questions/13910/pkcs7-encoding-in-java-without-external-libs-like-bouncycastle-etc), and only an external crypto library such as [Bouncy Castle](http://bouncycastle.org/java.html) would enable such encoding without any errors or warnings.

**Comment by codeanticode** [comment]
No longer needed as the mode uses gradle to create the packages and bundles.
