### ISSUE TITLE
println not showing up in the console

### ISSUE THREAD

**Issue by clankill3r** [processing/processing-android#504]
`println` is not showing up in the console for me.
For the rest I can create apps fine.

android 7.0

**Comment by clankill3r** [comment]
Ok I got it.
I have to dial a number and set logging on.
And don't reboot.
Here more info:

https://stackoverflow.com/questions/18124334/huawei-logcat-not-showing-the-log-for-my-app

I leave the issue open in case it is possible to detect which phones are affected by this or make a not in the docs or whatever.

**Comment by codeanticode** [comment]
@clankill3r thanks a lot for posting the solution to this issue! I will add a note about it in an upcoming tutorial about debugging.
