### ISSUE TITLE
A proper way to go to 2D in VR Mode

### ISSUE THREAD

**Issue by clankill3r** [processing/processing-android#505]
I had problems getting into 2D in VR mode.

Before I used the `eye` method:
https://android.processing.org/reference/vr/eye.html

But then with:

 ```
eye();
translate(-width/2, -height/2, 1350);
```
This was guessing and isn't perfect (and only works for my phone I guess).

What I did now was:

```java
void setup() {
  fullScreen(P3D);
  orientation(LANDSCAPE);    
}

void draw() {
}

void touchStarted() {
  printMatrix();
}
```
This prints the matrix for me.

Then in my VR sketch I use:

```java
      resetMatrix();
      
      applyMatrix(
       001.0000,  000.0000,  000.0000, -960.0000,
       000.0000,  001.0000,  000.0000, -540.0000,
       000.0000,  000.0000,  001.0000, -935.3074,
       000.0000,  000.0000,  000.0000,  001.0000
       );
```

This works much better.
But I feel like there should be something build in to go from VR view to a 2D view to draw GUI elements etc.
Also this only works for LANDSCAPE and my aspect / resolution I guess..

**Comment by clankill3r** [comment]
I got it.

I think something like this should be in the android mode by default:

```java
void begin_2d() {
  hint(ENABLE_DEPTH_SORT);
  pushMatrix();
  resetMatrix();
  ortho(0, width, -height, 0, MIN_FLOAT, MAX_FLOAT);
}

void end_2d() {
  popMatrix();  
  hint(DISABLE_DEPTH_SORT);
}
```

**Comment by codeanticode** [comment]
Thanks for your comments! I think it is hard to set a default that would work for everyone. However, since the main use of VR is to display 3D objects, I'd imagine most users would expect to get a 3D perspective by default. 

Regardless of that, your code snippet should come handy to other people wanting to add 2D elements to a VR scene. My only suggestion would be to use DISABLE/ENABLE_DEPTH_TEST instead of DEPTH_SORT, since the result should be the same (I believe), but disabling the depth test is a more efficient way to do it (depth sorting sorts all the triangles in the scene, which can be costly if you drawing many complex shapes).

**Comment by clankill3r** [comment]
@codeanticode there is another problem with this, maybe you know what it is.


```java
void setup() {
  size(600, 600, P3D);
}


void draw() {
  background(0);

  noStroke();
  fill(255, 0, 0);
  translate(width/2, height/2);
  rotateX(random(PI));
  rotateY(random(PI));
  rotateZ(random(PI));
  box(150);

  if (!true) {
    begin_2d();
    stroke(255, 255, 0);
    line(0, 0, width, height);
    end_2d();
  }
}


void begin_2d() {
  hint(ENABLE_DEPTH_TEST);
  pushMatrix();
  resetMatrix();
  ortho(0, width, -height, 0, MIN_FLOAT, MAX_FLOAT);
}

void end_2d() {
  popMatrix();  
  hint(DISABLE_DEPTH_TEST);
}
```
Enable the if scope close before the begin_2d.
Now the box will move.

I think this is because `resetMatrix` is making a call to `projmodelview.set(projection);`

**Comment by clankill3r** [comment]
same with this

```java

void begin_2d() {
  hint(ENABLE_DEPTH_TEST);
  pushMatrix();
  applyMatrix(1.0000, 0.0000,  0.0000,  0.0000,
              0.0000, 1.0000,  0.0000,  0.0000,
              0.0000, 0.0000,  1.0000,  0.0000,
              0.0000, 0.0000,  0.0000,  1.0000);

  ortho(0, width, -height, 0, MIN_FLOAT, MAX_FLOAT);
}

void end_2d() {
  popMatrix();  
  hint(DISABLE_DEPTH_TEST);
}
```
