### ISSUE TITLE
Cache buffer keeps expanding 

### ISSUE THREAD

**Issue by HansAMpaD** [processing/processing-android#506]
Upgraded to 4.0.3. Found that Bepdroid doesn't compile anymore... :'(. Now also ran into the problem that, even with the example sketch, the cache buffer expands every time the sketch runs on my device. It easily exceeds 1GB. Searched for clearing the buffer programmatically but the solution won't work, seems for older versions.

**Comment by HansAMpaD** [comment]
Got a reaction from another user, he had the same experience. Back to Android mode 4.0.2. is for now the only solution to prevent overloading the cache.

**Comment by codeanticode** [comment]
Hi, could you provide some more detail about this issue? I haven't experienced any memory management problems with 4.0.3, if anything, it should use less resources than previous versions (eg.: see issues #483 and #482). What's the cache buffer you are referring to? Thank you!

**Comment by HansAMpaD** [comment]
Hi, thanks for the response. I also discussed this in the Processing
Android forum. A few others reported same experience. Made the simple
example sketch. After installing it's approximately 7mb. Each time you run
the sketch the buffer expands. Made some screenshots, see attachments.
Total size on the device keeps growing.

I also very much appreciate it when Blepdroid would work again. Updating
previous build, or new,  BLE sketches isn't possible any more. Don't see
other Buetooth Low Energie possibilities.

Thanks again for all good work.

Greetings Hans

Op ma 24 dec. 2018 09:14 schreef codeanticode <notifications@github.com:

**Comment by codeanticode** [comment]
Ok, got it, I think this is caused by the fix for  #482, which creates a temporary file to save the screen pixels... I thought it would be automatically deleted, but looks like I was wrong in my assumption :-) Will fix this regression asap!

**Comment by HansAMpaD** [comment]
Okay, thanks. 
Do you expect a workaround for Blepdroid soon?

**Comment by codeanticode** [comment]
Actually, there are two different issues here:

- the cache buffer expansion, which I believe is caused by the regression from issue 482, although I'm not 100% sure. Does the buffer expansion happen only with sketches using the P2D/P3D renderers, or with any renderer?

- Bepdroid not compiling anymore, is that related to the buffer expansion in any way? If not, we should put it in a separate issue.

**Comment by HansAMpaD** [comment]
In my original sketch, where I first noticed that behavior, I was using P2D because circles and text weren’t smooth. To make sure that I didn’t make any other programming mistake I used the example sketch (https://android.processing.org/tutorials/getting_started/index.html). I don’t see P2D/P3D in that example. The previous sent screenshot came from that sketch.  

 

True, my apologies. Thought that items, like Blepdroid, not working anymore already had your attention. Looks like a Fragment layout error. Because I’m not that experienced I was hoping for a workaround. For me a Android device listening and talking to Arduino over BLE has a great added value. Do you see it as an issue or more like a request?  

 

Van: codeanticode <notifications@github.com>
Beantwoorden - Aan: processing/processing-android <reply@reply.github.com>
Datum: dinsdag 25 december 2018 om 01:59
Aan: processing/processing-android <processing-android@noreply.github.com>
CC: HansAMpaD <jhvos01@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [processing/processing-android] Cache buffer keeps expanding (#506)

 

Actually, there are two different issues here:
the cache buffer expansion, which I believe is caused by the regression from issue 482, although I'm not 100% sure. Does the buffer expansion happen only with sketches using the P2D/P3D renderers, or with any renderer?
Bepdroid not compiling anymore, is that related to the buffer expansion in any way? If not, we should put it in a separate issue.

**Comment by codeanticode** [comment]
No worries! 

Yes, now I remember the thread on Bepdroid, I thought I added back some API to PApplet so older libraries such as Bepdroid could still work with the latest version of the mode. Otherwise, the library maintainers would need to update it. I will take another look at it.

Regarding the cache size issue, I don't see any screenshot in this thread, could you re-post it?

**Comment by HansAMpaD** [comment]
![screenshot_20181118-135301_settings](https://user-images.githubusercontent.com/30293062/50420085-ab7e1800-0834-11e9-8b57-b3349a50911a.jpg)
![screenshot_20181118-135529_settings](https://user-images.githubusercontent.com/30293062/50420093-b5a01680-0834-11e9-8931-5f57542dac3f.jpg)
![screenshot_settings_opening20x](https://user-images.githubusercontent.com/30293062/50420097-bc2e8e00-0834-11e9-974f-c308f68bc668.jpg)

hope this works

**Comment by HansAMpaD** [comment]
The last screenshot was after opening and closing some 20 times. My original sketch was graphical heavier so it easily went over 1Gb.

Great if you can find time to look into Blepdroid, I don't mind to go back to previous Android mode but that also produced lots of errors. A workaround to easily switch modes would be sufficient for now (but probably also not that simple I guess ;-) ).

**Comment by codeanticode** [comment]
Ok, I can confirm it. It's obviously a critical issue, so I will fix and upload an update shortly. Thanks a lot for providing the debugging information!

**Comment by codeanticode** [comment]
The cache expansion bug should be solved with this commit https://github.com/processing/processing-android/commit/42b38661bd78ee55eb94da54c62d5933d12d7f22

**Comment by codeanticode** [comment]
@HansAMpaD Regarding the issues with the blepdroid library, please check this other issue: #507
