### ISSUE TITLE
Sketches don't work properly the second time (BUG?)

### ISSUE THREAD

**Issue by Darklod** [processing/processing-android#514]
The second time I run the sketch something goes wrong. 
I tried both with the emulator and with my phone (Xiaomi Redmi Note 5 - Android 8.1.0) and both don't work. (minSdkVersion 21, targetSdkVersion 26) 

I'm using a MainActivity in which I choose the sketch to launch and an other one RunSketchActivity for start the sketch.
I pass the sketch to the RunSketchActivity as a static variable and put it in a PFragment like in the example.
For this reason in the manifest i have only one activity for all the sketches.

When debugging, on my phone i got the error below, but not on the emulator. 

E/BufferQueueProducer: [SurfaceView - com.darklod.app/com.darklod.app.RunSketchActivity#0] disconnect: not connected (req=2)
E/SurfaceFlinger: Failed to find layer (SurfaceView - com.darklod.app/com.darklod.app.RunSketchActivity#0) in layer parent (no-parent).
E/SurfaceFlinger: Failed to find layer (Background for - SurfaceView - com.darklod.app/com.darklod.app.RunSketchActivity#0) in layer parent (no-parent).
E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
E/ActivityTrigger: activityStartTrigger: not whiteListedcom.darklod.app/com.darklod.app.RunSketchActivity/1
E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.darklod.app/com.darklod.app.RunSketchActivity/1
E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.darklod.app/com.darklod.app.RunSketchActivity/1

Here's the Kotlin code:
   
    companion object {
        var sketch: PApplet? = null
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_sketch)

        val frame = FrameLayout(baseContext)
        frame.id = CompatUtils.getUniqueViewId()

        setContentView(
            frame, ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT
            )
        )

        val fragment = PFragment(sketch)
        fragment.setView(frame, this)
    }

    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
        if (sketch != null) {
            sketch?.onRequestPermissionsResult(
                requestCode, permissions, grantResults
            )
        }
    }

    public override fun onNewIntent(intent: Intent) {
        if (sketch != null) {
            sketch?.onNewIntent(intent)
        }
    }

The Sketch:

    override fun settings() {
        fullScreen()
    }

    override fun setup() {
        background(0)
        fill(255)
    }

    override fun draw() {
        stroke(255)
        line(0f, 0f , displayWidth.toFloat(), displayHeight.toFloat())
        if (mousePressed) {
            ellipse(mouseX.toFloat(), mouseY.toFloat(), 50f, 50f)
        }
    }

And the two images (the first time, the second time):
![screenshot_1547332741](https://user-images.githubusercontent.com/19750893/51079450-9ffd6e80-16c7-11e9-9f95-7673b0327abc.png)

**SOLUTION**

[Here's my repo](https://github.com/Darklod/SketchesApp)

Create a superclass of PApplet and implements the Serializable interface.

`class Sketch : Serializable, PApplet()`

In the activity that will call the RunSketchActivity pass the sketch in the intent.
```
val intent = Intent(applicationContext, RunSketchActivity::class.java)
intent.putExtra("sketch", item)
startActivity(intent)
```
And in the RunSketchActivity get the sketch from the intent.
```
private lateinit var sketch : Sketch

override fun onCreate(savedInstanceState: Bundle?) {
      super.onCreate(savedInstanceState)
      sketch = intent.getSerializableExtra("sketch") as Sketch
}
```

**Comment by codeanticode** [comment]
The [main repo](https://github.com/processing/processing-android/tree/master/studio) includes some Android Studio projects for debugging, very similar to your code (in Java though). I haven't seen the error you are reporting, but maybe there are other aspects in your project that are causing the problem or triggering a bug in processing-core. Can you post your entire Kotlin project (a stripped down version should be enough) so I can test myself?

As for the difference in the output between the first and second time your run your sketch, this is probably related to the fact that you are clearing the screen in setup(), which means that if the sketch is resumed the second time (meaning that setup is not called again) then the background is not set to black. But not sure if this is the case, that's why seeing the entire project would help. Thank you!

**Comment by Darklod** [comment]
I put it on a repo: https://github.com/Darklod/SketchesApp

**Comment by codeanticode** [comment]
Cool, thanks. I was able to load and run the project, will take a look at the issue.

**Comment by Darklod** [comment]
I just notice that in the wiki the SDK version should be API 26. I decreased to 26 and still nothing, the problem persist D:

**Comment by codeanticode** [comment]
I think the problem is related to how the Processing fragments are handled in by the main activity, but could not look yet look in detail into it.

**Comment by Darklod** [comment]
You was right! I solved removing the static variable and pass the sketch in the intent. 
Now I get the sketch in the onCreate event. I think it might have been a problem of instances due the static. I'll update the above code. 
I still have problem with orientation, but this is another issue.

**Comment by dzaima** [comment]
If I recall correctly, exiting a processing app doesn't _actually_ exit it, it leaves something running which keeps static fields around, so restarting the app after that would cause problems. Very strange, as I'd expect exiting an app to exit from the app..
