### ISSUE TITLE
OpenGL ES 3.0 and glsl 3.0 es shader support

### ISSUE THREAD

**Issue by scudly** [processing/processing-android#515]
Does Processing for Android have support for OpenGL es 3 and `#version 300 es` shaders? If so, how do we enable it?

Desktop Java Processing seems to run version 3 shaders just fine even without adding `PJOGL.profile = 3;` as I’ve seen posted in a few places. Maybe it detects the version and makes that setting on its own?

Running a 3.00 ES shader on Android, however, gives `Error: shader version mismatch.`

**Comment by codeanticode** [comment]
With commit  https://github.com/processing/processing-android/commit/be27f88cfcdd7885a48f1b8bbd03d4a1e2db039f I added a PGLES.version field with the same interpretation as PJOGL.profile, which it is set by default to 2 but you can manually increase to 3 if desired. However, it seems that if the device supports ES 3, an ES 3 context is automatically created even if one requests 2, so this addition might be of not much use. Tested on one single phone thou.
