### ISSUE TITLE
Copy parameters are reversed.

### ISSUE THREAD

**Issue by JackWitherell** [processing/processing-android#519]
Version 4.0.4 of the mode

According to processing's reference,
`copy(sx, sy, sw, sh, dx, dy, dw, dh)`
is meant to take the region of the screen designated by a rect with the position of `sx, sy` and a size of `sw, sh` and copy it over to `dx, dy` with a size of `dw, dh`

In processing for android version 4.0.4, the order of parameters are
`copy(dx, dy, dw, dh, sx, sy, sw, sh)`

Demo code

```java
void setup(){
  fullScreen();
  background(0);
  point(30,height-1);
}

void draw(){
  stroke(color(random(255),random(255),random(255)));
  point(random(width),height-1);
  copy(0,1,width,height-1,0,0,width,height-1);
  //copy(0,0,width,height-1,0,1,width,height-1); //fix for android
}
```

**Comment by codeanticode** [comment]
Thanks for the bug report. I can confirm this happens with the default renderer. Also, no output is generated when one uses the OpenGL renderer, either with the original order of parameters, or with the fix. So this may be pointing to another bug.

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/dbacaba1fb36e63e13c254501448b32fe0e683d3
