### ISSUE TITLE
Unable to run on device; stuck compiling

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#52]
<a href="https://github.com/GaryHomewood"><img src="https://avatars.githubusercontent.com/u/671408?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GaryHomewood](https://github.com/GaryHomewood)**
_Saturday May 17, 2014 at 12:54 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/67_

----

Hi
I am unable to get a sketch running on Android.

Using Processing 2.2 on OSX 10.9.2
Installed Java SE 7u55 from Oracle, and I have followed previous issues to set up javac in /Applications/Processing.app/Contents/PlugIns/jdk1.7.0_55.jdk/Contents/Home/jre/bin/

javac -version shows 1.7.0_55  

Android 4.4.2 phone is set up for USB debugging

When I try "run on device" I get the following output, it gets stuck "Compiling 3 source files" and nothing appears on the phone.

-set-mode-check:

-set-debug-files:

-check-env:
Android SDK Tools Revision 22.6.3
Installed at /Applications/Android Studio.app/sdk

-setup:
     [echo] Project Name: sketch_140517a
Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
Using latest Build Tools: 19.0.3
     [echo] Resolving Build Target for sketch_140517a...
Project Target:   Android 2.3.3
API level:        10
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /var/folders/zh/bm23rpxx1ljfs0tlvghz9zzr0000gn/T/android2295280901380018275sketch/bin
    [mkdir] Created dir: /var/folders/zh/bm23rpxx1ljfs0tlvghz9zzr0000gn/T/android2295280901380018275sketch/bin/res
    [mkdir] Created dir: /var/folders/zh/bm23rpxx1ljfs0tlvghz9zzr0000gn/T/android2295280901380018275sketch/bin/rsObj
    [mkdir] Created dir: /var/folders/zh/bm23rpxx1ljfs0tlvghz9zzr0000gn/T/android2295280901380018275sketch/bin/rsLibs
    [mkdir] Created dir: /var/folders/zh/bm23rpxx1ljfs0tlvghz9zzr0000gn/T/android2295280901380018275sketch/gen
    [mkdir] Created dir: /var/folders/zh/bm23rpxx1ljfs0tlvghz9zzr0000gn/T/android2295280901380018275sketch/bin/classes
    [mkdir] Created dir: /var/folders/zh/bm23rpxx1ljfs0tlvghz9zzr0000gn/T/android2295280901380018275sketch/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for sketch_140517a...
Library dependencies:
No Libraries

------------------
API<=15: Adding annotations.jar to the classpath.
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
Merging AndroidManifest files into one.
Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 3 source files to /var/folders/zh/bm23rpxx1ljfs0tlvghz9zzr0000gn/T/android2295280901380018275sketch/bin/classes

Any ideas?

**Comment by cjdg** [comment]
i can confirm  the same +1
