### ISSUE TITLE
SDKUpdater says "No Updates Available" when no internet

### ISSUE THREAD

**Issue by DeerajTheepshi** [processing/processing-android#524]
Steps to recreate:
Open SDK Updater without internet connection.

It would be better to notify the user about the issue with internet connectivity rather than giving incorrect information that says "No updates"

Priority: Low, doesn't affect any other process. Just an enhancement feature.

**Comment by SyamSundarKirubakaran** [comment]
Good one.! I think this should be a simple patch.! Go ahead.! 👍
