### ISSUE TITLE
text does not appear in the touches example

### ISSUE THREAD

**Issue by clankill3r** [processing/processing-android#526]
Using this example I see no text at all when I touch:
https://android.processing.org/reference/multitouch/touches.html

(Also as a side node, it makes more sense to have a minimum size for the ellipse. As of now, I can only see the ellipse for a split second when I stop touching the screen, else my finger is covering the screen.)

**Comment by codeanticode** [comment]
@clankill3r thanks for the suggestion, I updated the example so that the ellipses have a minimum radius and the text is visible.

**Comment by codeanticode** [comment]
actually, just realized that this is an issue not so much about the mode itself but more about the website, which has it own repo here: https://github.com/codeanticode/processing-android-website :-)
