### ISSUE TITLE
Bug in loadShape(), not load .mtl asociated file.

### ISSUE THREAD

**Issue by LuislopezMartinez** [processing/processing-android#534]
This example works fine in java mode, but in android not load material and model apears with no colors.
Code example: 

```
PShape s1,s2;
float ry;

public void setup() {
    size(640, 360, P3D);
    orientation(LANDSCAPE);
    s1 = loadShape("3d/models/rocket/rocket.obj");
    s2 = loadShape("3d/models/cubo/untitled.obj");
}

public void draw() {
    background(0);
    lights();

    translate(width/2, height/2 + 100, -200);
    rotateZ(PI);
    rotateY(ry);
    shape(s1);

    ry += 0.02;
}
```

The s2 object returns exception when atempt to load a .mtl file..   .mtl file has at the same folder of .obj model.

If move the .mtl file to data/ folder the skets works fine.
This is a bug.

**CODE EXAMPLE:** https://www.dropbox.com/s/tef1b5dah18i7gm/prueba_assets.zip?dl=0

**Comment by dzaima** [comment]
It seems this [was](https://github.com/processing/processing/issues/2003) once a bug in the Java mode and [was fixed](https://github.com/processing/processing/commit/b0dbb20fd96559b3dcc0aa4ee0f9413df67d822d), but the fix hasn't been ported to Android (the main lines of interest being [here](https://github.com/processing/processing-android/blob/cac5c642ed8427476d85148e42c0b52ed045b7d2/core/src/processing/core/PShapeOBJ.java#L240-L249)). I'm not one here to say how to handle this, but once someone shows up, at least they know where to look.

Also, please close the old issue to avoid clutter there.

**Comment by LuislopezMartinez** [comment]
It would be great to have a last minute fix, because it is very dirty to have a lot of files so messy in the main directory.

**Comment by dzaima** [comment]
It should be possible to, as a temporary & possibly annoying solution, replace the `mtllib rocket.mtl` line in the `.obj` file, with, in this case, `3d/models/cubo/rocket.mtl`.

**Comment by LuislopezMartinez** [comment]
Yes, thanks for this tip.

**Comment by codeanticode** [comment]
Done with https://github.com/processing/processing-android/tree/android-0276-v4.1.0, please check once the new release of the mode is out.

**Comment by codeanticode** [comment]
Actually, relative path was broken because implementation of getBasePath() was valid only for desktop, fixed for Android with https://github.com/processing/processing-android/commit/1d343b76457774626b1289b9025c8d8737f0c865
