### ISSUE TITLE
Can't save tables on android

### ISSUE THREAD

**Issue by Bobby54** [processing/processing-android#535]
Tried to save a table to Android using this code:

`Table table;

void setup(){

  table = new Table(); 

  saveTable(table, "Android/data/com.calsignlabs.apde/test.xlxs");

}`

Tried most of the possible folders to save it in, but I always get the following error.

![errorMessage](https://user-images.githubusercontent.com/47862814/59786175-ef734680-92c6-11e9-8d51-be82e1dfdbc1.PNG)

The application on my phone simply stops running.
I think the problem is the notation of where I want to save it.

**Comment by dzaima** [comment]
What Android version are you on? Do you want to write on the internal or external storage?

Did you enable the `WRITE_EXTERNAL_STORAGE` permission and manually turned it on in the apps properties?

After enabling the permission, in many cases the path `/sdcard/Android/...` should work (note that `/sdcard/` isn't guaranteed to exist on all android phones though; if you want the app to be portable you'd need to use `Environment.getExternalStorageDirectory().getAbsolutePath()` or something similar)

**Comment by Bobby54** [comment]
My Android Version is 6.0.1, I am trying to save to internal storage.
I have enabled the permission to save data from USB to my storage on the phone, but I'll try to allow the permission in the Sketch as well.
Thanks for your help

**Comment by Bobby54** [comment]
Thanks again, it is working now.
Onliest issue is still the Extension of the table file.

**Comment by dzaima** [comment]
The valid extensions for saving a table are `csv`, `tsv`, `bin`, and `html`, look [here](https://processing.org/reference/saveTable_.html).

**Comment by Bobby54** [comment]
Figured that as well, thanks though.
Closing the issue now.
Thanks for your help once more.
