### ISSUE TITLE
Skip downloading zip files during installation if present

### ISSUE THREAD

**Issue by kfrajer** [processing/processing-android#537]
#### Summary:
When installing the AndroidSDK, it first downloads the needed zip files into the temp folder and then it creates the `sdk/` folder and unzip them there. Finally it removes the temp folder that stores the zip files (Intended behavior)

#### Feature request:
To downloaded the files only if not present in the temp folder.

#### Additional info:
Currently this can be done manually by following these steps:
1. Download the files and place them in the temp folder
2. Disable the following two blocks:
  * The `while()` block in [`downloadAndUnpack()`](https://github.com/processing/processing-android/blob/master/mode/src/processing/mode/android/SDKDownloader.java#L233) function within **SDKDownloader.java** 
  * Disable removal of [`Temp` folder](https://github.com/processing/processing-android/blob/master/mode/src/processing/mode/android/SDKDownloader.java#L179) in **SDKDownloader.java**. It is in the `SDKDownloadTask` class.

**Comment by DeerajTheepshi** [comment]
- I guess this might be useful in cases of an incomplete download due to, say internet connectivity , and the user might have to download all the zip files once again .
- In the downloadAndUnpack() method : We could check for the presence of temp folder (in case of incomplete downloads), check the files for md5 checksum and then unzip it .

**Comment by kfrajer** [comment]
Yes, I think this is a great use case and I like it. However there are other use cases that we need to capture. For example, Sarah's comment [here, #21](:https://github.com/DeerajTheepshi/processing-android/issues/21)

The first step to implement this is for `urlHolder` to also manage file size and file checksum values. 
The second step is to manage the `temp/` folder lifecycle during installation.
