### ISSUE TITLE
API 28 not available?

### ISSUE THREAD

**Issue by Quentlac** [processing/processing-android#551]
Hello, I tried to upload my Android Package on Google Play Store, but I can't because the level API required is API 28. How to do? thanks

**Comment by hmy65** [comment]
You may try use processing as a library.
https://android.processing.org/tutorials/android_studio/index.html

**Comment by codeanticode** [comment]
When working in the PDE, the target level can be set manually to a higher value by editing the preferences file (accessible through the Preferences menu). By agree that next version of the mode should target Android 28 by default

**Comment by codeanticode** [comment]
Dependencies updated to Android 28 in https://github.com/processing/processing-android/commit/4f10a9d38b3d9908d578f6ac898192dfba82976d
