### ISSUE TITLE
Multitouch: releasing second touch does not trigger touches[] update

### ISSUE THREAD

**Issue by Garbaz** [processing/processing-android#553]
Holding down two fingers on the screen and releasing one without moving(!) the other will not update `touches[]`. The array will still contain two objects (which are unchanged) until an update is triggered by releasing or moving the remaining finger. `toucheEnded()` still gets called.

If I get the touch events manually by overwriting `surfaceTouchEvent()`, everything works as expected, so the issue seems to be with Processing and not Android or my phone.

**Test code:**
```java
void setup() {
}

void draw() {
  background(255);
  fill(0);
  textSize(64);
  textAlign(CENTER, CENTER);
  text(touches.length, width/2, height/2);
}
```
**How to reproduce:**

Hold down two fingers (It should display a 2) release one while holding the other still. It still is a 2 (at least for me), even though it should be a 1.

_Versions:
Processing: 3.5.2
Android Mode: 4.0.4_

**Comment by codeanticode** [comment]
@Garbaz Cannot reproduce, tested on two different phones. The number of touch pointers gets updated as expected as I release fingers. What phone/android version are you using?

**Comment by Garbaz** [comment]
Phone: Fairphone 2

Android Version: 7.1.2

**Comment by codeanticode** [comment]
OK, thanks for the code. I will leave this for a bugfix release after 4.1 is out

**Comment by JonLit** [comment]
I have observed the same Error (multiple touches registered even after fingers left the screen) on my Xiaomi 12 Lite (Android 12), but interestingly NOT on my Honor 9X Lite.
I even managed to get 3 Touches registered after taking off my hand. It seems to occur when I only touch the screen for a 
_very_ short time, same with releasing the second finger which I can reproduce much more easily.
I have not made a simple testing sketch, but I observed it while making this: https://github.com/JonLit/shortCutPhone

**Comment by dfkettle** [comment]
I'm not sure if this is the same issue, but I added some print statements to display the 'touches' array after every "touch started" and "touch ended" event. The counter on the device's screen is correct, but the info displayed in the console isn't. This is what I see in the IDE console when I touch with two fingers, then release them one at a time, about a second apart.

```
touch started
0 767.0 1164.0
touch started
0 767.0 1164.0
1 598.0 1367.0
touch ended
0 759.0 1170.0
1 595.0 1367.0
touch ended
```

I'm testing this on a Samsung Tab Lite 6 running Android 12 (attached to my computer). Here's the code I used to test:

```
void setup() {
  fullScreen();
}

void draw() {
  background(255);
  fill(0);
  textSize(64);
  textAlign(CENTER, CENTER);
  text(touches.length, width/2, height/2);
}    

void touchStarted() {
  println("touch started");
  printTouches();
}

void touchEnded() {
  println("touch ended");  
  printTouches();
}

void printTouches() {
  for (int i = 0; i < touches.length; i++) {
    println(touches[i].id,touches[i].x,touches[i].y);
  }
}

```

**Comment by codeanticode** [comment]
It's tricky to reproduce, most of the time the pointers are updated immediately, tested on a couple of different devices. The closest I was to reproduce it was in a few instances when the pointer that corresponded to the finger that was releases stayed a bit longer, but eventually was removed.

**Comment by codeanticode** [comment]
@Garbaz @dfkettle Ok I think I found the reason for this issue: when a ACTION_POINTER_UP event was registered, the event would still return the pointers including the one being released. So it remained in the list of touches until another event is registered. This commit should take care of this: https://github.com/processing/processing-android/commit/208f5e3508a69dc3d9f7df017560dcb7281fefd1, I will release a new beta version of the mode shortly so you can test it more extensively.
