### ISSUE TITLE
rewarded video ads 

### ISSUE THREAD

**Issue by Yashwanthd1998** [processing/processing-android#554]
hi the code down executes but no rewarded video ad shows..can some one help .iam having very bad time implementing it from the past two weeks.help.

import android.os.Looper;//for setup() if needed
      import android.os.Bundle;
      import android.view.Window;
      import android.widget.RelativeLayout;
      import android.app.Activity;
      //import com.google.ads.*;//
      import com.google.android.gms.ads.AdRequest;
      import com.google.android.gms.ads.AdView;
      import com.google.android.gms.ads.AdSize;
      import com.google.android.gms.ads.MobileAds;
 
 private RewardedVideoAd mRewardedVideoAd;
  private RewardedVideoAdListener r;
      public void setup(){
           size(800, 1000);
       }
 
      public void draw(){
         background(100);
         rect(100,100,100,100);
      }
 
        @ Override
      public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
          Window window = getActivity().getWindow();
       RelativeLayout adsLayout = new RelativeLayout(this.getActivity());
       RelativeLayout.LayoutParams lp2 = new RelativeLayout.LayoutParams(
          RelativeLayout.LayoutParams.WRAP_CONTENT, RelativeLayout.LayoutParams.MATCH_PARENT);
 
        MobileAds.initialize(this.getActivity(), "ca-app-pub-3940256099942544~3347511713");

       mRewardedVideoAd = MobileAds.getRewardedVideoAdInstance(this.getActivity());     
     mRewardedVideoAd.setRewardedVideoAdListener(r);  
      loadRewardedVideoAd();  
    window.addContentView(adsLayout,lp2);  
      }
      
private void loadRewardedVideoAd()
{
mRewardedVideoAd.loadAd("ca-app-pub-3940256099942544/5224354917",new AdRequest.Builder().build());
    }

      
 public void onRewardedVideoAdFailedToLoad(int errorCode)
 {
        loadRewardedVideoAd();
    }

 public void onRewardedVideoAdLoaded() 
{
    if (mRewardedVideoAd.isLoaded())
       {
          print("uck"); 
          mRewardedVideoAd.show();
        }
    }

**Comment by codeanticode** [comment]
I have no experience with video ads, but seems that you need to import additional packages ( com.google.android.gms.*) so that might be difficult to do in the PDE. I'd recommend you use Android Studio instead, you can still use the processing-core library, as explained in [this tutorial](https://android.processing.org/tutorials/android_studio/index.html).

**Comment by codeanticode** [comment]
No updates, closing.
