### ISSUE TITLE
Raycasting API

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#559]
The p5.xr library implements a number of functions for raycasting in VR/AR:

* rayObject =  {origin: p5.Vector, direction: p5.Vector}
* generateRay(Number x1, Number y1, Number z1, Number x1, Number y2, Number z2) - returns rayObject
* intersectsBox(Number width, [Number height], [Number depth], [rayObject ray]) - returns boolean
* intersectsPlane([rayObject ray]) - returns p5.Vector(2D)
* intersectsSphere(Number radius, [rayObject ray]) - returns Boolean
* getRayFromScreen(Number screenX, Number screenY) - returns rayObject

These could be useful to add to the VR/AR libraries in the Android mode. 

More information:

Implementation: https://github.com/stalgiag/p5.xr/blob/master/src/p5xr/core/raycasting.js

Examples: https://github.com/stalgiag/p5.xr/tree/master/tests/manual-test-examples/p5vr/raycasting

Doc discussing design/implementation: https://docs.google.com/document/d/1JzvLBAQuh7gydo0Wpk0UhdgbTBkSekFp-uoKKSUN5Xg

**Comment by b2renger** [comment]
This is great ! maybe some feature enhancements from this could be helper functions to draw projected shadows on tracked planes ? and very probably to calculate occlusion from walls ?

**Comment by codeanticode** [comment]
@b2renger thanks for the suggestions, are you referring to AR?

**Comment by codeanticode** [comment]
@stalgiag As for the ray casting API, it ports all the functions in p5.xr, so this can be considered complete. There are some differences in implementation, for instance, there is no generateRay equivalent, as I don't think one needs to transform origin/direction before the corresponding intersectsX call. We can discuss this later.

@reas @benfry @lmccart just a heads up of the ongoing efforts to sync AR/VR between p5 and android mode.
