### ISSUE TITLE
Screen Flickering caused by SurfaceView

### ISSUE THREAD

**Issue by hmy65** [processing/processing-android#570]
@codeanticode 

SurfaceViewAndroid2D extends SurfaceView, brings the screen flicking problem.

My main activity is a simple start activity, I put a button when I click that button, it will start CanvasActivity which contains a PFragment.
The screen will shortly flash with black screen. 
After doing some research, I found this is caused by android surfaceview api.

Nobody report this bug yet maybe because most people use the default processing IDE, so their first activity is the processing canvas.

Some related info here:
https://stackoverflow.com/questions/12232583/android-surfaceview-causing-screen-flicker

After doing some other research, I found an easy fix.

put " setBackgroundColor(Color.argb(0x00, 0, 0, 0));
      getHolder().setFormat(PixelFormat.TRANSPARENT);" at the end of the SurfaceViewAndroid2D constructor.

I told you since mine is already migrated to AndroidX, so I won't start a pull request.
You could add these two lines to repo.
![image](https://user-images.githubusercontent.com/30286560/67792323-13446580-facd-11e9-9ac3-04a6e189d075.png)

**Comment by codeanticode** [comment]
Thank you! Incorporated in https://github.com/processing/processing-android/commit/5f1411fcf40f89eb50b800939d26a15b1059d1db
