### ISSUE TITLE
Emulator does not launch on Linux

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#571]
Tested on Ubuntu 16.0.4, the system images for both phone and watch install correctly, but when the PDE tries to open the emulator, it fails with the following error:

```
Emulator process exited with status 1.
EmulatorController: Emulator never booted. NOT_RUNNING
Error while starting the emulator. (NOT_RUNNING)
```

**Comment by q2dg** [comment]
Well, this is similar to https://github.com/processing/processing-android/issues/467 
Still waiting...

**Comment by codeanticode** [comment]
Maybe fixed with this: https://github.com/processing/processing-android/pull/639, will review.

**Comment by codeanticode** [comment]
The emulator does work on Linux (tested with Ubuntu 20.04, takes some time and maybe need to hit run on emulator a second time if the first attempt times out because of the image install)
