### ISSUE TITLE
console no longer responsive with 4.1 update

### ISSUE THREAD

**Issue by hunterkiddo** [processing/processing-android#572]
attempting to print() no longer show up in the console after updating to 4.1, which also had me redownload Android SDK. Errors also do not show up in in the console. [#277 ](https://github.com/processing/processing-android/issues/277) apparently this has happened before?

**Comment by codeanticode** [comment]
It may be a regression introduced by the update to the latest SDK tools, including adb (the redownload is expected). I will look into it, thank you for posting!

**Comment by hunterkiddo** [comment]
another person with this issue: https://discourse.processing.org/t/is-there-an-android-mode-4-1-problem-characters-are-broken-solution/15033/4

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/7b820b250b5be1fc23d2bd37ee86f5e7296097fc
