### ISSUE TITLE
Grammatical errors on home page: https://android.processing.org/index.html

### ISSUE THREAD

**Issue by GwizBilly** [processing/processing-android#581]
https://android.processing.org/index.html

Errors highlighted with _ underscore:

"Processing for Android also lets you access_ing_ the Android API to read sensor data, and export_ing_ your sketch as a signed package ready to upload to the Google Play Store."

Suggested correction:

"Processing for Android also lets you access the Android API to read sensor data, and export your sketch as a signed package ready to upload to the Google Play Store."

**Comment by codeanticode** [comment]
Thanks for pointing this out. Should be added to the [website's repo](https://github.com/codeanticode/processing-android-website), re-opening over there: https://github.com/codeanticode/processing-android-website/issues/19
