### ISSUE TITLE
premultiplyMatrices not found

### ISSUE THREAD

**Issue by pallav12** [processing/processing-android#586]
In debug-> apps -> fast2d->src ->java-> Sketch.java 
compilation error because of line 546 and 548
![Screenshot (101)](https://user-images.githubusercontent.com/46514947/71720611-5661e280-2e48-11ea-9fc6-1d3a81214a66.png)
there's no static variable in PGraphics2DX as premultiplyMatrices

**Comment by codeanticode** [comment]
Fixed in release 4.2.0
