### ISSUE TITLE
need to update old wiki for this repo

### ISSUE THREAD

**Issue by LuGO0** [processing/processing-android#592]
It has been clearly mentioned in the repo that ant support has been scraped off particularly due to dependency resolution but still some links in the wiki takes us to the old wiki

![Capture](https://user-images.githubusercontent.com/30355336/75926072-d7ad1400-5e8f-11ea-83fe-959db49ddb3b.PNG)

**Comment by codeanticode** [comment]
That's a screen of Processing's wiki, which does use ant for compilation... this does not seem to be a valid issue.
