### ISSUE TITLE
Google Play does not accept .apk anymore.

### ISSUE THREAD

**Issue by FarukHammoud** [processing/processing-android#594]
Now, we are now forced to upload an .aab (Android App Bundle) to Google Play.

**Comment by codeanticode** [comment]
Thanks for the heads up. According to Google's documentation, use of AABs will not be mandatory until [August 2021](https://support.google.com/googleplay/android-developer/answer/9859152?hl=en), so there is still some time to make the switch.

**Comment by rupesh-kumar-lpu** [comment]
@codeanticode I have checked now AAB is the only way to distribute the app on the google play console. I worked on adding the menu module for AAB generation earlier and it went well. Looking forward to completing it.

**Comment by codeanticode** [comment]
Excellent, thanks Rupesh! Have you created a PR with your current implementation, I'll review it when it's ready.
And I just noticed that we already in August 2021 so we have to get this done soon :-)
