### ISSUE TITLE
lerpColor(int, int, float) is missing in the PApplet

### ISSUE THREAD

**Issue by SanielDan** [processing/processing-android#598]
lerpColor(int, float, float) overload is missing in the Android mode, only lerpColor(int, float, float, int) is available for this mode.

**Comment by dzaima** [comment]
Seems [this](https://github.com/processing/processing-android/commit/77ca9229001d4825b463c65bbd3aa2df9b476b43#diff-29e1de29464981394819a89e38e87288L9912) commit is responsible for the removal. Probably a mistake while refactoring.

**Comment by ranaaditya** [comment]
> lerpColor(int, float, float) overload is missing in the Android mode, only lerpColor(int, float, float, int) is available for this mode.

yes, I also faced this issue few days ago.

**Comment by codeanticode** [comment]
Done with https://github.com/processing/processing-android/commit/4b6579607e7e5096bb3bf0ab5bcc88dc32ea5328
