### ISSUE TITLE
APDE for Android chrashes instant after starting

### ISSUE THREAD

**Issue by FIeischi** [processing/processing-android#604]
Everytime I use an ArrayList in APDE the App crashes. 
When trying to open it again, it crashes with no really error. 

The only way I found to fix it, is reinstalling the app.

A month before everything worked fine, but now theres this nasty error. 

Thanks for help,

**Comment by dzaima** [comment]
The proper place for bug reports about APDE is [on its repo](https://github.com/Calsign/APDE/).

**Comment by ranaaditya** [comment]
closing this issue, it should be on APDE repo.
