### ISSUE TITLE
android studio example crashes at startup

### ISSUE THREAD

**Issue by paulgoux** [processing/processing-android#611]
The example provided on the android processing site does not work.

https://android.processing.org/tutorials/android_studio/index.html

I think it might have something to do with permissions. Any help would be great, I have tried things for the last week and nothings worked.

I have even tried the solutions in the migrating to androidX issue request and am pointing the program to processing build 4.11

**Comment by eoao** [comment]
Dear Processing team,
I am having the same problem. I've found out that processing doesn't support higher API's.
By using androidx instead of android and adjusting the code should solve this problem

**Comment by paulgoux** [comment]
ive found an alternative, I had to resolve the permissions issue in processing to get it to work on android 10 so now no need for android studio

**Comment by codeanticode** [comment]
@paulgoux @eoao the latest release of the mode and core library has been updated to support Android 10 and the AndroidX packages, please confirm if this issue has been solved by the update. Thanks!

**Comment by GENTEK05** [comment]
Just create a new project in android studio, added implementation 'org.p5android: processing-core: 4.2.0'
and nothing works! Can't you do it and check everything, or does everything work?

**PApplet shown in red**
**import processing.core.PApplet; shown in red**
```
import processing.core.PApplet;

public class AAAAAAA extends PApplet {
    @Override
    public void settings() {
        size(displayWidth, displayHeight);
    }

    @Override
    public void setup() {

    }

    @Override
    public void draw() {

    }
}
```

**Comment by rupesh-kumar-lpu** [comment]
Hi @GENTEK05 

There's a helpful explanation @ranaaditya has mentioned in #640 for the kind of issue that you are facing. I hope this resolves the issue.

**Comment by codeanticode** [comment]
Android Studio examples in the tutorials probably need to be revised/updated. They were written some years ago.

**Comment by paulgoux** [comment]
I agree some updates are needed to keep this part of processing relevant. As much as a may disagree with the direction that people want processing to head in, I also see the potential to create a great fast prototype and deployment platform unrestricted by Android studio.

I am in the process of creating a library to add simple basic functionality, out of the box, ie keyboard text input, gui, with sliders etc and user request prompts. I understand you can use context and to access some android functions but again, it feels like thats a big departure away from processing.

This library will allow users to code to android using processing without having to worry about any android specific code.

**Comment by codeanticode** [comment]
@paulgoux thanks for your comments. By direction you mean what's exposed through the core library or the functionality of the Android mode itself? The idea of your library sounds interesting, keep us posted!

**Comment by ranaaditya** [comment]
> I agree some updates are needed to keep this part of processing relevant. As much as a may disagree with the direction that people want processing to head in, I also see the potential to create a great fast prototype and deployment platform unrestricted by Android studio.
> 
> I am in the process of creating a library to add simple basic functionality, out of the box, ie keyboard text input, gui, with sliders etc and user request prompts. I understand you can use context and to access some android functions but again, it feels like thats a big departure away from processing.
> 
> This library will allow users to code to android using processing without having to worry about any android specific code.

@paulgoux this seems to be interesting idea, please keep us posted about the development !

**Comment by rupesh-kumar-lpu** [comment]
I tried updating some tutorial code to the android website sources [here](https://github.com/codeanticode/processing-android-website/pull/21) if you haven't reviewed it yet @codeanticode

**Comment by paulgoux** [comment]
Here is the start of my project. There is more to come. Here is read write and permissions in android.
In the following few months I hope to add the rest of Noels examples. This should provide a good basic foundation for most coding projects. Also I'll look into adding serial usb and bluetooth as some have had difficulties with this.

https://github.com/EmmanuelPil/Android-java-code-utilities-widgets-for-Processing-for-Android

https://github.com/paulgoux/fileWriter-Android/tree/main/fileWriter

**Comment by paulgoux** [comment]
> @paulgoux @eoao the latest release of the mode and core library has been updated to support Android 10 and the AndroidX packages, please confirm if this issue has been solved by the update. Thanks!

Sorry I didnt reply. Yes I've seen it and am making full use of it!

**Comment by codeanticode** [comment]
> I tried updating some tutorial code to the android website sources [here](https://github.com/codeanticode/processing-android-website/pull/21) if you haven't reviewed it yet @codeanticode

I will look at it soon, thank you!

**Comment by codeanticode** [comment]
Reorganized the project structure in the main branch, to follow more closely the Android standard. It should be enough to import the root folder of the repo to be able to run the sample apps and debug/develop the core, VR, and AR libraries.
