### ISSUE TITLE
Emulator is not available

### ISSUE THREAD

**Issue by toreal** [processing/processing-android#636]
Here seems a bug.
Processing can not run in an emulator.
Does it forget to add an exclamation mark? !emulator.exists()

```
final File emulator = sdk.getEmulatorTool();
     if (emulator == null || emulator.exists()) {
       System.err.println("EmulatorController: Emulator is not available.");
       return;      
     }
```

**Comment by ranaaditya** [comment]
> Here seems a bug.
> Processing can not run in an emulator.
> Does it forget to add an exclamation mark? !emulator.exists()
> 
> ```
> final File emulator = sdk.getEmulatorTool();
>      if (emulator == null || emulator.exists()) {
>        System.err.println("EmulatorController: Emulator is not available.");
>        return;      
>      }
> ```

Hi @toreal , can you please describe ( preferably Screenshot of the issue) the error / issue you are getting while running Processing sketches on emulator ?

Code seems to be absolutely good without any error !

also please specify your System specifications. It may be possible that your system doesn't support emulators !

thanks,
rana

**Comment by toreal** [comment]
Thank you for your response.
I use MacOS.
I download Processing and change it into Android mode.  
then download Android SDK, then download emulator and install it. 
All is done automatically.

then, I got the error.
EmulatorController: Emulator is not available.

In previous version, everything is fine. 
Thus, I try to compare the two versions. I find those code I can not understand well. 
emulator.exists but Emulator is not available
 

<img src='https://firebasestorage.googleapis.com/v0/b/violetweb.appspot.com/o/images%2Ffea3cc43-c7e5-40fc-83f9-b739b008498f.png?alt=media&token=f631d191-15a6-47c4-b970-fbc73d191ecd'/>

**Comment by toreal** [comment]
@ranaaditya can you run in the emulator?

**Comment by ranaaditya** [comment]
Hi @toreal , did you change the Android SDK location ?

Check if you are able to run emulator using android studio. Seems like there are some errors while initializing the Emulator for you.

Can you do one more thing - revert back to previous version and check if you are able to run emulator in it.

**Comment by toreal** [comment]
Hi @ranaaditya 
I can run the emulator from  android studio or by command. But Processing still say 'EmulatorController: Emulator is not available.'

Actually, I try to compile from source code and change  the source code as the following.
`final File emulator = sdk.getEmulatorTool();
     if (emulator == null || !emulator.exists()) {
       System.err.println("EmulatorController: Emulator is not available.");
       return;      
     }`

Then, I can run in the emulator.

**Comment by toreal** [comment]
Hi @ranaaditya 
I don't know how to revert back to previous version. Can you teach me?

**Comment by ranaaditya** [comment]
> Hi @ranaaditya
> I don't know how to revert back to previous version. Can you teach me?

Hi @toreal , if you are building from the source code then follow:

1.see the commit history (preferabbly in github web client) or use **git log**  command.
2. Copy the hash of the very first commit responsible for new version.
3. Checkout to a new branch(to avoid messing up in your local).
4. do **git reset --hard <copied_hash>
5. try to build now

**Comment by toreal** [comment]
@ranaaditya  Thanks. I can do it from the source code.  But I do not know how to use the previous version from the release version.  Although, I can build from the source code and use the emulator. But I don't know how to deploy the VR/AR libraries. The VR/AR functions can not work correctly from my build. I need a released version. I am so surprised that why nobody has the requirement as I to wait to use the emulator?
