### ISSUE TITLE
Updating android mode with latest permission updates

### ISSUE THREAD

**Issue by ranaaditya** [processing/processing-android#645]
android-mode need to get updated with the updated android permission system, new permissions, depreciations and updates.
 #611 

references:
- [new one time permission system in Android 11](https://medium.com/swlh/android-11-one-time-permission-changes-fda18ca4367e)
- [permissions changed in Android10](https://developer.android.com/about/versions/10/privacy/changes)
- [permission updates in Android 11](https://developer.android.com/about/versions/11/privacy/permissions)
- [permission hub in Android 12 preview](https://www.xda-developers.com/android-12-permission-management-hub-dashboard-internal-debugging-tool/)

....

This will consist of hit-trial testing and will require Android 26+ devices (or emulators with Android 26+ image)

**Comment by codeanticode** [comment]
Should be done with https://github.com/processing/processing-android/commit/e6b4c0db6cf4a9e787d8a19fc1c5ce95f12a5e5d

@ranaaditya if there is any missing new permission, let me know
