### ISSUE TITLE
Errors executing Permissions Python Script

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [processing/processing-android#649]
![PermissionScriptFailure](https://user-images.githubusercontent.com/46577873/114325343-3e016d00-9b4d-11eb-9f44-42fcd562c93c.PNG)

Currently, I am trying to understand the workflow of the [script](https://github.com/processing/processing-android/blob/master/mode/scripts/permissions.py). 
The script is not compatible with python 3(shows errors on printing statements and importing [urllib2](https://stackoverflow.com/questions/6594620/python-3-2-unable-to-import-urllib2-importerror-no-module-named-urllib2)), I changed to Python 2.7 and then installed the BeautifulSoup module separately. Running the script has shown key error mentioned in the image above.

Would it be better to have python version validation and module auto set up methods in the script?

Your views on this would be helpful @ranaaditya @codeanticode

**Comment by ranaaditya** [comment]
Yes @rupesh-kumar-lpu  these python scripts also didn't work for me last time.

We need to migrate them to python 3+ and (not sure if we are using SL4A) need to see if there is something upgraded / deprecated in [**SL4A**](https://pythonspot.com/sl4a-android-python-scripting/) which is hindering us to run these scripts for this project

**Comment by rupesh-kumar-lpu** [comment]
Thanks for your response on this @ranaaditya I will look into the SL4A.

**Comment by codeanticode** [comment]
The script is updated to Python 3: https://github.com/processing/processing-android/commit/33151c8d715e961dcf88701d813fd04bff657ce9
