### ISSUE TITLE
Minimum SDK Tag in AndroidManifest.xml shows error on exporting signed package

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [processing/processing-android#654]
Discussions on Processing Discourse Forum about the issue - [I can’t export signed...](https://discourse.processing.org/t/i-cant-export-signed-and-aligned-pakage-whats-wrong/29725/5) and [Processing Android debug mode](https://discourse.processing.org/t/processing-android-debug-mode/29094)

**Method to reproduce:**

`New Project  =>  Save Project  => File => "Export Signed Package"`

Specifying target and minimum SDK versions are sufficient to include in build [templates](https://github.com/processing/processing-android/tree/master/mode/templates). I think excluding the tag will not create any problem but it will resolve the issue.

**Comment by codeanticode** [comment]
Ok, so I think this is the same as https://github.com/processing/processing-android/issues/662

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/afb84baed09c9e14923ef66bfedf5a592f600747
