### ISSUE TITLE
support flutter ?

### ISSUE THREAD

**Issue by odaymusic** [processing/processing-android#667]

**Comment by codeanticode** [comment]
Support for flutter in the android mode goes beyond the scope of the project (incorporating another language into the PDE, in this case Dart, is not trivial),  but there is a separate project that re-implements the processing API in Dart so it can be used in Flutter applications:

https://github.com/codeanticode/p5.dart

Another related ongoing project is the Kotlin-native mode:

https://github.com/processing-for-kotlin/kotlin-native-mode

that implements support for Kotlin and aims at using Kotlin Native to run sketches on Android and iOS
