### ISSUE TITLE
Why is compilation so slow?

### ISSUE THREAD

**Issue by embedream** [processing/processing-android#669]
it.s completes the Android mode installation in Processing-4.0b1 , can compile, and execute on the phone, but the compilation time is too slow, a simple program takes more than 30 minutes, what is the reason?
I tried SDK downloads automatically and manually locate the SDK directory on Android Studio. No improvement in compile time.
Look forward to master to give directions!
Thank you very much!

**Comment by codeanticode** [comment]
That's weird, the sketch compilation should not take more than a few seconds (on a fast computer):

<img width="701" alt="image" src="https://user-images.githubusercontent.com/62246/158064449-00e69f52-3c08-434e-9c0f-16818510f8b1.png">

Maybe there is something else is happening with your setup. What OS are you using?

**Comment by rupesh-kumar-lpu** [comment]
Confirming that the build is running fine for me (not slow) on processing 4.

**Comment by codeanticode** [comment]
@embedream try the [latest release](https://github.com/processing/processing-android/releases/tag/latest) of the mode compatible with processing 4.0b7, to see if build process is faster. I have not seen anything unusual so far.

**Comment by ranaaditya** [comment]
> Confirming that the build is running fine for me (not slow) on processing 4.

Agree with Rupesh, Build LGTM.

**Comment by ranaaditya** [comment]
> it.s completes the Android mode installation in Processing-4.0b1 , can compile, and execute on the phone, but the compilation time is too slow, a simple program takes more than 30 minutes, what is the reason? I tried SDK downloads automatically and manually locate the SDK directory on Android Studio. No improvement in compile time. Look forward to master to give directions! Thank you very much!

Hi @embedream , that's weird, normally build should not take more than 10-15 mins in very slow case.

I believe build is slow maybe due to too many java projects / process runnig at same time or maybe your system is low end or having less RAM.

BTW what was your system config during the build.

Thanks,
Aditya
