### ISSUE TITLE
Getting pixels is null

### ISSUE THREAD

**Issue by muslimmuda15** [processing/processing-android#670]
https://github.com/processing/processing-android/blob/b6cae000feddf08f3bfcb2faf76369c7ac15ba82/core/src/processing/core/PImage.java#L195

I found the pixels is null, I saw the init you set pixel by width and height

**Comment by codeanticode** [comment]
Please see the comment of that initializer:

https://github.com/processing/processing-android/blob/b6cae000feddf08f3bfcb2faf76369c7ac15ba82/core/src/processing/core/PImage.java#L187

This is a case where the pixels array is not allocated until explicitly calling loadPixels().
