### ISSUE TITLE
SDK version 30+?

### ISSUE THREAD

**Issue by GyverLibs** [processing/processing-android#673]
Is it possible to sign project with SDK 30+ via processing IDE? I manually installed SDK 30, builded and signed APK, but in Play Console i have "ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme."

**Comment by codeanticode** [comment]
The mode does not yet support V2 signing (#646), working on it at the moment. I'm going to close this as a duplicate, but thanks for the heads up.
