### ISSUE TITLE
PGraphics is very slow

### ISSUE THREAD

**Issue by GyverLibs** [processing/processing-android#674]
Hello! Imaging "pre rendered" PGraphics object is ~15 times slower than drawing it "manually" (couple of rects and circles for example). Vice versa in Java mode - imaging PGraphics is faster!  

Approximate example of what I am taking about:
```
PGraphics canvas;

void setup() {
  canvas = createGraphics(w,h);
  canvas.beginDraw();
  // draw some graphics to image 
  canvas.endDraw();
}

void draw() {
  for (int i = 0; i < 1000; i++) image(canvas, 0, 0);
}
```
Is slower than
```
void setup() {
}

void draw() {
  for (int i = 0; i < 1000; i++) {
    // draw some graphics
  }
}
```
In Android mode, but faster in java

**Comment by codeanticode** [comment]
The same code will generally run faster on java (pc or mac) than on android. So I would not consider that a fixable issue. And then, drawing 1000 images might actually be slower than drawing 1000 geometric primitives, specially if you use the default (non-hardware accelerated) renderer and the images are large.

**Comment by GyverLibs** [comment]
Okay :(

**Comment by codeanticode** [comment]
Try the P2D renderer, that should run faster in general.
