### ISSUE TITLE
processing4 branch shows warning on build(Target SDK in Manifest)

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [processing/processing-android#678]
It's not a major issue and can be simply resolved. I observed that [manifest.setSdkTarget](https://github.com/processing/processing-android/blob/5e187eb7a213c80d513fb31c88d234d67c87ca65/mode/src/processing/mode/android/AndroidBuild.java#L228) is being used and some recent chages of AAB are not yet there in processing4 branch. During Gradle build in processin4, it shows a warning as Target SDK is being used in manifest and it must be used in build.gradle file. 

Is processing4 planned to be an independent branch or will it be merged into the master? @codeanticode

**Comment by codeanticode** [comment]
I already removed target SDK from the manifest file with this commit: https://github.com/processing/processing-android/commit/afb84baed09c9e14923ef66bfedf5a592f600747 

The plan is to merge the processing4 branch into main, so will be taken care when that happens.

**Comment by rupesh-kumar-lpu** [comment]
Yes, it was already corrected by you in the main branch. Got it now, so closing the issue @codeanticode
