### ISSUE TITLE
Align Package process stream handling(Enhancement) 

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [processing/processing-android#679]
We can use a way we are already doing [pb.redirectErrorStream(true);](https://github.com/processing/processing-android/blob/e39526b3faa2dd95477b2ad93dbf72fd481a7f20/mode/src/processing/mode/android/AVD.java#L168)

or a separate redirect stream handler thread can be defined as follows - 
```
Process process = Runtime.getRuntime().exec(commandArguments, null, workingDir);
      new RedirectStreamHandler(new PrintWriter(out, true), process.getInputStream());
      new RedirectStreamHandler(new PrintWriter(err, true), process.getErrorStream());
```

RedirectStreamHandler will extend the thread and use bufferReader to read the stream line by line and redirect it to the standard output console. The above code will be used just before ['alignProcess.waitFor();'](https://github.com/processing/processing-android/blob/67dcfab77724dabf328b77660ec9613c4fadd0f1/mode/src/processing/mode/android/AndroidBuild.java#L827)

Can it be assigned to me? @codeanticode

**Comment by codeanticode** [comment]
No longer needed with Gradle signing.
