### ISSUE TITLE
Bundle Export Error

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [processing/processing-android#685]
![ExportIssue](https://user-images.githubusercontent.com/46577873/163887587-72e974ad-2a3e-44c2-a347-5fc1df0ca0cc.PNG)

Default Gradle version from the 'version.properties' is not being used for the Top Level Build file. Instead, I am getting [GRADLE_PLUGIN_VER](https://github.com/processing/processing-android/blob/fa4429de11339425f79411e3cdef33484f9b1c8d/mode/src/processing/mode/android/AndroidBuild.java#L1026) value as 7.2.0 which is being used in Top Level Build file. Is there any preference file associated with it from where `Preferences.get("android.gradle_plugin");` returning as 7.2.0? @codeanticode

**Comment by codeanticode** [comment]
Sorry, not sure what you mean, the version.properties in 4.3.0 are the following:

https://github.com/processing/processing-android/blob/android-0280-v4.3.0/mode/version.properties

and updated android-gradle-plugin, gradle-wrapper, and gradle-tooling-api to the versions in the 4.5.0a3 update:

https://github.com/processing/processing-android/blob/android-0402-v4.5.0a3/mode/version.properties

It seemed to work well, but I only tested on mac so maybe I missed some problem with this versioning.

**Comment by rupesh-kumar-lpu** [comment]
I tried to build with the master branch, Let me try with v4.5.0a3 with processing 4 and confirm with you back.

**Comment by rupesh-kumar-lpu** [comment]
You didn't miss anything @codeanticode  It is working well. The issue is resolved. 
Basically, `C:\Users\User\AppData\Roaming\Processing\preferences.txt` file was being used which saved some cache data from previous builds which saved **android.gradle_plugin=7.2.0** inside it during previous builds by line [Preferences.set("android.gradle_plugin", GRADLE_PLUGIN_VER);](https://github.com/processing/processing-android/blob/55bfe5891be4b57b091553882eaf7a6062cd8876/mode/src/processing/mode/android/AndroidBuild.java#L1044)
because of which plugin version([android-gradle-plugin = 7.1.0](https://github.com/processing/processing-android/blob/55bfe5891be4b57b091553882eaf7a6062cd8876/mode/version.properties#L4)) from version.properties was not being used in [TopBuild.gradle.tmpl](https://github.com/processing/processing-android/blob/android-0402-v4.5.0a3/mode/templates/TopBuild.gradle.tmpl)
`preferences.txt` file is preferred over `version.properties` with the condition [here](https://github.com/processing/processing-android/blob/55bfe5891be4b57b091553882eaf7a6062cd8876/mode/src/processing/mode/android/AndroidBuild.java#L1042)
Cleaning C:\Users\User\AppData\Roaming\Processing for a fresh start resolves this.
