### ISSUE TITLE
Build Error when using 'gradlew dist' more than once consecutively 

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [processing/processing-android#687]
The latest build works well with `gradlew dist` command. However, The following issue arises when using `gradlew dist` more than once(one by one).

![ConsecutiveDistErrorCapture](https://user-images.githubusercontent.com/46577873/164953520-4b46e683-3ebf-4c90-8272-b15d5aef550b.PNG)

**Possible Reasons**
The error arises due to Gradle 7 upgrade changes, it seems no other changes raise the issue. The issue was not there in Gradle 6.8.3. Jar files are not getting generated properly in build folders of Core, AR, and VR libraries on running `gradlew dist` again.

**Working Solution**
Deleting build folders of respected libraries Core, AR, and VR or just running `gradlew clean` before running `gradlew dist` resolves the issue. A task can also be defined to delete build folders of libraries on running `gradlew dist` just before the task to create jar files.

**Comment by codeanticode** [comment]
Yes I noticed this, and just started running ```gradle clean``` every time before build or dist. Do you have any idea why this is happening?

**Comment by rupesh-kumar-lpu** [comment]
If we look at the changes in details of 7.0 from 6.0, I see some changes have been done on `buildSrc.jar` generation and some deprecated methods of javaCompile have been removed. More information is available [here](https://docs.gradle.org/7.0/release-notes.html#build-reliability) and [here](https://docs.gradle.org/7.0/release-notes.html) I'm looking into it.
