### ISSUE TITLE
Feature for rendering and saving GIF files

### ISSUE THREAD

**Issue by ranaaditya** [processing/processing-android#690]
**Feature request to render and saving GIF Files in Processing's android-mode.**

For more detailed discussion, we can see P5.js discussion here - [p5.js/issues/5118](https://github.com/processing/p5.js/issues/5118)

**This can be implemented as standalone processing library or can be implemented inside the android-mode as well.**

**Referrences:**
__Note__: All the below resources are for understanding the working of GIF encoding and decoding, GIF Feature will be implemented as a new feature from scratch as per the Processing's android-mode implementation of various renderers.

- [Stackoverflow discussion](https://stackoverflow.com/questions/12726952/how-to-show-animated-gif-image-in-android-application)
- [Square's Gif Encoder](https://github.com/square/gifencoder)
- [GIF View library implemented for android](https://github.com/Cutta/GifView)
- [GIF implemented with Android NDK](https://github.com/waynejo/android-ndk-gif)

PS: I am open to the discussion about the designing and implemetation of the GIF Feature from scratch for processing's android-mode.

Best,
Aditya Rana

**Comment by rupesh-kumar-lpu** [comment]
Hi Aditya, 
As far as I understand from the discussion, Is it about providing an export button to export the sketch's animation on PFragment into an animated GIF? This interesting idea seems to be related to the core library. I have worked majorly on the mode side as compared to the core library part. But let me know if something can be done, as I see this as a helpful feature.
Thanks for raising the discussion here,
Rupesh

**Comment by codeanticode** [comment]
Sounds to me like this functionality should be easy to implement as a contributed library and not as part of the core-android library.
