### ISSUE TITLE
[Android] Is it possible to update libraries like Ketai?

### ISSUE THREAD

**Issue by SeongJongKwak** [processing/processing-android#692]
[Android] Is it possible to update libraries like Ketai?

https://discourse.processing.org/t/android-is-it-possible-to-update-libraries-like-ketai/36856

hello.

I have created several projects and APPs through ‘Android Processing’. Good environment and software.

However, there are many things that do not work through the Android version update.

In particular, the ‘Ketai library’ needs an update.
Do you have a goal or schedule for updating like this?

If anyone knows, please let me know. I wonder.

**Comment by codeanticode** [comment]
@SeongJongKwak I think that the ketai library is no longer maintained (I see the [last commit](https://github.com/ketai/ketai/commits/master) from 2018), but answering to your question, it should be possible to fork the main repo and update the code so it works with the latest version of the Android mode.

**Comment by SeongJongKwak** [comment]
> 
@codeanticode 

Thanks for your kind reply.

**Comment by codeanticode** [comment]
You are welcome! I'm going to close this issue, since it's not really about the android mode, but rather about updating libraries for the android mode, such as ketai.
