### ISSUE TITLE
Export signed package missing in 4.5.0a4

### ISSUE THREAD

**Issue by ludiccc** [processing/processing-android#693]
The item "Export Signed Package" is not available. Only "Export Signed Bundle" is shown in "File" menu. Is there a new procedure to export a package for distribution?

**Comment by rupesh-kumar-lpu** [comment]
@codeanticode @ranaaditya Do we require an Export option for APK? I observe that APK files are sharable and installable on devices and APKs are still widely being used for distributions out of the Google Play Console.

**Comment by ludiccc** [comment]
The whole idea of using Android mode in Processing is to provide a faster and better way to develop apps with all the Processing framework. 

The tutorial must be updated to show the new stuff around this: https://android.processing.org/es/tutorials/index.html, it should simplify these problems.

**Comment by rupesh-kumar-lpu** [comment]
@ludiccc A lot of things have been updated recently in Android Mode and some are in the process. Updating the website is one of the tasks in progress. As the website update involves updating pages in multiple languages and requires updates of image resources as well, It can be a little time-consuming. But, We will try our best to update the website as soon as possible. Thanks for your patience and understanding.

**Comment by ludiccc** [comment]
Yes, I understand that and is it fine, we are on the Open Source community.

In the meantime, is there a roadmap for using Android Studio properly with the actual state of the Processing+Android code?

**Comment by codeanticode** [comment]
@ludiccc the reason I removed apk export is that the Google's play store only accepts aabs:

https://android-developers.googleblog.com/2021/06/the-future-of-android-app-bundles-is.html

@rupesh-kumar-lpu couldn't aab files used in the same way as apks to distribute an app outside the store? I did test installing an aab manually  from the command line using adb.

**Comment by dzaima** [comment]
AFAICT from a quick search, while `.aab`s might be installable through adb, they can't outside of it, which makes it useless as a sideloading sharing method.

**Comment by codeanticode** [comment]
Ok I see. No problem, I will put apk export back in for the next release.

**Comment by ranaaditya** [comment]
> Yes, I understand that and is it fine, we are on the Open Source community.
> 
> In the meantime, is there a roadmap for using Android Studio properly with the actual state of the Processing+Android code?
> 
> I've followed the instructions on the tutorials but Android Studio complains about too many things that I can't continue and it doesn't seem worthy to open issues for each one of them. Some new instructions can help a lot.

Hi @ludiccc , thanks for raising the issue, I think Andres and Rupesh have solved your issue. 

To use Processing in Android Studio is little bit trouble as it has various gradle files so studio finds it hard to detect the proper configuration, you have to use it as a external library and for reference you can take help from my [this repository](https://github.com/ranaaditya/Android-Sketch)

In case you don't understand it, you can revert back to this thread anytime.

Thanks for using Processing,
rana

**Comment by ludiccc** [comment]
As the plan is for the apk export to be included again in the next release, we can conclude this issue. Thanks to everybody :-)

**Comment by rupesh-kumar-lpu** [comment]
@codeanticode Yes, AAB is installable through ADB and It worked fine for me as well. Outside play store, I mean to say here is for third-party distribution app stores. I assumed that many third-party app store websites still be using APK upload options for distribution purposes as the APK was there for a long and it has recently been prioritized to use AAB. But the APK is getting deprecated slowly. I think AAB is the future of distribution and We can remove the option of APK export in the near future. For now, your decision to keep the APK export option can be handy for users as an APK installer on Android devices for direct installation is usually there.

**Comment by dzaima** [comment]
Distributing APKs through means like GitHub releases is still common (this includes me), and as long as versions of Android are in use which don't support easily installing `.aab`s (which afaict is all current versions, and currently-in-use android versions will be used for many many more years (this also includes me)), APKs aren't going anywhere.

**Comment by codeanticode** [comment]
@rupesh-kumar-lpu @ranaaditya we could put apk export back in, sounds like it serves an important function for app distribution outside of the play store. If we do, I'd re-implement the functionality using a gradle task to generate/align/sign the apk instead of doing the aling/sign work ourselves, just like aab export works now.

**Comment by rupesh-kumar-lpu** [comment]
@codeanticode @ranaaditya the option to use grade task for release apk creation sounds good, let me know if I can do something about it. Thanks!

**Comment by codeanticode** [comment]
The gradle task to generate signed apks ready for distribution is "assemble", correct?

https://developer.android.com/studio/build/building-cmdline

**Comment by rupesh-kumar-lpu** [comment]
You can execute 'assembleRelease' via tooling API methods. It will use signing information from the file. @codeanticode

**Comment by codeanticode** [comment]
Just realized the code is all in there already :-)

https://github.com/processing/processing-android/blob/master/mode/src/processing/mode/android/AndroidBuild.java#L792

Only need to add the menu entry to call the exportPackage() function.

**Comment by rupesh-kumar-lpu** [comment]
Yes, We can change keystore manager. I created a boolean earlier to differentiate the type of task(Bundle or APK). [e08fa30](https://github.com/processing/processing-android/pull/671/commits/e08fa30a1f98d36572bcd4f6b94915237b59d39b)

**Comment by rupesh-kumar-lpu** [comment]
If you are not working on it, you can assign it to me @codeanticode

**Comment by codeanticode** [comment]
I made some quick changes:

https://github.com/processing/processing-android/commit/9e57a33e7d5c5642260a3da91069c207df70fda8

If you can review and make fixes if needed, I will create a new alpha release of the mode.
