### ISSUE TITLE
Update default icon

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#698]
When sketches get installed on the device they get a default launcher icon:

https://github.com/processing/processing-android/blob/master/mode/icons/launcher_96.png

This icon should be updated to better match the new project logo.

**Comment by rupeshkumar22** [comment]
https://twitter.com/designsystemsin/status/1425454918123630592?s=20&t=34ugy6NiRm5omEFvm83BSw

This new logo by Design System Internations would be the default launcher icon without Text? @codeanticode @ranaaditya

**Comment by ranaaditya** [comment]
> https://twitter.com/designsystemsin/status/1425454918123630592?s=20&t=34ugy6NiRm5omEFvm83BSw
> 
> This new logo by Design System Internations would be the default launcher icon without Text? @codeanticode @ranaaditya 

Hi @rupeshkumar22 , is this logo available without text ? 

I think this logo will be good without text, what do you think @codeanticode ?

**Comment by rupeshkumar22** [comment]
Hi @ranaaditya @codeanticode 
There is a logo available on Wikimedia Commons here-
https://commons.wikimedia.org/wiki/File:Processing_Android_2021_logo.svg

It seems to be uploaded officially not sure.

**Comment by codeanticode** [comment]
Yes, the logo on wikimedia is good, I also have high-res file I can share with you.

**Comment by ranaaditya** [comment]
> Yes, the logo on wikimedia is good, I also have high-res file I can share with you.

That's great :ok_hand:

**Comment by Bholanath8436** [comment]
I want to work on this issue, please assign me this issue.

**Comment by ranaaditya** [comment]
> I want to work on this issue, please assign me this issue.

Hi @Bholanath8436 you can start working on it but make sure this issue hasn't been resolved yet !

Thanks !

**Comment by codeanticode** [comment]
This one should not bee too hard, it's just a matter of replacing the icons and preview images in this folder:

https://github.com/processing/processing-android/tree/main/mode/icons

using the latest Processing for Android logo. I have the high-res file somewhere to do this.

**Comment by codeanticode** [comment]
Dome with https://github.com/processing/processing-android/commit/b7f7ff71e725798404186d1bb792acfa5f239fd6
