### ISSUE TITLE
Attributes and their values are not getting saved properly in preferences.text 

### ISSUE THREAD

**Issue by rupeshkumar22** [processing/processing-android#700]
It's strange that [Preferences.set("android.sdk.path", folder.getAbsolutePath());](https://github.com/processing/processing-android/blob/55bfe5891be4b57b091553882eaf7a6062cd8876/mode/src/processing/mode/android/AndroidSDK.java#L468)
not committing the changes to the preferences.txt file. During runtime if logs are used- `Preferences.get("android.sdk.path")` returns the correct value just after [Preferences.set("android.sdk.path", folder.getAbsolutePath());](https://github.com/processing/processing-android/blob/55bfe5891be4b57b091553882eaf7a6062cd8876/mode/src/processing/mode/android/AndroidSDK.java#L468)
But after closing the program Preferences.txt file does not contain the attribute and value. So the next time on program startup [load](https://github.com/processing/processing-android/blob/55bfe5891be4b57b091553882eaf7a6062cd8876/mode/src/processing/mode/android/AndroidSDK.java#L391) returns null as the value was not stored earlier in preferences.txt file not even with [Preferences.set("android.sdk.path", folder.getAbsolutePath());](https://github.com/processing/processing-android/blob/55bfe5891be4b57b091553882eaf7a6062cd8876/mode/src/processing/mode/android/AndroidSDK.java#L468)

Steps to reproduce-
Remove the variable ANDROID_SDK from eclipse if using, and delete the preferences.txt folder. Remove any system environment with ANDROID_SDK if present.
On startup, it shows "cannot find an Android SDK" dialog box. Choose any option either "choose sdk path mannually" or "download SDK automatically. After the process, values are not getting saved as "android.sdk.path" in the preferences.txt file. 
Restarting the program opens the same dialog again and `Preferences.get("android.sdk.path")` returns null on logs. I have confirmed the SDK path was used without any space in `Preference.set` and was accessible by `Preferences.get` on runtime.

**Comment by codeanticode** [comment]
@rupeshkumar22 I think the issue is that Preferences.set("android.sdk.path", folder.getAbsolutePath()) does not save the preferences to the file immediately, the PDE writes to the preferences.txt file only on exit.

**Comment by rupeshkumar22** [comment]
@codeanticode thanks for the information, I checked the file after closing PDE window. Might be the case that process was running in background. I will check again. Thanks!

**Comment by rupeshkumar22** [comment]
After closing the PDE properly, The values were getting saved, Thanks for the information.
