### ISSUE TITLE
Shortcut is invisible for `Signed Package Export` in menu.

### ISSUE THREAD

**Issue by rupeshkumar22** [processing/processing-android#702]
Some minor correction is needed, related to showing the shortcut on the right side of the option `Signed Package Export` in the File menu. Currently the shortcut text is not visible on the right side.
Here is a minor issue on startup of mode -

`'Export Signed Package.keystroke.windows' is not understood, please re-read the Java reference for KeyStroke`

**Comment by ranaaditya** [comment]
> Some minor correction is needed, related to showing the shortcut on the right side of the option `Signed Package Export` in the File menu. Currently the shortcut text is not visible on the right side. Here is a minor issue on startup of mode -
> 
> `'Export Signed Package.keystroke.windows' is not understood, please re-read the Java reference for KeyStroke`

hey @rupeshkumar22 did you face this issue earlier ?

or is this first time you are getting it ?

**Comment by rupeshkumar22** [comment]
@ranaaditya It was not faced earlier. It might have been missed during the reimplementation of the Export Package Option in the menu. Earlier it was removed for some time and later it was finalized to be included as discussed by @codeanticode #693 
Not a significant issue, I will do some changes to make it visible along with the major emulator PR.
Thanks

**Comment by ranaaditya** [comment]
> @ranaaditya It was not faced earlier. It might have been missed during the reimplementation of the Export Package Option in the menu. Earlier it was removed for some time and later it was finalized to be included as discussed by @codeanticode #693 Not a significant issue, I will do some changes to make it visible along with the major emulator PR. Thanks

@rupeshkumar22 just tag me in the PR, will review it ASAP 👍
