### ISSUE TITLE
AndrodStudio: NPE when using wearInteractive() in draw()

### ISSUE THREAD

**Issue by berni421** [processing/processing-android#717]
Based on example here: [](https://android.processing.org/tutorials/android_studio/index.html)

Logcat: 

> 17:39:58.400 System.err               W  java.lang.NullPointerException: Attempt to invoke interface method 'boolean processing.android.ServiceEngine.isInAmbientMode()' on a null object reference
> 17:39:58.401 System.err               W  	at processing.core.PApplet.wearInteractive(PApplet.java:8077)
> 17:39:58.401 System.err               W  	at com.elbourn.android.clock2.Sketch.draw(Sketch.java:57)
> 17:39:58.401 System.err               W  	at processing.core.PApplet.handleDraw(PApplet.java:1895)
> 17:39:58.401 System.err               W  	at processing.core.PSurfaceNone.callDraw(PSurfaceNone.java:478)
> 17:39:58.401 System.err               W  	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:518)

Code:

```
try {
            if (wearInteractive()) {  // <---- Sketch.java:57
                frameRate(1);
            } else {
                frameRate(0.1f);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
```

**Comment by codeanticode** [comment]
@berni421 should be fixed with this new release: https://github.com/processing/processing-android/releases/tag/latest
