### ISSUE TITLE
Need to update SDK to 31 and eventually 33

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#722]
New apps submitted to Google Play must target API level 31 by August 1, 2022, and API level 33 by August 1 2023:

https://support.google.com/googleplay/android-developer/answer/11926878?hl=en

**Comment by ranaaditya** [comment]
@codeanticode yes Andres, we need to upgrade the SDK version to these versions, may need to add or update few components in the SDK if needed, have to research more about the it. 

Thanks !

**Comment by codeanticode** [comment]
Seems that no additional components are needed, I will upload b4 with SDK 31 as the requirement.

**Comment by codeanticode** [comment]
Updated to SDK level 33 with https://github.com/processing/processing-android/commit/b5bf1cd1829026d298b248a3e013c758cfd5ea2a
