### ISSUE TITLE
Cannot download system image for watch emulator

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#726]
Tried latest beta, and got this error:

```
processing.mode.android.AndroidSDK$BadSDKException: Emulator could not be downloaded
	at processing.mode.android.AndroidSDK.downloadSysImage(AndroidSDK.java:584)
	at processing.mode.android.AndroidSDK.requestSysImage(AndroidSDK.java:530)
	at processing.mode.android.AVD.ensureProperAVD(AVD.java:466)
	at processing.mode.android.AndroidMode.handleRunEmulator(AndroidMode.java:261)
	at processing.mode.android.AndroidEditor$16.run(AndroidEditor.java:399)
"Could not create a virtual device for the emulator.";
```

**Comment by ranaaditya** [comment]
@codeanticode i think we missed the testing for watches while working on emulator issue.

**Comment by codeanticode** [comment]
No worries, took me by surprise because I think I tested the watch emulator not long ago, but it was using an M1 mac, and this error happened with an Intel mac, so maybe the arch has something to do with it. I also increased the target SDK to 33 recently, perhaps that's another factor to consider.

**Comment by rupeshkumar22** [comment]
Right now I'm working on debugging logs specifically [here](https://github.com/processing/processing-android/blob/1159dd8640e46eb9a958f34b435c43b6a2ff7527/mode/src/processing/mode/android/SysImageDownloader.java#L142), to check system image urls and other information.

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/8af3d11ce18f42191b31cb7ac777687944e03334
