### ISSUE TITLE
Shortcut for run sketch in device and enable debugger is the same

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#734]
Both functionalities use "CTRL + D"

**Comment by ranaaditya** [comment]
> Both functionalities use "CTRL + D"

do we need to change this ?

if yes, then what would be the other shortcut ?

Thanks !

**Comment by ranaaditya** [comment]
> > Both functionalities use "CTRL + D"
> 
> do we need to change this ?
> 
> if yes, then what would be the other shortcut ?
> 
> Thanks !

@p4puniya can start with this issue, looks like this gonna be just an addition to the shortcuts only.

what do you think @codeanticode ?

Thanks !

**Comment by p4puniya** [comment]
Sure , I'll look into it 👍

**Comment by codeanticode** [comment]
I think this could be a good opportunity to revisit all the keyboard shortcuts in the mode and make adjustments based on which ones are the most used, in addition to removing this conflict

**Comment by ranaaditya** [comment]
> I think this could be a good opportunity to revisit all the keyboard shortcuts in the mode and make adjustments based on which ones are the most used, in addition to removing this conflict

fully agree with you @codeanticode

**Comment by ranaaditya** [comment]
> I think this could be a good opportunity to revisit all the keyboard shortcuts in the mode and make adjustments based on which ones are the most used, in addition to removing this conflict

@p4puniya you can pick it up as good start in android-mode, just list down the shortcuts in th mode and see if any shortcut is same for more tha one action just like this issue and can start working on it. But first let us know on which shortcut you are working.

Thanks 1

**Comment by codeanticode** [comment]
There were a few more duplicated shortcuts, fixed with this commit: https://github.com/processing/processing-android/commit/142bffb464407064184a4f3e62337976180db55c
