### ISSUE TITLE
Unable to open JavaFX window in Android mode

### ISSUE THREAD

**Issue by vsquared** [processing/processing-android#736]
The following code fails in Android mode with Processing version 4.2:
```
import javafx.scene.control.Button;

void setup() {
}

void draw() {  
}
```
The error message below is generated:
<img width="789" alt="fxErr" src="https://user-images.githubusercontent.com/2294268/232332770-98143375-abc4-4747-ab10-968993cb7566.png">

**Comment by vsquared** [comment]
In file https://github.com/processing/processing4/blob/main/app/src/processing/app/Library.java **line 436**, should list[] be allowed to be null?

**Comment by ajavamind** [comment]
javafx is not supported in Processing android mode

**Comment by codeanticode** [comment]
@vsquared JavaFX is not supported in the Android mode, but you may find ways of using by using existing JavaFX ports for mobile, some resources below:

https://stackoverflow.com/questions/49238603/how-to-run-javafx-in-android-studio-and-make-imageview

https://www.reddit.com/r/JavaFX/comments/q4vi50/can_javafx_application_be_deployed_to_android/
