### ISSUE TITLE
No connected devices

### ISSUE THREAD

**Issue by clankill3r** [processing/processing-android#751]
Under `Android > Devices >` I get `No connected devices`.

Processing 4.3
Windows 10

I can try on OSX in like a week or so.

The android version is old (7.0), but it did work before (last time I used was like 2 years ago).

**Comment by ranaaditya** [comment]
> Under `Android > Devices >` I get `No connected devices`.
> 
> Processing 4.3 Windows 10
> 
> I can try on OSX in like a week or so.
> 
> The android version is old (7.0), but it did work before (last time I used was like 2 years ago).

hi @clankill3r are you getting any error logs for this in processing console ?

You can cross check it -> try using ADB (Android Debugging Bridge) and see if its showing any existing android connected device.

`
adb usb
`

`
adb devices
`

Thanks,
Aditya

**Comment by clankill3r** [comment]
I think I eventually fixed it, I don't have my android near me, so I will check asap.
I think I had todo several steps, will report back later.
