### ISSUE TITLE
Tiny wrong mistake in documentation

### ISSUE THREAD

**Issue by clankill3r** [processing/processing-android#752]
https://android.processing.org/reference/permissions/query.html

This:

`println("No permission to read location", width/2, height/2);` 

should be:

`text("No permission to read location", width/2, height/2);`

**Comment by rupeshkumar22** [comment]
This should be on [processing-android-website](https://github.com/codeanticode/processing-android-website/issues)
reopening it there.

**Comment by ranaaditya** [comment]
Closing it, issue raised at processing-website repo.

Thanks @clankill3r for reporting it !

Thanks,
Aditya
