### ISSUE TITLE
wiki page Android outdated (ia32libs)

### ISSUE THREAD

**Issue by nonchip** [processing/processing-android#84]
in https://github.com/processing/processing-android/wiki#Linux_Users there's a command line targeting ubuntu users:

     sudo apt-get install ia32-libs

this package isn't in the ubuntu repos anymore, because foreign-arch packages are now installed using

    sudo apt-get install <arch>:<package>

**Comment by codeanticode** [comment]
Wiki has been updated by @omerjerk  and myself. Thanks!
