### ISSUE TITLE
File won't compile

### ISSUE THREAD

**Issue by Bazmundi** [processing/processing-android#87]
On windows 7 box.

I downloaded Processing 3.0a4 64 bit.

I setup JAVA_HOME, ANT_HOME, ANDROID_HOME, ADB_HOME variables.

I made sure every variable turned up in path.

Pointed to ADT

Set Android mode.

Loaded hello world and kaput.

![procbang](https://cloud.githubusercontent.com/assets/1772587/5057525/f3ef8cbe-6d14-11e4-81f5-2f49b97e7217.png)

Any suggestions as to what I missed?

Cheers,
B

**Comment by Ariane98** [comment]
Hi
I'm having the same problem with Processing 2.2.1
I'm not sure how to install the new version of AndroidMode though...do I need to compile the whole git folder ?

**Comment by ManickamRM** [comment]
Getting Error while running on Device:
Hi
 I am also getting the same error(RUNNING ERROR IN JAVAC.EXE COMPILER) in windows 7 32-bit and i am using processing 2.2.1.I have downloaded all the files in andriod sdk except images.
 I have set all the path variables ANDRIOD_HOME,JAVA_HOME,ANT_HOME,ADB_HOME,PATH 
 ANDRIOD_HOME=C:\Users\Acer\AppData\Local\Android\android-sdk\tools
 ANT_HOME=C:\Users\Acer\AppData\Local\Android\android-sdk\tools\ant
 ADB_HOME= C:\Users\Acer\AppData\Local\Android\android-sdk\platform-tools
 JAVA_HOME=C:\ProgramFiles\Java\jdk1.7.0_67\bin;
 PATH =C:\ProgramData\Oracle\Java\javapath;
               %JAVA_HOME%;%ANT_HOME%;ADB_HOME%;%ANDROID_HOME%
 I am trying to fix this problem more than 10 days can any one help me 

![processing](https://cloud.githubusercontent.com/assets/13126962/8445702/45e3cbb4-1fbe-11e5-8485-d8ccbbbd42bc.jpg)
