### ISSUE TITLE
redraw() doesn't work with P3D on Android

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#9]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Sunday May 12, 2013 at 21:51 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/10_

----

Original report: http://code.google.com/p/processing/issues/detail?id=1077

**Comment by codeanticode** [comment]
works with latest release of the mode
