### ISSUE TITLE
Does the "Export Signed Package" feature work for other people? 

### ISSUE THREAD

**Issue by joemckay5** [processing/processing-android#92]
At first I was getting the error "java.io.IOException: Cannot run program "/Applications/Processing.app/Contents/PlugIns/jdk1.7.0_55.jdk/Contents/Home/jre/bin/keytool": error=2, No such file or directory". Then I copied a version of keytool from Library/java/ into that folder and now it gives me a long list of java.lang.Exception errors.
I'm on mac  10.9.5, Processing 2.2.1, and Java is up to date.

**Comment by codeanticode** [comment]
Hello, the Android Mode release that includes the export signed package functionality requires Processing 3.0 or higher. Not sure if you can make it work properly in 2.2.1. You could try to copy the keytool file from precisely the 1.7.0_55 version of the JDK into /Applications/Processing.app/Contents/PlugIns/jdk1.7.0_55.jdk/Contents/Home/jre/bin/. Maybe the keytool you copied from Library/java/ corresponded to another JDK version, and that's the reason for the errors. 

In any case, the latest android mode is only supported in Processing 3.0+

**Comment by joemckay5** [comment]
Thanks for writing back. I've updated to 3.0a5. 
Now I'm getting an error saying "java.io.IOException: Cannot run program "/Users/username/Developer/android-sdk-macosx/build-tools/.DS_Store/zipalign": error=20, Not a directory
Does this indicate that I have not installed something?

**Comment by XshadowlynxX** [comment]
.DS_Store is a hidden file that mac osx puts in every directory you've visited. I don't know how to fix this problem but it sounds like processing is trying to read .DS_Store as a directory. So I think it's processing's fault.

**Comment by omerjerk** [comment]
It is working fine on Ubuntu.

**Comment by codeanticode** [comment]
@joemckay5 I haven't seen this error (testing on Mac OSX 10.9.5 with latest 3.0 beta and android mode), but if you have chance please confirm is still happening on your system.

**Comment by codeanticode** [comment]
No confirmation from original poster, cannot reproduce
