### ISSUE TITLE
sketch doesn't open in emulator

### ISSUE THREAD

**Issue by sunofkyuss** [processing/processing-android#93]
![ekran alintisi](https://cloud.githubusercontent.com/assets/9921265/5593953/bff2e3d0-9239-11e4-81fc-a8f7409cb5f6.PNG)

it gets stuck at that "Runnig sketch on device..." writing.
I did the port setting in preferences.txt
and virtual machine's name is Processing-0221. (I am not so sure if this is matter)

what am I supposed to do for running a sketch in emulator?

**Comment by codeanticode** [comment]
could a misconfiguration in the system, not possible to tell from the information available.
