### ISSUE TITLE
no android mode in mode manager

### ISSUE THREAD

**Issue by jeboyd** [processing/processing-android#94]
I had android mode enabled on 2.2.1 but was having some trouble.  I "removed" android mode thinking I could re-install.  Now Mode Manager does not show Android Mode. 

![mode-manager](https://cloud.githubusercontent.com/assets/10457178/5673798/54e6ad22-975e-11e4-9d97-173f6e04d2c3.png)

**Comment by joemckay5** [comment]
You need to do it manually. Your sketchbook folder should now have a "modes" folder in it along with "libraries". Download android mode and put it in this folder. Restart Processing and it should work.

**Comment by pdonoso** [comment]
I downloaded as Zip and then copied the unzipped folder in the modes folder, but it still doesn't appear. What could I do?

**Comment by joemckay5** [comment]
This step circumvents the mode manager window. Click the "java" button on a sketch and Android should be one of the modes you can switch to.

**Comment by hcrux** [comment]
I've the same problem and I can't fix it. I've made all the steps as pdonoso and still I dont have androidMode to chose. How can i solve it? should i give up on processing?

**Comment by jeboyd** [comment]
I solved the problem by restoring the files to the modes folder from a backup.  I suppose I could have done this by downloading instead.

**Comment by TheRealSimJoo** [comment]
Same problem here. Can't install the mode, I tried about everything... Anyone any ideas?

**Comment by ashleyjamesbrown** [comment]
same thing here. i tried copying it back in to the modes folder and no joy - it doesnt show up as a mode.

**Comment by codeanticode** [comment]
I have tried installing the Android mode on 2.2.1 without problems on Mac (10.9.5, don't think that matters). However, the version of the mode available for 2.2.1 is quite buggy, I'd recommend using the one for 3.0a5, or wait until the 3.0 beta and the accompanying android mode come out. We will be making a push to update the android mode during this year's Google Summer of Code.
