### ISSUE TITLE
Use in eclipse?

### ISSUE THREAD

**Issue by yass-n** [processing/processing-android#99]
Is there a way to use processing-android as a library so it can be added to eclipse projects?

**Comment by omerjerk** [comment]
There's no way to do this as of now. I'll see if anything can be done.

**Comment by yass-n** [comment]
Already in the [wiki](https://github.com/processing/processing-android/wiki#Using_Eclipse_for_Development), sorry. The solution in this [link](http://blog.onthewings.net/2013/04/25/setting-up-a-processing-android-project-in-eclipse/) works.

**Comment by omerjerk** [comment]
cool. I didn't know.
